import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
import {safeAsset,fromPixeria,instancesFor} from './model.mjs';
const source=fs.readFileSync(new URL('./store.js',import.meta.url),'utf8');
function harness(){const values=new Map(),events=new Map();const root={localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)},addEventListener:(k,f)=>events.set(k,f),dispatchEvent(){}};vm.runInNewContext(source,{window:root,Event:class{}});return {store:root.XpaceInventory,values,events};}
test('visibility survives reload, isolates spaces and instances, and never changes layout positions or collisions',()=>{
 const h=harness(),layout=[{id:'counter',type:'counter',col:1,row:2},{id:'counter-2',type:'counter',col:4,row:2}],before=JSON.stringify(layout);h.store.setVisible('xtanco','counter',false);
 assert.deepEqual(h.store.filter('xtanco',layout).map(x=>x.id),['counter-2']);assert.equal(h.store.filter('supermercado',layout).length,2);assert.equal(JSON.stringify(layout),before);
 vm.runInNewContext(source,{window:{localStorage:{getItem:k=>h.values.get(k)},addEventListener(){}},Event:class{}});
 h.store.setVisible('xtanco','counter',true);assert.equal(h.store.filter('xtanco',layout).length,2);h.store.restore('xtanco');assert.equal(h.store.visible('xtanco','counter'),true);
});
test('cross-tab changes notify current listeners and unsubscribe stops updates',()=>{const h=harness();let hits=0;const off=h.store.subscribe(s=>{assert.equal(s,'xtanco');hits++;});h.events.get('storage')({key:'xpaceos:inventari:v1:xtanco'});assert.equal(hits,1);off();h.events.get('storage')({key:'xpaceos:inventari:v1:xtanco'});assert.equal(hits,1);});
test('invalid records and unavailable storage fail without success notification',()=>{const h=harness();assert.throws(()=>h.store.setVisible('xtanco','__proto__',false));h.values.set('xpaceos:inventari:v1:xtanco','invalid');assert.equal(h.store.visible('xtanco','counter'),true);});
test('Pixeria preserves source identity and rejects executable or unrelated URLs',()=>{assert.equal(safeAsset('javascript:alert(1)'),null);assert.equal(safeAsset('https://example.com/x.png'),null);const a=fromPixeria({type:'furni',id:'one',url:'https://api.admira.store/stock/asset/one',fp:[2,1]});assert.equal(a.id,'pixeria:one');assert.equal(instancesFor(a,[{id:'placed',type:'custom',img:a.img}]).length,1);assert.equal(fromPixeria({type:'video'}),null);});
test('catalog contains all native creator types and immutable factory instance identities',()=>{
 const data=JSON.parse(fs.readFileSync(new URL('./catalog.json',import.meta.url)));const game=fs.readFileSync(new URL('../admira-xp/index.html',import.meta.url),'utf8');const literal=game.split('const XPACE_CREATOR_FURNITURE_CATALOG=')[1].split(';\nconst XPACE_CREATOR_STAFF')[0];const cats=vm.runInNewContext('('+literal+')');assert.deepEqual(data.native.map(x=>x.type).sort(),Object.values(cats).flat().map(x=>x.type).sort());assert.equal(new Set(data.layouts.xtanco.map(x=>x.id)).size,data.layouts.xtanco.length);
});
test('Good and snapshots share the presentation filter; no saveLayout or collision mutation in inventory bridge',()=>{const s=fs.readFileSync(new URL('../admira-xp/index.html',import.meta.url),'utf8');const bridge=s.slice(s.indexOf('function inventoryPresentationLayout'),s.indexOf('function drawShop(){'));assert.match(bridge,/store.filter\(space,shopLayout\)/);assert.doesNotMatch(bridge,/saveLayout|shopLayout\s*=|hardness/);assert.match(s,/for\(const item of renderLayout\)/);assert.match(s,/layout:moving\?\[\]:\(shopFurnitureVisible\|\|editorSceneActive\?inventoryPresentationLayout\(\)/);});
