import {hydrateLibrary,libraryEntry} from './library-runtime.mjs?v=cafebreria-1';
import {mountCapsulas} from './capsulas.mjs?v=cafebreria-1';
export async function mountLibraryStage(host,api){
 const en=document.documentElement.lang==='en',abort=new AbortController();
 hydrateLibrary(api.root);const shelf=api.root.getObjectByName('estanteria-libros'),controller=mountCapsulas({scene:api.scene,entries:[libraryEntry(shelf)],signal:abort.signal});controller.setViewer(api);controller.attachUI({stage:api.canvas.parentElement,canvas:api.canvas,on:(el,type,fn)=>{el.addEventListener(type,fn,{signal:abort.signal});}});
 const section=document.createElement('section');section.className='library-stage-controls';const button=document.createElement('button');button.textContent=en?'Explore books, records and TV':'Explorar libros, vinilos y tele';button.onclick=()=>controller.enterDetail();const link=document.createElement('a');link.href='/xpacios/cafebreria/?ver=estanteria-libros';link.textContent=en?'View in the recovered café ↗':'Ver en la cafetería recuperada ↗';const download=document.createElement('a');download.href='/inventario/cafebreria/library.package.json';download.download='cafebreria-library.package.json';download.textContent=en?'Download interactive package manifest ↓':'Descargar manifiesto interactivo ↓';const note=document.createElement('p');note.textContent=en?'In another XpaceOS project: /inventario añadir 51. The GLB contains geometry; XpaceOS adds its interactive behavior.':'En otro proyecto de XpaceOS: /inventario añadir 51. El GLB conserva la geometría; XpaceOS incorpora su comportamiento interactivo.';section.append(button,link,download,note);host.append(section);
 await controller.ready;const list=document.createElement('select');list.setAttribute('aria-label',en?'Select book':'Seleccionar libro');const empty=document.createElement('option');empty.textContent=en?'Choose a book…':'Elige un libro…';empty.value='';list.append(empty);for(const b of controller.state.books){const option=document.createElement('option');option.value=b.id;option.textContent=b.libro;list.append(option);}list.onchange=()=>{if(list.value){controller.enterDetail();controller.openBook(list.value);}};section.append(list);api.draw();
 return()=>{abort.abort();section.remove();};
}
