import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const {createAnnouncements}=createRequire(import.meta.url)('../admira-xp/scripts/announcements.js');
const flush=()=>new Promise(resolve=>setImmediate(resolve));
function harness(generate){const players=[],timers=[];let ducks=0,releases=0;class Audio{constructor(url){this.url=url;players.push(this);}play(){this.onplaying?.();return Promise.resolve();}pause(){this.paused=true;}removeAttribute(){}load(){}}
 const api=createAnnouncements({generate,Audio,duck(){ducks++;return ()=>releases++;},schedule(fn){timers.push(fn);return fn;},unschedule(fn){const i=timers.indexOf(fn);if(i>=0)timers.splice(i,1);}});return {api,players,timers,get ducks(){return ducks;},get releases(){return releases;}};}
test('premium generates exact full text once, plays the same audio three times and releases resources',async()=>{let calls=0,disposed=0;const text='Atención. '+('Texto completo. '.repeat(70));const h=harness(async(t,opts)=>{calls++;assert.equal(t,text.trim());assert.equal(opts.voice,'male');return {url:'blob:one',release(){disposed++;}};});assert.equal(h.api.play(text,{voice:'male',language:'en'}),true);assert.equal(h.api.state().phase,'generating');await flush();assert.equal(calls,1);assert.equal(h.api.state().language,'es-ES');assert.equal(h.ducks,1);const audio=h.players[0];for(let i=0;i<3;i++){audio.onended();if(i<2)h.timers.shift()();}assert.equal(h.api.state().phase,'done');assert.equal(h.api.state().completed,3);assert.equal(h.players.length,1);assert.equal(h.releases,1);assert.equal(disposed,1);});
test('stop during generation aborts and a late response cannot play or alter music',async()=>{let resolve,signal,disposed=0;const h=harness((_,opts)=>{signal=opts.signal;return new Promise(r=>resolve=r);});h.api.play('Hola',{voice:'female'});await flush();h.api.stop();assert.equal(signal.aborted,true);resolve({url:'blob:late',release(){disposed++;}});await flush();assert.equal(h.players.length,0);assert.equal(h.ducks,0);assert.equal(disposed,1);assert.equal(h.api.state().phase,'stopped');});
test('replacement ignores old generation and stop between readings clears replay',async()=>{let first;const h=harness(text=>text==='Antes'?new Promise(r=>first=r):Promise.resolve({url:'blob:now'}));h.api.play('Antes',{voice:'male'});await flush();h.api.play('Ahora',{voice:'female'});await flush();first({url:'blob:old'});await flush();assert.equal(h.players.length,1);assert.equal(h.players[0].url,'blob:now');h.players[0].onended();h.api.stop();assert.equal(h.timers.length,0);assert.equal(h.players[0].paused,true);assert.equal(h.releases,1);});
test('generation and playback errors never fall back to free speech or claim completion',async()=>{const error=new Error();error.code='auth';const h=harness(async()=>{throw error;});h.api.play('Hola',{voice:'male'});await flush();assert.equal(h.api.state().error,'auth');assert.equal(h.ducks,0);const p=harness(async()=>({url:'blob:one'}));p.api.play('Hola',{voice:'female'});await flush();p.players[0].onerror();assert.equal(p.api.state().phase,'error');assert.equal(p.api.state().completed,0);assert.equal(p.releases,1);});
test('muted and oversized premium requests never invoke the paid generator',async()=>{let calls=0;const h=harness(async()=>{calls++;});assert.equal(h.api.play('Hola',{voice:'female',muted:true}),false);assert.equal(h.api.play('x'.repeat(1501),{voice:'male'}),false);await flush();assert.equal(calls,0);});
