import test from 'node:test';import assert from 'node:assert/strict';import {onRequest} from '../functions/admira-xp/announcement-tts.js';import {siteForHost} from '../functions/_perimetro.js';
const origin='https://www.admira.store',site=siteForHost('www.admira.store');const env={PERIMETRO_SIGNING_KEY:'test-signing-key'};
async function request(body,originHeader=origin){const now=Math.floor(Date.now()/1000),part=Buffer.from(JSON.stringify({v:1,aud:site.id,email:'csilvasantin@gmail.com',iat:now,exp:now+60})).toString('base64url');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.PERIMETRO_SIGNING_KEY),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode('perimetro:'+part))).toString('base64url');const token=part+'.'+sig;return new Request(origin+'/admira-xp/announcement-tts',{method:'POST',headers:{'Content-Type':'application/json',Origin:originHeader,Cookie:'__Host-perimetro_session='+token},body:JSON.stringify(body)});}
test('unauthenticated requests cannot invoke the private generator',async()=>{let calls=0;const res=await onRequest({env:{...env,ANNOUNCEMENT_TTS:{generate(){calls++;}}},request:new Request(origin+'/admira-xp/announcement-tts',{method:'POST',body:'{}'})});assert.equal(res.status,401);assert.equal(calls,0);});
test('authorized session invokes the narrow private binding with exact text and chosen voice',async()=>{let input;const res=await onRequest({env:{...env,ANNOUNCEMENT_TTS:{generate(body){input=body;return new Response('MP3',{headers:{'Content-Type':'audio/mpeg'}});}}},request:await request({text:'Texto exacto.',voice:'female'})},async()=>Response.json({allowed:true}));assert.equal(res.status,200);assert.deepEqual(input,{text:'Texto exacto.',voice:'female',language:'es'});assert.equal(await res.text(),'MP3');assert.equal(res.headers.get('X-Announcement-Model'),'eleven_v4');});
test('cross-site, arbitrary voices and too-long text cannot invoke the generator',async()=>{let calls=0;const secure={...env,ANNOUNCEMENT_TTS:{generate(){calls++;}}};for(const [body,header,status] of [[{text:'Hola',voice:'male'},'https://other.example',403],[{text:'Hola',voice:'constructor'},origin,400],[{text:'x'.repeat(1501),voice:'male'},origin,400],[{text:'Hola',voice:'male',language:'constructor'},origin,400]]){const res=await onRequest({env:secure,request:await request(body,header)},async()=>Response.json({allowed:true}));assert.equal(res.status,status);}assert.equal(calls,0);});

test('English male and female selection reaches the private generator with language en',async()=>{for(const voice of ['male','female']){let sent;const res=await onRequest({env:{...env,ANNOUNCEMENT_TTS:{generate(body){sent=body;return new Response('MP3',{headers:{'Content-Type':'audio/mpeg'}});}}},request:await request({text:'Thank you.',voice,language:'en'})},async()=>Response.json({allowed:true}));assert.equal(res.status,200);assert.deepEqual(sent,{text:'Thank you.',voice,language:'en'});assert.equal(res.headers.get('X-Announcement-Language'),'en');}});

const {onRequest:imageRequest}=await import('../functions/admira-xp/advertising-image.js');
test('image preview cannot invoke paid generation without a perimeter session or with a cross-site request',async()=>{let calls=0;const secure={...env,ANNOUNCEMENT_TTS:{generateImage(){calls++;}}};const unauth=await imageRequest({env:secure,request:new Request(origin+'/admira-xp/advertising-image',{method:'POST',body:'{}'})});assert.equal(unauth.status,401);const cross=await imageRequest({env:secure,request:await request({text:'Coffee',language:'en'},'https://other.example')},async()=>Response.json({allowed:true}));assert.equal(cross.status,403);assert.equal(calls,0);});
test('image preview forwards only the exact brief and supported language via the existing binding',async()=>{let sent;const r=await imageRequest({env:{...env,ANNOUNCEMENT_TTS:{generateImage(input){sent=input;return Response.json({ok:true,b64:'fixture'});}}},request:await request({text:'  Full coffee offer  ',language:'en',n:99,model:'pro'})},async()=>Response.json({allowed:true}));assert.equal(r.status,200);assert.deepEqual(sent,{text:'Full coffee offer',language:'en'});assert.deepEqual(await r.json(),{ok:true,b64:'fixture'});});
