import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {readFileSync} from 'node:fs';import vm from 'node:vm';
const {createAnnouncements}=createRequire(import.meta.url)('../admira-xp/scripts/announcements.js');
// Desde el 7-oct-2026 la locución suena UNA vez por defecto; la repetición sigue existiendo con `times` y es lo que cubren estas pruebas.
function setup(times=3){const spoken=[],timers=new Map();let next=0,suppression=0,resumed=0;const synthesis={cancel(){},resume(){resumed++;},getVoices:()=>[{lang:'en-US',name:'English'},{lang:'es-ES',name:'Castellano'}],speak(u){spoken.push(u);u.onstart();}};const api=createAnnouncements({...(times==='default'?{}:{times}),synthesis,Utterance:class{constructor(text){this.text=text;}},duck(){suppression++;let released=false;return ()=>{if(!released){released=true;suppression--;}};},schedule(fn){timers.set(++next,fn);return next;},unschedule:id=>timers.delete(id)});return {api,spoken,synthesis,timers,get suppression(){return suppression;},get resumed(){return resumed;},advance(){const [id,fn]=timers.entries().next().value;timers.delete(id);fn();}};}
test('one click reads the exact text three times sequentially and restores music only after completion',()=>{const h=setup(),text='Buenas tardes. '+('Texto sin recortar. '.repeat(50)).trim();assert.equal(h.api.play(text),true);assert.equal(h.spoken.length,1);assert.equal(h.suppression,1);for(let i=0;i<3;i++){assert.equal(h.spoken[i].text,text);assert.equal(h.spoken[i].lang,'es-ES');assert.equal(h.spoken[i].voice.name,'Castellano');assert.equal(h.spoken[i].volume,1);h.spoken[i].onend();assert.equal(h.api.state().completed,i+1);if(i<2){assert.equal(h.suppression,1);assert.equal(h.spoken.length,i+1);h.advance();}}assert.equal(h.api.state().phase,'done');assert.equal(h.suppression,0);assert.equal(h.timers.size,0);assert.equal(h.resumed,3);});
test('English interface selects an English voice and each batch retains its starting language',()=>{const h=setup(),opts={language:'en'};h.api.play('Welcome',opts);opts.language='es';h.spoken[0].onend();h.advance();assert.equal(h.spoken[1].lang,'en-US');assert.equal(h.spoken[1].voice.name,'English');h.api.stop();});
test('Stop cancels a pending repetition and stale end events cannot restart it',()=>{const h=setup();h.api.play('Hola');const old=h.spoken[0];old.onend();assert.equal(h.timers.size,1);h.api.stop();old.onend();assert.equal(h.timers.size,0);assert.equal(h.spoken.length,1);assert.equal(h.suppression,0);assert.equal(h.api.state().phase,'stopped');});
test('a new click replaces the previous batch and ignores its stale callbacks',()=>{const h=setup();h.api.play('Antes');const old=h.spoken[0];h.api.play('Ahora');old.onend();old.onerror({error:'canceled'});assert.equal(h.api.state().phase,'speaking');assert.equal(h.api.state().completed,0);assert.equal(h.suppression,1);h.spoken[1].onend();h.advance();assert.equal(h.spoken[2].text,'Ahora');h.api.stop();});
test('by default the announcement is read exactly once (Carlos, 7-oct-2026: one reading, not three)',()=>{const h=setup('default'),d=setup(1);for(const x of [h,d]){assert.equal(x.api.play('Hola'),true);assert.equal(x.api.state().total,1);x.spoken[0].onend();assert.equal(x.api.state().phase,'done');assert.equal(x.api.state().completed,1);assert.equal(x.spoken.length,1);assert.equal(x.timers.size,0);assert.equal(x.suppression,0);}});
test('speech errors restore music and never report successful completion or retry silently',()=>{const h=setup();h.api.play('Hola');h.spoken[0].onerror({error:'audio-busy'});h.spoken[0].onend();assert.equal(h.api.state().phase,'error');assert.equal(h.api.state().completed,0);assert.equal(h.suppression,0);assert.equal(h.timers.size,0);h.synthesis.speak=()=>{throw Error('unavailable');};assert.equal(h.api.play('Hola'),false);assert.equal(h.suppression,0);});
test('empty text, master mute and unavailable speech cannot start a silent batch',()=>{const h=setup();assert.equal(h.api.play('  '),false);assert.equal(h.api.state().error,'empty');assert.equal(h.api.play('Hola',{muted:true}),false);assert.equal(h.api.state().error,'muted');assert.equal(h.spoken.length,0);assert.equal(h.suppression,0);const missing=createAnnouncements();assert.equal(missing.play('Hola'),false);assert.equal(missing.state().error,'unsupported');});
test('native menu dispatch uses the shared controller and editable field instead of an inaccessible CLI closure',()=>{const html=readFileSync(new URL('../admira-xp/index.html',import.meta.url),'utf8');const code=html.match(/  if\(id==='mega'\)[^\n]+\n  if\(id==='megaStop'\)[^\n]+/)[0];let got,stopped=0;const context=vm.createContext({lang:'es',dsMasterMute:false,document:{getElementById:id=>id==='announcementText'?{value:'Oferta de hoy'}:null},window:{XpaceAnnouncements:{play:(text,opts)=>got={text,opts},stop:()=>stopped++}}});vm.runInContext('function action(id){'+code+'}',context);context.action('mega');assert.equal(got.text,'Oferta de hoy');assert.equal(got.opts.language,'es');assert.equal(got.opts.muted,false);context.action('megaStop');assert.equal(stopped,1);assert.match(html,/<textarea id="announcementText"/);assert.match(html,/Public Announcement System/);assert.match(html,/es:'Locuciones'/);assert.match(html,/function stopAllMedia\(\)\{\s*window.XpaceAnnouncements\?\.stop\(\)/);});
test('web documentation and MCP catalogues agree on three local readings and retained CLI commands',()=>{for(const rel of ['admira-xp/help.html','help/index.html','help/cli/index.html','mcp/index.html','mcp/llms.txt','mcp/manifest.json','mcp/funcionalidades.json','admira-xp/docs/announcements.md']){const text=readFileSync(new URL('../'+rel,import.meta.url),'utf8');for(const phrase of ['Locuciones','Make Announcement','es-ES','en-US','/comunicar','/aviso','announcements.md'])assert.ok(text.includes(phrase),rel+' '+phrase);}});
// Carlos, 7-oct-2026: la locución PARA el hilo musical que esté sonando y lo devuelve al terminar; /audio mute impide arrancarla.
test('DOM integration pauses the playing twin music for the announcement, resumes it afterwards and obeys the master mute',()=>{const status={dataset:{}},button={setAttribute(){}},input={addEventListener(){}},player=o=>({...o,pauses:0,plays:0,pause(){this.pauses++;this.paused=true;},play(){this.plays++;this.paused=false;return Promise.resolve();}}),music=player({volume:0.7,paused:false,muted:false,currentTime:42}),starbucks=player({volume:0.5,paused:true,muted:true,currentTime:80});const spoken=[];const document={documentElement:{lang:'es'},getElementById:id=>({announcementStatus:status,announcementText:input,bgMusic:music,starbucksMusic:starbucks}[id]),querySelector:()=>button};const window={document,addEventListener(){},speechSynthesis:{cancel(){},speak(u){spoken.push(u);u.onstart();}},SpeechSynthesisUtterance:class{constructor(text){this.text=text;}}};vm.runInNewContext(readFileSync(new URL('../admira-xp/scripts/announcements.js',import.meta.url),'utf8'),{window,setTimeout,clearTimeout,Promise});window.XpaceAnnouncements.play('Hola');assert.equal(music.paused,true);assert.equal(music.pauses,1);assert.equal(window.__xpaceMusicHeld.has(music),true);assert.equal(music.volume,0.7);assert.equal(starbucks.pauses,0);window.XpaceAnnouncements.stop();assert.equal(music.paused,false);assert.equal(music.plays,1);assert.equal(window.__xpaceMusicHeld.size,0);assert.equal(music.currentTime,42);assert.equal(starbucks.paused,true);assert.equal(starbucks.plays,0);assert.equal(starbucks.muted,true);assert.equal(status.dataset.phase,'stopped');window.dsMasterMute=true;const before=spoken.length;assert.equal(window.XpaceAnnouncements.play('Hola'),false);assert.equal(window.XpaceAnnouncements.state().error,'muted');assert.equal(spoken.length,before);assert.equal(music.pauses,1);let last=null;assert.equal(window.XpaceAnnouncements.playStock('https://x/a.mp3','Hola',{onState:s=>last=s}),false);assert.equal(last.error,'muted');});
