import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../admira-xp/scripts/created-media-history.js',import.meta.url),'utf8');
const store=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};};
function runtime(localStorage,sessionStorage=store(),loc='alsea-sbux-021'){const events=[];const root={location:{href:'https://www.admira.store/admira-xp/?loc='+loc},localStorage,sessionStorage,dispatchEvent:e=>events.push(e),CustomEvent:class{constructor(type,o){this.type=type;this.detail=o.detail;}}};vm.runInNewContext(source,{window:root,URL,Date,JSON,Number,encodeURIComponent});return {api:root.XpaceCreatedMedia,events};}
const receipt=n=>({id:'test-'+n,url:'https://api.admira.store/stock/asset/test-'+n,title:'Contenido '+n});
test('completed receipts survive another tab/session, preserve Xpace isolation and never autoplay',()=>{const local=store(),a=runtime(local);a.api.add('voice',receipt(1));const b=runtime(local);assert.equal(b.api.list()[0].title,'Contenido 1');assert.equal(b.events.length,0);assert.equal(runtime(local,store(),'other-room').api.list().length,0);});
test('a creator can finish before PREVIEWS is loaded; canonical Stock URLs and newest six are recoverable',()=>{const local=store(),r=runtime(local);for(let i=0;i<8;i++)r.api.add('image',receipt(i));assert.equal(r.api.list().length,6);assert.equal(r.api.list()[0].id,'test-7');r.api.add('music',{...receipt(9),url:'https://stock.admira.store/stock/test-9/asset.mp3'});assert.equal(runtime(local).api.list()[0].url,receipt(9).url);assert.equal(r.api.add('video',{...receipt(10),url:'https://foreign.example/movie.mp4'}),null);r.api.clear();assert.equal(runtime(local).api.list().length,0);});
test('legacy session previews migrate once without modifying their Stock identity',()=>{const session=store();session.setItem('xpaceos.expert-previews.v1',JSON.stringify([{kind:'video',...receipt(1)}]));const local=store();assert.equal(runtime(local,session).api.list()[0].id,'test-1');assert.equal(runtime(local).api.list()[0].id,'test-1');});
test('a completed paid job records its receipt before any preview UI or Stock link exists',async()=>{const local=store(),{api}=runtime(local);const root={XpaceCreatedMedia:api,crypto,URL,AbortSignal,sessionStorage:store(),setTimeout,clearTimeout,document:{documentElement:{lang:'es'},getElementById:()=>null,querySelectorAll:()=>[]},fetch:async()=>Response.json({ok:true,job:{status:'done',stock:receipt(42)}})};vm.runInNewContext(readFileSync(new URL('../admira-xp/scripts/media-stock.js',import.meta.url),'utf8'),{window:root,URL,Date,JSON,Error});await root.XpaceMedia.generate('image',{text:'Oferta de Alsea',language:'es'});const recovered=runtime(local).api.list()[0];assert.equal(recovered.title,'Oferta de Alsea');assert.equal(recovered.id,'test-42');});
