import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../admira-xp/scripts/ipad-cola.js',import.meta.url),'utf8');
function runtime(){let state={recibido:[],preparando:[],listo:[]},fail=false;const intervals=[];const root={addEventListener(){},document:{querySelector:()=>true,addEventListener(){}},localStorage:{getItem:()=>null},XpaceStarbucks:{active:()=>true},XpaceScreenMedia:{get:()=>null,draw:()=>false}};vm.runInNewContext(source,{window:root,location:{search:''},URLSearchParams,Map,Set,Date,setInterval:f=>intervals.push(f),setTimeout(){},fetch:async()=>{if(fail)throw Error('offline');return {json:async()=>state};}});return {api:root.XpaceIpadCola,media:root.XpaceScreenMedia,poll:intervals[0],set:s=>{state=s;},fail:()=>{fail=true;}};}
function canvas(){const texts=[],transforms=[];let saves=0;const ctx=new Proxy({save(){saves++;},restore(){saves--;},translate(...v){transforms.push(v);},fillText:t=>texts.push(t),measureText:t=>({width:t.length*14})},{get:(o,k)=>k in o?o[k]:()=>{}});return {ctx,texts,transforms,saves:()=>saves};}
test('idle canvas fills the screen and returns after every queue phase',async()=>{const r=runtime();for(const phase of ['recibido','preparando','listo']){r.set({[phase]:[{numero:'A001',nombre:'QA'}]});await r.poll();assert.equal(r.api.demo(),false,phase);let c=canvas();r.api.draw(c.ctx,1024,768);assert.ok(c.texts.includes('🧾 Recibido'));assert.equal(c.saves(),0);r.set({recibido:[],preparando:[],listo:[]});await r.poll();assert.equal(r.api.demo(),true);c=canvas();r.api.draw(c.ctx,1024,768);assert.ok(c.transforms.some(([x,y])=>x===512&&y===384));assert.ok(!c.texts.includes('✅ ¡Preparado!'));assert.ok(!c.texts.includes('☁️ ADMIRITO · COLA'));assert.equal(c.saves(),0);}});
test('offline keeps the last active phase; user preview retains priority',async()=>{const r=runtime();r.set({preparando:[{numero:'A001'}]});await r.poll();r.fail();await r.poll();assert.equal(r.api.demo(),false);assert.equal(r.media.get('starbucks-ipad-01').kind,'web-app');assert.equal(r.media.get('other'),null);assert.equal(new URL(r.api.url()).searchParams.get('voz'),'0');});
