import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const html=readFileSync(new URL('../admira-xp/index.html',import.meta.url),'utf8');
const helper=html.slice(html.indexOf('function dsMatrixAdapter'),html.indexOf('function dsSurfaceLabel'));
const pin=html.slice(html.indexOf('function dsPinSurface('),html.indexOf('// Pin de una superficie desde'));
const hit=html.slice(html.indexOf('function dsSurfaceAtClientPoint'),html.indexOf('function dsUpdateDragHighlight'));
function context({active=true}={}){const seen=[],api={isActive:()=>true,devices:()=>[{id:'starbucks-wall-06',label:'1'}],screenAt:()=>null,previewScreen:async(id,track)=>seen.push({id,track})};const ctx=vm.createContext({seen,window:{XpaceMatrixOptions:api},document:{body:{classList:{contains:()=>active}},getElementById:()=>{throw Error('Good renderer used');}},DS_SURFACES:[{id:'ds1'}],DS_PIN:{},VIDEO_LIST:['Clip'],VIDEO_FILES:{Clip:'assets/videos/clip.mp4'},DS_IMPORT:{KIND:{}},location:{href:'https://www.admira.store/admira-xp/'},URL,dsEnsureSurfaceMedia:()=>{throw Error('Good pin used');}});vm.runInContext(helper+pin+hit,ctx);return ctx;}
test('Signage pin reaches the mapped Matrix ID and resolves the direct media URL',async()=>{const c=context();assert.equal(vm.runInContext("dsPinSurface('starbucks-wall-06','Clip')",c),true);await new Promise(r=>setImmediate(r));assert.equal(c.seen.length,1);assert.equal(c.seen[0].id,'starbucks-wall-06');assert.equal(c.seen[0].track.url,'https://www.admira.store/admira-xp/assets/videos/clip.mp4');assert.equal(c.seen[0].track.kind,'video');});
test('Matrix does not accept Good IDs or fall through to an overlapping Good rectangle',()=>{const c=context();assert.equal(vm.runInContext("dsPinSurface('ds1','Clip')",c),false);assert.equal(vm.runInContext('dsSurfaceAtClientPoint(100,200)',c),null);c.window.XpaceMatrixOptions=null;assert.equal(vm.runInContext('dsSurfaceAtClientPoint(100,200)',c),null);assert.equal(vm.runInContext('dsActiveSurfaces().length',c),0);});
const reset=html.slice(html.indexOf("      if(cmd==='reset'){"),html.indexOf("      if(cmd==='importtube'||cmd==='tube'){"));
function resetContext(arg=''){const store=new Map(),calls=[],ctx=vm.createContext({cmd:'reset',arg,lang:'en',dsMatrixAdapter:()=>({reset:async()=>calls.push('matrix-reset')}),dsMatrixOwnsScreens:()=>true,dsImportsDBList:async()=>[{id:'import-1'}],localStorage:{setItem:(k,v)=>store.set(k,v)},DS_RESET_IMPORTS_KEY:'excluded-imports',DS_SURFACES:[{id:'ds1'},{id:'ds2'}],dsUnpinSurface:id=>calls.push(id),VIDEO_LIST:['Changed','Imported','Basic'],DS_BASE_VIDEO_LIST:['Basic','Original'],dsVideoIdx:2,dsSelectedSurfaces:new Set(['ds1']),window:{XpaceOptionsPlayback:{resetScreens:()=>calls.push('stock-active-reset')},dispatchEvent:()=>{}},Event,dsSavePlaylistOrder:()=>calls.push('save-order'),renderSignagePanel:()=>{},switchDSVideo:()=>{throw Error('Good playback selected');}});vm.runInContext('async function runReset(){'+reset+'}',ctx);return {ctx,store,calls};}
test('/reset restores the original order, releases pins and resets Matrix without deleting receipts or imports',async()=>{const {ctx,calls,store}=resetContext();const message=await ctx.runReset();assert.deepEqual(Array.from(ctx.VIDEO_LIST),['Basic','Original']);assert.equal(ctx.dsVideoIdx,0);assert.equal(ctx.dsSelectedSurfaces.size,0);assert.equal(store.get('excluded-imports'),'["import-1"]');assert.deepEqual(calls,['ds1','ds2','stock-active-reset','save-order','matrix-reset']);assert.match(message,/Stock, history and shared MCP playlists retained/);});
test('/reset rejects arguments without altering the active playlist',async()=>{const {ctx,calls,store}=resetContext('all');assert.match(await ctx.runReset(),/without arguments/);assert.deepEqual(Array.from(ctx.VIDEO_LIST),['Changed','Imported','Basic']);assert.equal(calls.length,0);assert.equal(store.size,0);});
test('excluded imports remain in IndexedDB but do not return to the active list after reload',()=>{const code=html.slice(html.indexOf('function dsImportsRegister('),html.indexOf('function dsImportsListNames'));const seen=[],ctx=vm.createContext({localStorage:{getItem:()=>JSON.stringify(['archived'])},DS_RESET_IMPORTS_KEY:'key',URL:{createObjectURL:()=>{seen.push('blob');return 'blob:test';}},dsImportsUniqueName:n=>n,VIDEO_LIST:[],VIDEO_FILES:{},VIDEO_LED_MESSAGES:{},DS_IMPORT:{KIND:{},BLOB_URLS:{},IDS:{}}});vm.runInContext(code,ctx);assert.equal(ctx.dsImportsRegister({id:'archived',name:'Old'},true),null);assert.equal(ctx.VIDEO_LIST.length,0);assert.equal(seen.length,0);assert.equal(ctx.dsImportsRegister({id:'new',name:'New',blob:{},kind:'image'},false),'New');assert.equal(ctx.VIDEO_LIST.length,1);});
