import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
const source=readFileSync(new URL('../admira-xp/scripts/media-stock.js',import.meta.url),'utf8');
function runtime(fetchImpl,storage=new Map()){const root={crypto,AbortSignal,fetch:fetchImpl,URL,document:{documentElement:{lang:'es'},querySelectorAll:()=>[],getElementById:()=>null},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},setTimeout:fn=>setTimeout(fn,0),clearTimeout};vm.runInNewContext(source,{window:root,URL,Date,JSON,Error});return {api:root.XpaceMedia,storage};}
const stock={id:'fixture-stock',num:1,url:'https://api.admira.store/stock/asset/fixture-stock'};
test('one paid video POST, all further progress reads recover the same ID and return Stock',async()=>{const calls=[];const {api}=runtime(async(url,opts)=>{calls.push([url,opts]);return Response.json({ok:true,job:{status:calls.length===1?'pending':'done',stock}});});const result=await api.generate('video',{text:'Coffee',language:'en'});assert.equal(result.stock.id,stock.id);assert.equal(calls.filter(x=>x[1].method==='POST').length,1);assert.equal(calls[1][0],'/admira-xp/media-job?requestId='+JSON.parse(calls[0][1].body).requestId);assert.equal(api.pending('video'),null);});
test('network failure retains the operation and page reload recovers via GET without payment',async()=>{const storage=new Map(),payload={text:'Coffee',language:'en'};const first=runtime(async()=>{throw Error('network');},storage);await assert.rejects(first.api.generate('image',payload));const saved=first.api.pending('image');assert.ok(saved.requestId);const calls=[];const second=runtime(async(url,opts)=>{calls.push([url,opts]);return Response.json({ok:true,job:{status:'done',stock}});},storage);await second.api.generate('image',payload);assert.equal(calls.length,1);assert.equal(calls[0][1].method,undefined);assert.ok(calls[0][0].endsWith(saved.requestId));});
test('authentication failure clears unaccepted work and does not poll or generate again',async()=>{let calls=0;const {api}=runtime(async()=>{calls++;return Response.json({error:'login_required'},{status:401});});await assert.rejects(api.generate('video',{text:'Coffee',language:'en'}),e=>e.code==='auth');assert.equal(calls,1);assert.equal(api.pending('video'),null);});
test('provider failure and foreign Stock URLs never report a saved asset',async()=>{for(const job of [{status:'failed',error:'provider_failed'},{status:'done',stock:{id:'fixture',url:'https://other.example/stock/asset/fixture'}}]){const {api}=runtime(async()=>Response.json({ok:true,job}));await assert.rejects(api.generate('image',{text:'Coffee',language:'en'}));}});

test('long provider requests carry their own timeout instead of the existing 20-second page guard',async()=>{const {api}=runtime(async(url,options)=>{assert.ok(options.signal instanceof AbortSignal);return Response.json({ok:true,job:{status:'done',stock}});});await api.generate('image',{text:'Coffee',language:'en'});});
