import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../admira-xp/scripts/media-experience.js',import.meta.url),'utf8');
class Node{
 constructor(tag,doc){this.tagName=tag.toUpperCase();this.doc=doc;this.children=[];this.dataset={};this.attrs={};this.style={};this.events={};this.parentNode=null;this.paused=true;this.classList={toggle:(k,on)=>{const classes=new Set(this.className?.split(' ')||[]);on?classes.add(k):classes.delete(k);this.className=[...classes].join(' ');}};}
 append(...nodes){for(const n of nodes){n.parentNode=this;this.children.push(n);}}after(n){const p=this.parentNode;n.parentNode=p;p.children.splice(p.children.indexOf(this)+1,0,n);}replaceChildren(...nodes){this.children=[];this.append(...nodes);}setAttribute(k,v){this.attrs[k]=String(v);}removeAttribute(k){delete this.attrs[k];if(k==='src')this.src='';}getAttribute(k){return this.attrs[k]??null;}
 get isConnected(){return !!this.parentNode;}addEventListener(k,fn){(this.events[k]??=[]).push(fn);}fire(k,e={}){for(const fn of this.events[k]||[])fn({target:this,preventDefault(){},stopPropagation(){},...e});}focus(){this.doc.activeElement=this;}showModal(){this.open=true;}close(){this.open=false;this.fire('close');}pause(){this.paused=true;this.fire('pause');}load(){this.loaded=true;}
 matches(sel){return sel.split(',').some(s=>{const parts=s.trim().split(' '),last=parts.pop();let hit=last.startsWith('.')?(this.className||'').split(' ').includes(last.slice(1)):last.startsWith('#')?this.id===last.slice(1):last.startsWith('[')?Object.hasOwn(this.dataset,last.slice(6,-1).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())):this.tagName===last.toUpperCase();if(!hit)return false;let p=this.parentNode;for(const part of parts.reverse()){while(p&&!p.matches(part))p=p.parentNode;if(!p)return false;p=p.parentNode;}return true;});}
 closest(sel){let n=this;while(n){if(n.matches(sel))return n;n=n.parentNode;}return null;}querySelectorAll(sel){const out=[];for(const n of this.children){if(n.matches(sel))out.push(n);out.push(...n.querySelectorAll(sel));}return out;}querySelector(sel){return this.querySelectorAll(sel)[0]||null;}
}
function setup(){const doc={documentElement:{lang:'es'},readyState:'complete',activeElement:null,events:{},createElement:tag=>new Node(tag,doc),addEventListener(k,f){(this.events[k]??=[]).push(f);},querySelector:sel=>doc.body.querySelector(sel),querySelectorAll:sel=>doc.body.querySelectorAll(sel)};doc.body=new Node('body',doc);const statuses=['voiceoverStatus','announcementStatus','imagePromptStatus','videoPromptStatus'].map(id=>{const n=new Node('p',doc);n.id=id;doc.body.append(n);return n;});const link=new Node('a',doc);link.dataset.pixeriaMusicCreate='';doc.body.append(link);const events={},root={document:doc,addEventListener(k,f){(events[k]??=[]).push(f);}};vm.runInNewContext(source,{window:root,URL});return {root,doc,statuses,link,api:root.XpaceMediaExperience,event(k,e){for(const f of doc.events[k]||[])f(e);},created(kind){for(const f of events['xpace:media-created']||[])f({detail:{kind}});}};}
const receipt=kind=>({kind,id:'fixture-'+kind,url:'https://api.admira.store/stock/asset/fixture-'+kind,title:'Stock '+kind});
test('four creators show real stages, keep waits active and finish only on confirmation',()=>{const h=setup();for(const kind of ['music','voice','image','video']){h.api.progress(kind,'preparing');h.api.progress(kind,'pending');let state=h.api.state(kind);assert.equal(state.step,1);assert.equal(state.busy,true);h.api.progress(kind,'archiving');assert.equal(h.api.state(kind).step,2);h.api.progress(kind,'pending');assert.equal(h.api.state(kind).step,2,'later status must not move confirmed stages backward');h.api.progress(kind,'loading');h.api.progress(kind,'done');assert.equal(h.api.state(kind).step,4);assert.equal(h.api.state(kind).busy,false);}assert.equal(h.doc.body.querySelectorAll('.media-creation-progress').length,5,'voice feedback visible in both creation surfaces');const bar=h.doc.body.querySelector('.mcp-track');assert.equal(bar.getAttribute('aria-valuemax'),'4');assert.equal(bar.getAttribute('aria-valuetext'),'Listo · revisa el previo');});
test('music link truthfully waits for a Stock delivery and does not pretend to know provider progress',()=>{const h=setup();h.event('click',{target:h.link});assert.equal(h.api.state('music').phase,'external');assert.match(h.doc.body.querySelector('.mcp-stage').textContent,/Pixeria.*esperando/);h.created('music');assert.equal(h.api.state('music').phase,'done');});
test('failure stops animation without falsely finishing; explicit retry resets stages and language labels',()=>{const h=setup();h.api.progress('video','preparing');h.api.progress('video','archiving');h.api.progress('video','error');assert.equal(h.api.state('video').step,2);assert.equal(h.api.state('video').busy,false);h.api.progress('video','preparing');assert.equal(h.api.state('video').step,0);h.doc.documentElement.lang='en';h.api.progress('video','pending');assert.match(h.doc.body.querySelector('.mcp-stage').textContent,/Generating media/);});
test('every kind opens a centered native modal, with no autoplay or device mutation, and Close releases media',()=>{const h=setup();const trigger=new Node('div',h.doc);h.doc.body.append(trigger);for(const kind of ['image','video','voice','music']){assert.equal(h.api.open(receipt(kind),trigger),true);const modal=h.doc.querySelector('#mediaLargePreview');assert.equal(modal.open,true);assert.equal(modal.dataset.kind,kind);const media=modal.querySelector('video,audio,img');assert.equal(media.src,receipt(kind).url);assert.equal(media.autoplay,undefined);if(kind==='video')assert.equal(media.controls,true);modal.querySelector('.media-large-close').fire('click');assert.equal(modal.open,false);assert.equal(h.doc.activeElement,trigger);if(kind!=='image'){assert.equal(media.src,'');assert.equal(media.paused,true);}}});
test('music duck starts only on user playback and is released on pause, Escape or close',()=>{const h=setup();let active=0,stops=0;h.root.XpaceMatrixOptions={suppressMusic(){active++;return ()=>active--;}};h.root.XpaceAnnouncements={stopStock(){stops++;}};h.api.open(receipt('voice'));const modal=h.doc.querySelector('#mediaLargePreview'),audio=modal.querySelector('audio');assert.equal(active,0);audio.fire('play');assert.equal(active,1);assert.equal(stops,1);audio.fire('pause');assert.equal(active,0);audio.fire('play');modal.fire('cancel');assert.equal(active,0);assert.equal(modal.open,false);});
test('double click and Enter open the exact bound receipt; foreign URLs and action buttons do not open',()=>{const h=setup();const node=new Node('div',h.doc);h.doc.body.append(node);h.api.bind(node,receipt('image'));let prevented=0;const event={target:node,preventDefault(){prevented++;},stopPropagation(){}};h.event('dblclick',event);assert.equal(h.doc.querySelector('#mediaLargePreview').dataset.kind,'image');h.api.close();h.event('keydown',{...event,key:'Enter'});assert.equal(prevented,2);h.api.close();const button=new Node('button',h.doc);node.append(button);h.event('dblclick',{...event,target:button});assert.equal(h.doc.querySelector('#mediaLargePreview').open,false);assert.equal(h.api.open({...receipt('image'),url:'https://evil.example/asset'}),false);});
