import {createStarbucksMusic} from '../admira-xp/scripts/starbucks-music.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const html=readFileSync(new URL('../admira-xp/index.html',import.meta.url),'utf8');
const bridge=html.slice(html.indexOf('(function(){\n const KEY=\'xpaceos.options-playlist-stock'),html.indexOf('function nextDSVideo(){'));
function setup(storage=new Map()){const calls=[],video=['Original','Second'],songs=['Music'],files={Original:'https://assets.example/original.mp4',Second:'https://assets.example/second.mp4'},music={Music:'https://assets.example/music.mp3'};const win={dispatchEvent(){}};const env={window:win,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},location:{href:'https://www.admira.store/admira-xp/'},URL,Event,lang:'es',VIDEO_LIST:video,VIDEO_FILES:files,SONG_LIST:songs,SONG_FILES:music,DS_IMPORT:{KIND:{},DURATION_BY_NAME:{}},dsImageEl:{complete:true,naturalWidth:1},dsVideoIdx:0,videoPlaying:true,videoPaused:false,currentDSVideoName:()=>video[env.dsVideoIdx],switchDSVideo:i=>{calls.push(['screen',i]);env.dsVideoIdx=i;},bgMusic:{paused:false,src:music.Music,currentSrc:music.Music,load(){calls.push(['load']);},play(){calls.push(['music']);return Promise.resolve();}},G:{nowPlaying:'Music'},shopTimeSettings:{}};vm.runInNewContext(bridge,env);return {api:win.XpaceOptionsPlayback,env,calls,storage};}
const image={id:'image-fixture',url:'https://api.admira.store/stock/asset/image-fixture',kind:'image',title:'Coffee'};
test('manual music launch retains the existing DJ control rule',async()=>{const h=setup();h.env.G.staff=[{hired:true,role:4}];const id=await h.api.insert('music',{...image,kind:'music'});await assert.rejects(h.api.play('music',id),/DJ controla/);assert.deepEqual(h.calls,[]);assert.equal(h.env.bgMusic.src,'https://assets.example/music.mp3');});
test('adding an image before the active screen content preserves its source/index and never plays it',async()=>{const h=setup();const id=await h.api.insert('screens',image,'Original');assert.deepEqual(h.calls,[]);assert.equal(h.api.state('screens').tracks.find(t=>t.active).id,'Original');assert.equal(h.api.state('screens').tracks[0].id,id);assert.equal(h.env.DS_IMPORT.KIND[id],'image');await h.api.play('screens',id);assert.deepEqual(h.calls,[['screen',0]]);});
test('only an explicit music launch replaces audio; duplicates and ordering retain one Stock identity',async()=>{const h=setup(),track={...image,kind:'music'};const id=await h.api.insert('music',track);await h.api.insert('music',track);assert.equal(h.env.SONG_LIST.filter(n=>h.env.SONG_FILES[n]===track.url).length,1);assert.equal(h.env.bgMusic.src,'https://assets.example/music.mp3');assert.deepEqual(h.calls,[]);await h.api.play('music',id);assert.equal(h.env.bgMusic.src,track.url);assert.deepEqual(h.calls,[['load'],['music']]);});
test('reload restores Stock references and playlist order without sending or autoplaying',async()=>{const h=setup();await h.api.insert('screens',image);const second=setup(h.storage);assert.deepEqual(second.calls,[]);assert.ok(second.api.state('screens').tracks.some(t=>t.url===image.url));assert.equal(second.env.bgMusic.src,'https://assets.example/music.mp3');});
test('wrong media type and invalid source cannot modify a playlist',async()=>{const h=setup();await assert.rejects(h.api.insert('music',image));await assert.rejects(h.api.insert('screens',{...image,url:'https://other.example/asset'}));assert.equal(h.env.VIDEO_LIST.length,2);assert.equal(h.env.SONG_LIST.length,1);});
test('image generation saves and stages the result without changing the counter or screen playlist',async()=>{const source=html.slice(html.indexOf('  async function admiraCreaImagen(desc)'),html.indexOf('  window.admiraCreaImagen=admiraCreaImagen;'));const current={desc:'Already playing'},calls=[],win={ADMIRA_CREA:current,XpaceMedia:{pending:()=>null,generate:async()=>({stock:image}),link:()=>{}},XpaceMediaOptions:{stage:(kind,stock)=>calls.push([kind,stock])}};class ImageStub{set src(value){this.value=value;this.onload();}}
 const env={window:win,lang:'es',Image:ImageStub};vm.runInNewContext(source,env);assert.match(await env.admiraCreaImagen('Coffee'),/pulsa Lanzar/);assert.equal(win.ADMIRA_CREA,current);assert.equal(calls.length,1);assert.equal(calls[0][0],'image');assert.equal(win.ADMIRA_CREA_LAST.until,0);
});
test('new music delivery stages Stock media and never invokes the audio transport',async()=>{const source=readFileSync(new URL('../admira-xp/scripts/hilomusical.js',import.meta.url),'utf8');const staged=[],audio={play(){throw Error('Unexpected playback');}},win={XpaceMediaOptions:{stage:(kind,value)=>staged.push([kind,value]),get:()=>null}};let n=0;const fixture={...image,kind:'music',ts:2};const env={window:win,document:{getElementById:()=>audio},location:{search:''},URLSearchParams,fetch:async()=>({json:async()=>n++===0?{now:1,playlist:[]}:{now:2,playlist:[fixture],pending:[fixture]}}),setInterval(){},setTimeout(){}};vm.runInNewContext(source,env);await new Promise(r=>setImmediate(r));win.HILOMUSICAL.poll();await new Promise(r=>setImmediate(r));assert.equal(staged.length,1);assert.equal(staged[0][0],'music');assert.equal(staged[0][1].id,fixture.id);});

test('automatic XPL selection excludes generated drafts from both cached and fetched Stock pools',async()=>{const source=readFileSync(new URL('../admira-xp/scripts/xpl-stock.js',import.meta.url),'utf8'),draft={id:'draft',url:image.url,type:'image',tags:['admira-xp'],title:'Coffee'},live={id:'live',url:'https://stock.example/live.jpg',type:'image',title:'Approved'};
 for(const cached of [true,false]){const root={},store=cached?JSON.stringify({ts:Date.now(),items:[draft,live]}):null;vm.runInNewContext(source,{window:root,localStorage:{getItem:()=>store,setItem(){}},fetch:async()=>({ok:true,json:async()=>({items:[draft,live]})}),Date,Math,Promise});await root.XPLStock.ensure();assert.equal(root.XPLStock.count(),1);assert.equal(root.XPLStock.pick({}).id,'live');}
});

test('blocked Matrix music launch reports failure rather than a successful send',async()=>{
 class Audio extends EventTarget{volume=1;paused=true;currentTime=0;load(){}removeAttribute(){}pause(){this.paused=true;}play(){return Promise.reject(Error('blocked'));}}
 const music=createStarbucksMusic({audio:new Audio(),publishedTracks:[{url:image.url,title:'Music'}]}),source=readFileSync(new URL('../admira-xp/scripts/matrix-panorama.mjs',import.meta.url),'utf8'),start=source.indexOf('window.XpaceMatrixOptions={'),end=source.indexOf('\n\n const announcementAnchor',start),root={};
 try{vm.runInNewContext(source.slice(start,end),{window:root,music,optionGroups:()=>[],t:(es,en)=>es});await assert.rejects(root.XpaceMatrixOptions.play('music',image.url),/No se pudo reproducir el audio/);assert.equal(music.state().playing,false);}finally{music.dispose();}
});
