import test from 'node:test';
import assert from 'node:assert/strict';
import {createPOSDemo,interpolateView,POS_DEMO_STEPS} from '../admira-xp/scripts/pos-demo.mjs';
import {createPOSDemoSound} from '../admira-xp/scripts/pos-demo-sound.mjs';
import {parseVisualCommand,executeVisualCommand} from '../admira-xp/scripts/xtanco-visual-command.mjs';
function harness({play=async()=>{}}={}){const calls=[],before={yaw:170,pitch:-20,fov:65},view={...before};let available=true,tick=null;const demo=createPOSDemo({camera:{get:()=>({...view}),set:v=>Object.assign(view,v)},checkout:{yaw:36.2,pitch:-18,fov:65},isAvailable:()=>available,presentation:{begin:()=>calls.push('begin'),show:v=>calls.push(v.phase),clear:()=>calls.push('clear')},drop:()=>{calls.push('basket');return true;},sound:{prepare:()=>calls.push('prime'),play:()=>{calls.push('song');return play();},stop:()=>calls.push('stop')},requestFrame:f=>{tick=f;return 1;},cancelFrame:()=>tick=null,now:()=>0});return {demo,calls,before,view,advance:t=>tick?.(t),disable:()=>available=false};}
test('the guided sequence focuses, outlines, picks, carries and commits once before the song',async()=>{const h=harness();assert.equal(h.demo.start().ok,true);assert.equal(h.demo.start().error,'busy');for(const t of [0,1500,2800,4000,5900])h.advance(t);assert.deepEqual(h.calls.filter(x=>['focus','outline','pick','travel','drop'].includes(x)),['focus','outline','pick','travel','drop']);assert.equal(h.calls.includes('basket'),false);assert.equal(h.calls.includes('song'),false);h.advance(POS_DEMO_STEPS.drop);await new Promise(setImmediate);assert.equal(h.demo.state().phase,'completed');assert.equal(h.calls.filter(x=>x==='basket').length,1);assert.ok(h.calls.indexOf('basket')<h.calls.indexOf('song'));assert.equal(h.view.yaw,36.2);});
test('Escape/off, unavailable POS and disposal cancel before checkout without basket or audible song',()=>{for(const action of ['stop','disabled','dispose']){const h=harness();h.demo.start();h.advance(4000);if(action==='stop')h.demo.stop();else if(action==='disabled'){h.disable();h.advance(4100);}else h.demo.dispose();h.advance(8000);assert.equal(h.calls.includes('basket'),false);assert.equal(h.calls.includes('song'),false);if(action!=='dispose')assert.deepEqual(h.view,h.before);}});
test('an old pending song cannot mark a cancelled or newer demo as completed',async()=>{let resolve;const h=harness({play:()=>new Promise(r=>resolve=r)});h.demo.start();h.advance(6400);h.demo.stop();h.demo.start();resolve();await new Promise(setImmediate);assert.equal(h.demo.state().running,true);assert.equal(h.demo.state().song,false);h.demo.stop();});
test('camera takes the shortest yaw route and music failure reports the accepted basket',async()=>{assert.equal(interpolateView({yaw:170,pitch:0,fov:65},{yaw:-170,pitch:0,fov:65},.5).yaw,180);const h=harness({play:async()=>{throw Error('blocked');}});h.demo.start();h.advance(6400);await new Promise(setImmediate);assert.equal(h.demo.state().error,'audio');assert.equal(h.calls.filter(x=>x==='basket').length,1);});
test('demo parsing stays local, help and stop do not open a view, and a bad router cannot start a demo',async()=>{for(const [input,expected] of [['/demo','help'],['/DEMO TPV','tpv'],['/demo@bot tpv','tpv'],['/demo off','stop'],['/demo tpv off','stop'],['/demo status','status'],['/demo nonsense','invalid']])assert.deepEqual(parseVisualCommand(input),{guided:expected});let started=0,stopped=0;globalThis.XpacePOSExperience={demo:{start:()=>{started++;return {ok:true};},stop:()=>stopped++,state:()=>({phase:'idle'})}};try{assert.equal((await executeVisualCommand('/demo')).ok,true);await executeVisualCommand('/demo off');assert.equal(stopped,1);const router={mode:'matrix',choose:async()=>({ok:true})};assert.equal((await executeVisualCommand('/demo tpv',{router})).ok,true);assert.equal(started,1);assert.equal((await executeVisualCommand('/demo tpv',{router:{...router,mode:'good'}})).ok,false);assert.equal(started,1);}finally{delete globalThis.XpacePOSExperience;}});
test('audible demo playback temporarily suppresses existing music and cancellation never resurrects a primed song',async()=>{const events={},calls=[],audio={muted:true,volume:.35,currentTime:0,addEventListener:(k,f)=>events[k]=f,removeEventListener(){},load(){},removeAttribute(){},pause:()=>calls.push('pause'),play:async()=>calls.push(['play',audio.muted])},music={suppress:()=>{calls.push('duck');return ()=>calls.push('restore');}},sound=createPOSDemoSound({audio,music});sound.prepare();await sound.play();assert.ok(calls.some(v=>Array.isArray(v)&&v[1]===false));assert.equal(audio.muted,false);events.ended();assert.equal(calls.filter(x=>x==='restore').length,1);sound.stop();assert.equal(audio.muted,true);sound.dispose();});
