import test from 'node:test';
import assert from 'node:assert/strict';
import {createRetailRulebook,createRetailRulePlayer,defaultRetailRule,RETAIL_RULES_KEY,RETAIL_REACTIONS,filterRetailMedia,mediaAsset} from '../admira-xp/scripts/retail-rules.mjs';
import {createRetailMediaDisplay} from '../admira-xp/scripts/retail-media-display.mjs';
import {onRequest} from '../functions/admira-xp/media-catalog.js';
const items=RETAIL_REACTIONS.map(r=>({id:r.kind,type:r.kind,title:r.kind,url:'https://api.admira.store/stock/asset/'+r.kind,tags:['starbucks','café']}));
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)};};
function fakeAudio(){return {muted:true,src:'',currentTime:0,plays:0,addEventListener(){},removeEventListener(){},removeAttribute(){},load(){},pause(){},async play(){if(!this.muted)this.plays++;}};}
test('every reaction resolves only its compatible Stock item, and media rules persist with editable filters',async()=>{const storage=memory(),book=createRetailRulebook({storage,fetcher:async()=>Response.json({items})});await book.refresh();for(const reaction of RETAIL_REACTIONS){const r=defaultRetailRule();r.do=[{id:reaction.action,filter:'#starbucks',value:reaction.kind}];book.save([r]);assert.equal(book.select('muffinPicked').kind,reaction.kind);const restored=createRetailRulebook({storage});assert.equal(restored.select('muffinPicked').id,reaction.kind);r.do[0].value=reaction.kind==='music'?'image':'music';book.save([r]);assert.equal(book.select('muffinPicked'),null);}book.save([{...defaultRetailRule(),do:[{id:'showImage',value:'',filter:'#imagen'}]}]);assert.equal(book.select('muffinPicked'),null);});
test('old song rules migrate without losing event, chosen song, disabled state or ID',()=>{const storage=memory(),r=defaultRetailRule();r.enabled=false;r.id='old-id';r.do=[{id:'playSong',value:'music'}];storage.setItem(RETAIL_RULES_KEY,JSON.stringify({version:1,rules:[r],songs:[items[0]]}));const book=createRetailRulebook({storage});assert.deepEqual(book.state().rules,[r]);assert.equal(book.state().media.find(a=>a.id==='music').kind,'music');book.save(book.state().rules);assert.equal(JSON.parse(storage.getItem(RETAIL_RULES_KEY)).version,2);});
test('preset type hashtags work even without tags; custom accents/tags/search remain editable and type-safe',()=>{const media=items.map(mediaAsset);for(const reaction of RETAIL_REACTIONS)assert.equal(filterRetailMedia(media,reaction.kind,reaction.filter).length,1);assert.equal(filterRetailMedia(media,'image','#starbucks').length,1);assert.equal(filterRetailMedia(media,'image','#CAFÉ').length,1);assert.equal(filterRetailMedia(media,'image','#video').length,0);assert.equal(filterRetailMedia(media,'video','vi').length,1);assert.equal(filterRetailMedia(media,'image','#missing').length,0);assert.equal(mediaAsset({...items[0],type:'audio'}).kind,'music');});
test('audio/voice and visual reactions take distinct playback paths; cancellation cannot claim late success',async()=>{const book=createRetailRulebook({storage:memory(),fetcher:async()=>Response.json({items})});await book.refresh();const audio=fakeAudio(),calls=[],visual={prepare:a=>calls.push(['prepare',a.kind]),play:async()=>calls.push(['play']),stop:()=>calls.push(['stop']),subscribe:()=>()=>{},dispose(){}};const p=createRetailRulePlayer({book,audio,music:{suppress:()=>()=>{}},visual});for(const r of RETAIL_REACTIONS){book.save([{...defaultRetailRule(),do:[{id:r.action,value:r.kind}]}]);p.prepare();await p.fire('muffinPicked');assert.equal(p.state().kind,r.kind);assert.equal(p.state().playing,true);p.stop();assert.equal(p.state().playing,false);}assert.equal(audio.plays,2);assert.equal(calls.filter(x=>x[0]==='play').length,2);let done;visual.play=()=>new Promise(r=>done=r);p.prepare();const late=p.fire('muffinPicked');p.stop();done();await late;assert.equal(p.state().playing,false);p.dispose();});
test('public media route fixes every upstream type, strips private fields and never forwards credentials',async()=>{const calls=[];const response=await onRequest({request:new Request('https://www.admira.store/admira-xp/media-catalog?url=https://other.example',{headers:{Cookie:'private',Authorization:'private'}})},async(url,opts)=>{const type=new URL(url).searchParams.get('type');calls.push(type);assert.equal(opts.headers.Cookie,undefined);assert.equal(opts.headers.Authorization,undefined);assert.equal(new URL(url).hostname,'api.admira.store');return Response.json({items:[{...(items.find(i=>i.type===type)||items[0]),type,prompt:'private',oculto:false},{...items[0],type,url:'https://other.example/file'}]});});assert.equal(response.status,200);assert.deepEqual(calls.sort(),['audio','image','locucion','music','video']);for(const item of (await response.json()).items)assert.deepEqual(Object.keys(item).sort(),['id','tags','title','type','url']);let fetched=false;for(const [url,method,status] of [['?type=link','GET',400],['','POST',405]]){const r=await onRequest({request:new Request('https://www.admira.store/admira-xp/media-catalog'+url,{method})},()=>{fetched=true;});assert.equal(r.status,status);}assert.equal(fetched,false);});
function displayFixture(){let attached=[],ducks=0,releases=0;const nodes=[];const document={createElement(tag){const ev=new Map(),node={tagName:tag.toUpperCase(),dataset:{},style:{},complete:true,naturalWidth:12,muted:true,removed:false,plays:0,addEventListener(e,f){ev.set(e,[...(ev.get(e)||[]),f]);},removeEventListener(e,f){ev.set(e,(ev.get(e)||[]).filter(v=>v!==f));},emit:e=>(ev.get(e)||[]).forEach(f=>f()),remove(){this.removed=true;attached=attached.filter(n=>n!==this);},removeAttribute(){},load(){},pause(){},async play(){this.plays++;}};nodes.push(node);return node;}};const display=createRetailMediaDisplay({host:()=>({append:n=>attached.push(n)}),document,music:{suppress(){ducks++;return ()=>releases++;}}});return {display,nodes,attached:()=>attached,counts:()=>({ducks,releases})};}
test('temporary image stays until stopped; video unmutes on reaction and restores the underlying display at end',async()=>{const h=displayFixture();h.display.prepare({...items[2],kind:'image'});assert.equal(h.attached().length,0);await h.display.play();assert.equal(h.attached().length,1);assert.deepEqual(h.counts(),{ducks:0,releases:0});h.display.stop();assert.equal(h.attached().length,0);h.display.prepare({...items[3],kind:'video'});await h.display.play();assert.equal(h.nodes.at(-1).muted,false);assert.deepEqual(h.counts(),{ducks:1,releases:0});h.nodes.at(-1).emit('ended');assert.equal(h.attached().length,0);assert.deepEqual(h.counts(),{ducks:1,releases:1});h.display.dispose();});
