import test from 'node:test';
import assert from 'node:assert/strict';
import {createRetailRulebook,createRetailRulePlayer,defaultRetailRule,RETAIL_RULES_KEY,songAsset} from '../admira-xp/scripts/retail-rules.mjs';
import {createPOSDemo} from '../admira-xp/scripts/pos-demo.mjs';
import {parseVisualCommand,executeVisualCommand} from '../admira-xp/scripts/xtanco-visual-command.mjs';
function store(){const data=new Map();return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),data};}
const second={id:'another',type:'music',title:'Other Pixeria song',url:'https://api.admira.store/stock/asset/another'};
function book(storage=store()){return createRetailRulebook({storage,fetcher:async()=>({ok:true,json:async()=>({items:[second,{...second,id:'picture',type:'image'}]})})});}
test('XPL conditions select the edited Pixeria song at the selected event, persist and keep empty/disabled rules silent',async()=>{const s=store(),b=book(s);await b.refresh();const r=defaultRetailRule();r.when.conds[0].fact='muffinDelivered';r.do[0].value='another';b.save([r]);assert.equal(b.select('muffinPicked'),null);assert.equal(b.select('muffinDelivered').title,second.title);const restored=book(s);assert.equal(restored.select('muffinDelivered').url,second.url);assert.equal(restored.state().songs.some(x=>x.id==='picture'),false);b.save([{...r,enabled:false}]);assert.equal(b.select('muffinDelivered'),null);b.save([]);assert.equal(book(s).select('muffinPicked'),null);assert.ok(s.data.has(RETAIL_RULES_KEY));});
test('unknown actions, malformed conditions and untrusted songs cannot execute',()=>{const b=book();assert.throws(()=>b.save([{...defaultRetailRule(),do:[{id:'command',value:'/anything'}]}]));assert.throws(()=>b.save([{...defaultRetailRule(),when:{conds:[]}}]));assert.equal(songAsset({...second,url:'javascript:alert(1)'}),null);assert.equal(songAsset({...second,url:'https://example.com/song.mp3'}),null);assert.equal(b.select('coffeePicked'),null);});
test('higher priority wins, last matching rule wins ties, failed persistence preserves prior rule',()=>{const s=store(),b=book(s),r=defaultRetailRule();b.save([{...r,id:'first',priority:5},{...r,id:'last',priority:1,do:[{id:'playSong',value:'missing'}]}]);assert.ok(b.select('muffinPicked'));s.setItem=()=>{throw Error('quota');};assert.throws(()=>b.save([]));assert.equal(b.state().rules.length,2);});
function player(b){let plays=0,ducks=0,releases=0;const audio={muted:true,src:'',currentTime:0,addEventListener(){},removeEventListener(){},removeAttribute(){},load(){},pause(){},async play(){if(!this.muted)plays++;}};const p=createRetailRulePlayer({book:b,audio,music:{suppress(){ducks++;return ()=>releases++;}}});return {p,audio,count:()=>({plays,ducks,releases})};}
test('pickup fires once per gesture, does not fire again at delivery, and stop restores background music',async()=>{const h=player(book());h.p.prepare();await h.p.fire('muffinPicked');await h.p.fire('muffinPicked');await h.p.fire('muffinDelivered');assert.deepEqual(h.count(),{plays:1,ducks:1,releases:0});h.p.stop();assert.equal(h.audio.muted,true);assert.equal(h.count().releases,1);h.p.prepare();await h.p.fire('muffinPicked');assert.equal(h.count().plays,2);h.p.dispose();});
test('delivery rules remain silent at pickup, and a disabled rule cannot fall back to the old demo song',async()=>{const b=book(),r=defaultRetailRule();r.when.conds[0].fact='muffinDelivered';b.save([r]);const h=player(b);h.p.prepare();await h.p.fire('muffinPicked');assert.equal(h.count().plays,0);await h.p.fire('muffinDelivered');assert.equal(h.count().plays,1);b.save([]);h.p.prepare();await h.p.fire('muffinDelivered');assert.equal(h.p.state().playing,false);assert.equal(h.count().plays,1);});
test('demo emits one pickup before checkout even when a background frame skips the pick animation',async()=>{let tick,picks=0,drops=0;const d=createPOSDemo({camera:{get:()=>({yaw:0,pitch:0,fov:65}),set(){}},checkout:{yaw:36,pitch:0,fov:65},isAvailable:()=>true,presentation:{begin(){},show(){},clear(){}},drop:()=>{drops++;return true;},sound:{prepare(){},stop(){},play:async()=>{},isPlaying:()=>false},onPick:()=>picks++,requestFrame:f=>(tick=f,1),cancelFrame(){},now:()=>0});d.start();tick(4000);tick(6000);tick(6500);await new Promise(setImmediate);assert.equal(picks,1);assert.equal(drops,1);assert.equal(d.state().song,false);});
test('ifthendothat stays local including invalid input and on/off command',async()=>{for(const [arg,result]of [['','on'],[' on','on'],[' off','off'],[' nonsense','invalid']])assert.equal(parseVisualCommand('/ifthendothat'+arg).conditional,result);let opened=0,closed=0;globalThis.XPLComposer={open:()=>opened++,close:()=>closed++};try{assert.equal((await executeVisualCommand('/ifthendothat')).local,true);await executeVisualCommand('/ifthendothat off');assert.equal(opened,1);assert.equal(closed,1);assert.equal((await executeVisualCommand('/ifthendothat bad')).ok,false);}finally{delete globalThis.XPLComposer;}});
