import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../admira-xp/scripts/voice-receipts.js',import.meta.url),'utf8');
const storage=()=>{const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};};
function runtime(local=storage(),loc='alsea-sbux-021',fetch=async()=>Response.json({items:[]}),host='admira.store'){const events={};const root={document:{},location:{href:'https://'+host+'/?loc='+loc},localStorage:local,AbortSignal,fetch,addEventListener:(k,f)=>events[k]=f};vm.runInNewContext(source,{window:root,URL,Date,JSON,Number,encodeURIComponent});return{api:root.XpaceVoiceReceipts,events,local};}
const receipt=(voice,language,id,at)=>({id,url:'https://api.admira.store/stock/asset/'+id,voice,language,title:'Aviso '+id,at});
test('latest per four voice/language combinations survives reload and is isolated per Xpace',async()=>{const r=runtime();for(const lang of ['es','en'])for(const voice of ['female','male'])r.api.remember(receipt(voice,lang,lang+'-'+voice,10));r.api.remember(receipt('female','es','latest-es-female',20));r.api.remember(receipt('female','es','older-es-female',5));const b=runtime(r.local);assert.equal((await b.api.latest('female','es')).id,'latest-es-female');assert.equal((await b.api.latest('male','en')).id,'en-male');assert.equal(runtime(r.local,'other').api.get('female','es'),null);assert.equal(b.api.get('female','es').voiceId,'KHCvMklQZZo0O30ERnVn');});
test('fallback reuses only published XpaceOS ElevenLabs receipts with exact voice/language metadata',async()=>{let calls=0;const items=[{id:'female-en',type:'locucion',motor:'elevenlabs-v4',comment:'Creado desde XpaceOS / Created in XpaceOS · female · en',tags:['xpaceos','en'],createdAt:'2026-10-06T10:00:00Z'},{id:'wrong-demo',type:'locucion',motor:'elevenlabs-v4',comment:'Demo · female · es',tags:['demo-365']},{id:'generic',type:'audio',tags:['xpaceos']}];const r=runtime(undefined,undefined,async(url,opts)=>{calls++;assert.equal(url,'/admira-xp/voice-receipts');assert.equal(opts.credentials,'same-origin');assert.equal(opts.method,undefined);return Response.json({items:items.filter(x=>x.id==='female-en').map(x=>({...x,voice:'female',language:'en',url:'https://api.admira.store/stock/asset/'+x.id,at:Date.parse(x.createdAt)}))});});assert.equal((await r.api.latest('female','en')).id,'female-en');assert.equal(await r.api.latest('male','es'),null);assert.equal(r.api.get('female','es'),null);assert.equal(calls,1);assert.equal(r.api.remember({...receipt('female','es','bad',1),voiceId:'wrong'}),null);assert.equal(r.api.remember({...receipt('female','es','bad',1),url:'https://foreign.example/audio'}),null);});
test('completion events preserve a voice even after previews history is replaced by other media',()=>{const r=runtime();r.events['xpace:media-created']({detail:{kind:'voice',track:receipt('male','es','speech',10)}});for(let i=0;i<12;i++)r.events['xpace:media-created']({detail:{kind:'image',track:{id:'image-'+i}}});assert.equal(runtime(r.local).api.get('male','es').id,'speech');});

test('static XpaceOS source recovers from the canonical server without credentials',async()=>{const r=runtime(undefined,undefined,async(url,opts)=>{assert.equal(url,'https://www.admira.store/admira-xp/voice-receipts');assert.equal(opts.credentials,'omit');return Response.json({items:[receipt('male','en','saved',10)]});},'www.xpaceos.com');assert.equal((await r.api.latest('male','en')).id,'saved');});
