// Documentación de demos generada desde el registro único admira-xp/demos.json (Carlos, 7-oct-2026 23:24).
// node admira-xp/scripts/demos-docs.mjs → reescribe la sección entre marcadores en admira-xp/help.html
// y help/demos/index.html. demos-docs.test.mjs comprueba que siguen sincronizadas con el registro.
export const START='<!-- demos-registry:start (generado desde admira-xp/demos.json · no editar a mano) -->',END='<!-- demos-registry:end -->';
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmt=s=>{const m=Math.floor(s/60),r=s%60;return m?m+' min'+(r?' '+r+' s':''):r+' s';};
export function tourSeconds(reg){const c=reg.tour?.title_card_s??2;return reg.demos.filter(d=>d.tour).reduce((a,d)=>a+d.duration_s+c,0);}
export function renderDemosSection(reg){const tour=reg.demos.filter(d=>d.tour),total=fmt(tourSeconds(reg));
 const card=d=>'<li class="dq'+(d.tour?'':' solo')+'" id="demo-'+esc(d.id)+'"><b class="n">'+d.n+'</b><h3><span lang="es">'+esc(d.name.es)+'</span><span lang="en">'+esc(d.name.en)+'</span></h3>'
  +'<p lang="es">'+esc(d.shows.es)+'</p><p lang="en">'+esc(d.shows.en)+'</p>'
  +'<p class="run"><code>/demo '+d.n+'</code>'+(d.id!==String(d.n)?' · <code>/demo '+esc(d.id)+'</code>':'')+' · '+fmt(d.duration_s)+(d.tour?' · ▶ all':'')+(d.only?' · '+esc(d.only):'')+'</p>'
  +'<p class="fx" lang="es">'+esc(d.tour?d.side_effects.es:'Solo individual: '+d.tour_skip_reason.es+'. '+d.side_effects.es)+'</p><p class="fx" lang="en">'+esc(d.tour?d.side_effects.en:'Single only: '+d.tour_skip_reason.en+'. '+d.side_effects.en)+'</p>'
  +'<p class="own">'+esc(d.command)+' · '+esc(d.owner)+(d.link?' · <a href="'+esc(d.link)+'">'+'help</a>':'')+'</p></li>';
 return START+'\n<section id="demos"><style>#demos .dgrid{list-style:none;padding:0;margin:16px 0;display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:12px}#demos .dq{aspect-ratio:1;overflow:auto;position:relative;border:1px solid rgba(0,229,168,.45);border-radius:14px;padding:14px 14px 10px;background:rgba(0,229,168,.05)}#demos .dq.solo{border-style:dashed;opacity:.9}#demos .dq .n{position:absolute;top:10px;right:12px;font:700 22px/1 ui-monospace,monospace;color:#00e5a8}#demos .dq h3{margin:0 34px 6px 0;font-size:16px;line-height:1.25}#demos .dq p{margin:0 0 6px;font-size:13px;line-height:1.4}#demos .dq .run code{font-size:12px}#demos .dq .fx,#demos .dq .own{opacity:.75;font-size:12px}</style>'
  +'<h2>Demos · /demo help · /demo all</h2>'
  +'<p lang="es"><code>/demo help</code> (o <code>/demo ayuda</code>) lista las '+reg.demos.length+' demos numeradas. <code>/demo all</code> (o <code>/demo todas</code>) enseña seguidas las '+tour.length+' marcadas ▶ (≈ '+total+'): tarjeta «Demo n/'+tour.length+' · nombre», cámara y unos segundos por demo; <code>/demo next</code> salta, <code>/demo stop</code> o Esc detiene, y al final el gemelo vuelve a su estado inicial (vista, cámara, pantallas, playlist, iPad, aviso y música). <code>/demo &lt;id|número&gt;</code> lanza una sola. La incidencia de demo crea y cierra un ticket CLI nuevo (nunca una incidencia real) y su informe no se envía salvo con <code>/demo all --enviar</code>. Las demos 1–5 son del motor común de la suite y conservan su número.</p>'
  +'<p lang="en"><code>/demo help</code> (or <code>/demo ayuda</code>) lists the '+reg.demos.length+' numbered demos. <code>/demo all</code> (or <code>/demo todas</code>) shows the '+tour.length+' ▶ demos in a row (≈ '+total+'): a “Demo n/'+tour.length+' · name” card, camera moves and a few seconds each; <code>/demo next</code> skips, <code>/demo stop</code> or Esc stops, and the twin returns to its initial state (view, camera, screens, playlist, iPad, announcement and music). <code>/demo &lt;id|number&gt;</code> runs one. The incident demo creates and closes a new CLI ticket (never a real incident) and its report is not sent unless <code>/demo all --enviar</code>. Demos 1–5 belong to the shared suite engine and keep their numbers.</p>'
  +'<ol class="dgrid">'+reg.demos.map(card).join('')+'</ol>'
  +'<p><a href="https://www.admira.store/admira-xp/demos.json">demos.json</a> · <span lang="es">registro único (id, nombre ES/EN, qué enseña, orden, duración, efectos, responsable, enlace)</span><span lang="en">single registry (id, ES/EN name, what it shows, command, duration, side effects, owner, link)</span></p></section>\n'+END;}
export function injectSection(html,section,{before}={}){const a=html.indexOf(START),b=html.indexOf(END);
 if(a>=0&&b>a)return html.slice(0,a)+section+html.slice(b+END.length);const at=html.indexOf(before);if(at<0)throw Error('marker not found: '+before);return html.slice(0,at)+section+'\n'+html.slice(at);}
export const TARGETS=[{file:'admira-xp/help.html',before:'<section id="demo-catalog"'},{file:'help/demos/index.html',before:'<h2><span lang="es">Estado actual</span>'}];
if(typeof process!=='undefined'&&process.argv[1]&&import.meta.url===new URL('file://'+process.argv[1]).href){
 const fs=await import('node:fs');const root=new URL('../../',import.meta.url);const reg=JSON.parse(fs.readFileSync(new URL('admira-xp/demos.json',root),'utf8'));const section=renderDemosSection(reg);
 for(const t of TARGETS){const u=new URL(t.file,root),h=fs.readFileSync(u,'utf8'),n=injectSection(h,section,t);if(n!==h){fs.writeFileSync(u,n);console.log('updated',t.file);}}}
