import {interfaceTranslator} from './interface-language.mjs?v=options-language-1';
import {createSharedPlaylists,playlistReference} from './shared-playlists.mjs?v=ipad-20261005-1';
import {mountPlaylistReorder} from './playlist-reorder.mjs?v=drop-1';
import {mountPixeriaPicker} from './pixeria-picker.mjs?v=drop-1';
import {DEVICE_IDS,emptyDeviceLayout,validateDeviceLayout,changeDeviceLayout,assignedPlaylist} from './device-layout.mjs?v=ipad-20261005-1';
import {attachFloatingPanel} from './floating-panels.mjs?v=windows-menu-1';
export const DEVICE_STORAGE='xpaceos.starbucks.device-layout.v1';
export function mountDeviceEditor({root,surface,lang='es',nameFor,catalog,onChange,onPlay,onPreview,onReload,onOpen=()=>{},getPlayback=()=>[]}){
 const copy=interfaceTranslator(),t=copy.t,selected=new Set();let config=emptyDeviceLayout(),seen=0,enabled=false,multiple=false,savedDraft='',draftRevision;const shared=createSharedPlaylists();let busy=false,disposed=false,pollTimer;const activeShared=new Set();
 try{const saved=JSON.parse(localStorage.getItem(DEVICE_STORAGE));if(saved){config=validateDeviceLayout(saved.config);seen=Number(saved.remoteRevision)||0;}}catch{}
 const panel=document.createElement('section');panel.className='matrix-device-editor matrix-playlist-editor';panel.hidden=true;panel.setAttribute('aria-label',t('Playlist del dispositivo','Device playlist'));
 panel.innerHTML=`<header><strong>${t('Dispositivos · Playlist','Devices · Playlist')}</strong><button type="button" data-device="close" aria-label="${t('Cerrar','Close')}">×</button></header>
 <p class="device-selection"></p>
 <div class="device-playlist-bar"><select class="device-playlists" aria-label="${t('Playlist disponible','Available playlist')}"></select><button type="button" data-device="assign">${t('Usar','Use')}</button><button type="button" data-device="reload">${t('Recargar','Reload')}</button></div>
 <div class="device-id-bar"><span class="device-reference"></span><button type="button" data-device="copy-id">${t('Copiar ID','Copy ID')}</button></div>
 <details class="device-details"><summary>${t('Ajustes e información','Settings and information')}</summary><label class="device-loop-label"><input type="checkbox" class="device-loop" checked> ${t('Reproducir en bucle','Loop playlist')}</label><p class="device-loop-help">${t('Activado: del último al primero. Desactivado: se detiene al final. Se guarda al cambiarlo.','On: last to first. Off: stops at the end. Saves when changed.')}</p><label class="device-multiple"><input type="checkbox"> ${t('Selección múltiple (Ctrl / Cmd + clic)','Multiple selection (Ctrl / Cmd + click)')}</label><label>${t('Nombre de playlist','Playlist name')}<input class="device-title" maxlength="100"></label><p class="device-shared"></p><p class="pixeria-hint">${t('Título, #hashtag o #1329: Enter busca en Pixeria; elegir guarda y reproduce. Arrastra la miniatura para ordenar o probar en una pantalla. Recargar restaura la programación guardada.','Title, #hashtag or #1329: Enter searches Pixeria; choosing saves and plays. Drag the thumbnail to reorder or preview on a screen. Reload restores the saved schedule.')}</p><div class="device-save-actions"><button type="button" data-device="delete">${t('Eliminar playlist','Delete playlist')}</button><button type="button" data-device="group">${t('Unir seleccionados','Group selected')}</button><button type="button" data-device="split">${t('Separar seleccionados','Ungroup selected')}</button><button type="button" data-device="reset">${t('Restaurar playlist original','Restore original playlist')}</button></div><small>${t('Guardar publica por ID. MCP playlist_add añade al final. La asignación se conserva en este navegador.','Save publishes by ID. MCP playlist_add appends content. Assignments stay in this browser.')}</small></details>
 <p class="device-now-playing" role="status"></p><ol class="device-tracks" tabindex="0" aria-label="${t('Contenidos de la playlist','Playlist contents')}"></ol><footer><button type="button" data-device="add">+ ${t('Añadir vídeo','Add video')}</button><button type="button" data-device="save">${t('Guardar playlist','Save playlist')}</button></footer><p class="device-notice" role="status"></p>`;
 root.append(panel);const controls=new AbortController(),opts={signal:controls.signal},select=panel.querySelector('select'),loop=panel.querySelector('.device-loop'),title=panel.querySelector('.device-title'),tracks=panel.querySelector('ol'),notice=panel.querySelector('.device-notice');
 const floating=attachFloatingPanel(panel,{label:t('Dispositivos · Playlist','Devices · Playlist'),handle:panel.querySelector('header'),closeButton:panel.querySelector('[data-device="close"]'),bounds:surface,key:'xpaceos.window.matrix-playlist.v1',menu:'matrix-playlist',onOpen:openPanel});
 function openPanel(){
  if(disposed)return;
  const first=!selected.size;if(first)selected.add(DEVICE_IDS[0]);
  onOpen();enabled=true;surface.classList.add('device-layout-active');panel.hidden=false;
  if(first)render();else playbackChanged();
 }
 const dock=document.getElementById('telegramDock');function sizePanel(){const d=dock?.getBoundingClientRect(),r=root.getBoundingClientRect();panel.style.setProperty('--playlist-bottom-inset',Math.max(0,d?.height&&getComputedStyle(dock).visibility!=='hidden'?r.bottom-d.top:0)+'px');}const resize=new ResizeObserver(sizePanel);resize.observe(root);if(dock)resize.observe(dock);window.addEventListener('resize',sizePanel,opts);sizePanel();
 for(const event of ['pointerdown','pointerup','click','keydown','wheel'])panel.addEventListener(event,e=>e.stopPropagation(),opts);
 const dropTargets=id=>selected.size>1&&selected.has(id)?[...selected]:[id];
 function hoverDrop(id){const ids=id?dropTargets(id):[];for(const n of root.querySelectorAll('[data-device-id]'))n.classList.toggle('device-drop-target',ids.includes(n.dataset.deviceId));}
 async function dropTrack(row,id){try{if(busy)return;const track={id:row.dataset.trackId,title:row.children[0].value.trim(),url:row.children[1].value.trim()};if(!track.url)throw Error(t('Elige primero un resultado de Pixeria','Choose a Pixeria result first'));const ids=dropTargets(id);const result=await onPreview(ids,track);selected.clear();for(const target of ids)selected.add(target);highlight();selectionSummary();playbackChanged();notice.textContent=result?.error?t('Vista previa no disponible; vuelve a arrastrar para reintentar','Preview unavailable; drag again to retry'):t('Vista previa temporal · Recargar playlist vuelve a la programación guardada','Temporary preview · Reload playlist restores the saved schedule');}catch(error){notice.textContent=error.message;}}
 const reorder=mountPlaylistReorder({list:tracks,scrollRoot:tracks,signal:controls.signal,hitTest:(x,y)=>{if(!enabled)return null;const id=document.elementFromPoint(x,y)?.closest('[data-device-id]')?.dataset.deviceId;return DEVICE_IDS.includes(id)?id:null;},onHover:hoverDrop,onDrop:dropTrack,onMove:()=>{notice.textContent=t('Orden actualizado · pulsa Guardar playlist','Order updated · click Save playlist');}});
 let lastActive='';
 function selectionSummary(){const names=[...selected].map(nameFor),el=panel.querySelector('.device-selection');el.textContent=names.length>1?names.length+t(' dispositivos seleccionados',' devices selected'):names[0]||'';el.title=names.join(' · ');}
 function playbackChanged(){
  if(panel.hidden)return;const states=getPlayback([...selected]),active=[];
  for(const li of tracks.children){const match=states.filter(s=>s.playing&&!s.error&&(s.playlistId===select.value||s.preview)&&s.trackId===li.dataset.trackId&&s.url===li.children[1].value);const yes=match.length>0;
   li.classList.toggle('is-playing',yes);if(yes){li.setAttribute('aria-current','true');active.push(li);}else li.removeAttribute('aria-current');
   const badge=li.querySelector('.device-playing-badge');badge.hidden=!yes;badge.textContent=t('▶ En reproducción','▶ Playing');
  }
  const current=panel.querySelector('.device-now-playing');current.textContent=active.length?t('▶ En reproducción · ','▶ Playing · ')+active.map(li=>li.children[0].value).join(' / '):states.some(s=>s.playing&&!s.error)?t('Vista previa u otra playlist en reproducción','Preview or another playlist playing'):states.length&&states.every(s=>s.finished)?t('Playlist finalizada','Playlist finished'):t('En pausa o cargando','Paused or loading');current.title=current.textContent;
  const key=active.map(li=>li.dataset.trackId).join('|');if(key&&key!==lastActive){lastActive=key;const li=active[0];if(!tracks.contains(document.activeElement)&&!tracks.querySelector('.is-reordering')){const a=li.getBoundingClientRect(),b=tracks.getBoundingClientRect();if(a.top<b.top||a.bottom>b.bottom)tracks.scrollTop+=a.top-b.top;}}
 }
 const all=()=>({...catalog(),...config.playlists});
 function highlight(){for(const n of root.querySelectorAll('[data-device-id]')){const yes=selected.has(n.dataset.deviceId);n.classList.toggle('device-selected',yes);n.setAttribute('aria-pressed',String(yes));}}
 function row(track={id:crypto.randomUUID(),title:'',url:''}){const li=document.createElement('li');li.dataset.trackId=track.id||track.stockId||crypto.randomUUID();if(track.kind==='image')li.dataset.kind='image';const label=document.createElement('input'),url=document.createElement('input');label.value=track.title;label.placeholder=t('Título, #hashtag o #1329','Title, #hashtag or #1329');label.setAttribute('aria-label',label.placeholder);url.value=track.url;url.type='hidden';url.placeholder='https://stock.admira.store/…/asset.mp4';url.setAttribute('aria-label',t('URL del vídeo','Video URL'));li.append(label,url);
  for(const [text,action] of [['↑',()=>li.previousElementSibling&&tracks.insertBefore(li,li.previousElementSibling)],['↓',()=>li.nextElementSibling&&tracks.insertBefore(li.nextElementSibling,li)],['×',()=>li.remove()]]){const b=document.createElement('button');b.type='button';b.textContent=text;b.setAttribute('aria-label',text==='↑'?t('Subir vídeo','Move video up'):text==='↓'?t('Bajar vídeo','Move video down'):t('Quitar vídeo','Remove video'));b.addEventListener('click',action,opts);li.append(b);}
  const preview=document.createElement('video');preview.className='device-preview';preview.muted=true;preview.playsInline=true;preview.preload='metadata';preview.tabIndex=-1;preview.setAttribute('aria-label',t('Previo del contenido','Content preview'));
  const play=document.createElement('button');play.type='button';play.className='device-track-play';play.textContent='▶';play.setAttribute('aria-label',t('Reproducir este contenido','Play this content'));play.title=t('Saltar a este contenido','Jump to this content');const handle=document.createElement('button');handle.type='button';handle.className='device-preview-handle';handle.title=t('Arrastra para ordenar o suelta sobre una pantalla para previsualizar · ↑ ↓ con teclado','Drag to reorder or drop on a screen to preview · ↑ ↓ with keyboard');handle.setAttribute('aria-label',t('Reordenar contenido: ','Reorder content: ')+track.title);handle.append(preview);li.append(play,handle);
  function updatePreview(){handle.setAttribute('aria-label',t('Reordenar contenido: ','Reorder content: ')+label.value);let valid=false;try{const u=new URL(url.value);valid=u.protocol==='https:'&&!u.username&&!u.password&&!/(^|\.)(youtube\.com|youtu\.be)$/.test(u.hostname);}catch{}play.disabled=!valid;preview.hidden=!valid;if(valid){if(li.dataset.kind==='image'){preview.removeAttribute('src');preview.poster=url.value;}else{preview.poster='';preview.src=url.value.split('#')[0]+'#t=0.1';}preview.load();}else{preview.removeAttribute('src');preview.load();}if(li.isConnected)playbackChanged();}
  url.addEventListener('change',updatePreview,opts);updatePreview();
  play.addEventListener('click',async()=>{try{if(busy)return;const trackId=li.dataset.trackId;let pid=select.value;if(JSON.stringify(draft())!==savedDraft)pid=await save();else if([...selected].some(id=>assignedPlaylist(config,id)!==pid))commit(changeDeviceLayout(config,{action:'assign',device_ids:[...selected],playlist_id:pid}));play.disabled=true;const result=await onPlay(pid,trackId);notice.textContent=result?.error?t('No se pudo reproducir el vídeo; pulsa Play para reintentar','Video could not play; press Play to retry'):t('Reproduciendo: ','Playing: ')+label.value;}catch(error){notice.textContent=error.message;}finally{play.disabled=false;}},opts);
  const badge=document.createElement('span');badge.className='device-playing-badge';badge.hidden=true;li.append(badge);tracks.append(li);mountPixeriaPicker({row:li,title:label,url,signal:controls.signal,lang,onInput:updatePreview,onPick:async item=>{if([...tracks.children].some(other=>other!==li&&(other.dataset.trackId===item.id||other.children[1].value===item.url)))throw Error(t('Ese vídeo ya está en esta playlist','That video is already in this playlist'));li.dataset.trackId=item.id;delete li.dataset.kind;label.value=item.title;url.value=item.url;updatePreview();const pid=await save();const result=await onPlay(pid,item.id);notice.textContent=result?.error?t('Guardado; no se pudo reproducir. Pulsa Play para reintentar.','Saved; playback failed. Press Play to retry.'):t('Asignado y reproduciendo: ','Assigned and playing: ')+item.title;}});
 }
 function loadDraft(){reorder.cancel();panel.querySelector('[data-device=delete]').disabled=!Object.hasOwn(config.playlists,select.value);const p=all()[select.value];title.value=p?.title||'';loop.checked=p?.loop!==false;tracks.replaceChildren();for(const track of p?.tracks||[])row(track);const members=DEVICE_IDS.filter(id=>assignedPlaylist(config,id)===select.value);panel.querySelector('.device-shared').textContent=t('Playlist usada por: ','Playlist used by: ')+members.map(nameFor).join(', ');savedDraft=JSON.stringify(draft());draftRevision=shared.revision(select.value);const ref=panel.querySelector('.device-reference');ref.textContent=playlistReference(select.value);ref.title=ref.textContent+(select.value.startsWith('playlist-')&&!shared.known(select.value)?t(' · local: guarda para compartir',' · local: save to share'):'');lastActive='';playbackChanged();}
 function render(){sizePanel();highlight();selectionSummary();select.replaceChildren();for(const [id,p] of Object.entries(all()))select.add(new Option(p.title,id));select.value=assignedPlaylist(config,[...selected][0]);loadDraft();panel.querySelector('[data-device=group]').disabled=selected.size<2;}
 function commit(next){const checked=validateDeviceLayout(next);localStorage.setItem(DEVICE_STORAGE,JSON.stringify({config:checked,remoteRevision:seen}));config=checked;onChange(config);render();notice.textContent=t('Guardado · reproducción actualizada','Saved · playback updated');}
 const draft=()=>({title:title.value.trim(),loop:loop.checked,tracks:[...tracks.children].map(li=>({id:li.dataset.trackId,title:li.children[0].value.trim(),url:li.children[1].value.trim(),...(li.dataset.kind==='image'?{kind:'image'}:{})})).filter(t=>t.title||t.url)});
 function validatedDraft(){const p=draft();for(const [i,track] of p.tracks.entries()){if(!track.title||!track.url)throw Error(t('Busca y elige un resultado de Pixeria para el contenido ','Search and choose a Pixeria result for content ')+(i+1));}return changeDeviceLayout(config,{action:'save_playlist',playlist_id:'playlist-validation',...p}).playlists['playlist-validation'];}
 const fresh=()=> 'playlist-'+crypto.randomUUID();
 async function save(forceNew=false){
  if(busy)throw Error(t('Guardando…','Saving…'));const value=validatedDraft(),old=select.value,ids=[...selected];busy=true;panel.setAttribute('aria-busy','true');panel.inert=true;
  try{const result=await shared.save(forceNew?'':old,value,draftRevision);activeShared.add(result.playlist_id);let next=changeDeviceLayout(config,{action:'save_playlist',playlist_id:result.playlist_id,title:result.title,tracks:result.tracks,loop:result.loop});
   if(!forceNew&&old.startsWith('playlist-')&&old!==result.playlist_id){for(const [id,pid]of Object.entries(next.assignments))if(pid===old)next.assignments[id]=result.playlist_id;delete next.playlists[old];}
   next=changeDeviceLayout(next,{action:'assign',device_ids:ids,playlist_id:result.playlist_id});commit(next);notice.textContent=t('Guardada y compartida: ','Saved and shared: ')+result.id;return result.playlist_id;
  }finally{busy=false;panel.inert=false;panel.removeAttribute('aria-busy');}
 }
 async function poll(){try{for(const id of Object.keys(config.playlists)){if(!shared.known(id)||busy)continue;const value=await shared.read(id);if(disposed)return;if(busy)continue;const first=!activeShared.has(id);activeShared.add(id);if(!value||value.revision===shared.revision(id))continue;const previous=shared.revision(id);const dirty=!panel.hidden&&JSON.stringify(draft())!==savedDraft;shared.accept(id,value.revision);config=changeDeviceLayout(config,{action:'save_playlist',playlist_id:id,title:value.title,tracks:value.tracks,loop:value.loop});localStorage.setItem(DEVICE_STORAGE,JSON.stringify({config,remoteRevision:seen}));onChange(config);if(!first&&value.playRequest?.revision>previous)void onPlay(id,value.playRequest.trackId).catch(error=>notice.textContent=error.message);if(!panel.hidden&&!dirty)render();notice.textContent=dirty?t('Playlist actualizada por otro agente. Conservamos tu borrador; recarga antes de guardar.','Playlist updated by another agent. Draft retained; reload before saving.'):t('Contenido actualizado por MCP','Content updated through MCP');}}catch{}finally{if(!disposed)pollTimer=setTimeout(poll,5000);}}
 void poll();

 async function reloadOriginal(ids){if(busy)throw Error(t('Guardando…','Saving…'));
   busy=true;panel.inert=true;try{const pids=[...new Set(ids.map(id=>assignedPlaylist(config,id)))];let next=config;
    for(const id of pids)if(shared.known(id)){const value=await shared.read(id);if(value){shared.accept(id,value.revision);next=changeDeviceLayout(next,{action:'save_playlist',playlist_id:id,title:value.title,tracks:value.tracks,loop:value.loop});}}
    commit(next);const result=await onReload(ids);notice.textContent=result?.error?t('No se pudo reproducir; pulsa Recargar playlist para reintentar','Playback failed; press Reload playlist to retry'):result?.empty?t('Playlist vacía','Empty playlist'):t('Playlist guardada · desde el principio; respeta el ajuste de bucle','Saved playlist · from the start; keeps its loop setting');
   return result;}finally{busy=false;panel.inert=false;}
 }
 loop.addEventListener('change',async()=>{try{await save();notice.textContent=loop.checked?t('Bucle activado · del último al primero','Loop enabled · last to first'):t('Bucle desactivado · se detiene al final','Loop disabled · stops at the end');}catch(error){notice.textContent=t('No guardado: ','Not saved: ')+error.message;}},opts);
 select.addEventListener('change',loadDraft,opts);panel.querySelector('.device-multiple input').addEventListener('change',e=>multiple=e.target.checked,opts);
 panel.addEventListener('click',async e=>{const action=e.target.closest('[data-device]')?.dataset.device;if(!action)return;try{
  if(action==='copy-id'){await navigator.clipboard.writeText(playlistReference(select.value));notice.textContent=t('ID copiado','ID copied');return;}if(action==='close'){panel.hidden=true;return;}if(action==='add'){row();tracks.lastElementChild.scrollIntoView({block:'nearest'});tracks.lastElementChild.children[0].focus({preventScroll:true});return;}if(!selected.size)return;
  if(busy)return;if(action==='reload'){await reloadOriginal([...selected]);return;}
  if(action==='save')await save();else if(action==='group')await save(true);else if(action==='assign')commit(changeDeviceLayout(config,{action:'assign',device_ids:[...selected],playlist_id:select.value}));
  else if(action==='delete')commit(changeDeviceLayout(config,{action:'remove_playlist',playlist_id:select.value}));
  else if(action==='reset')commit(changeDeviceLayout(config,{action:'reset',device_ids:[...selected]}));
  else if(action==='split'){let next=config;for(const device of selected){const p=all()[assignedPlaylist(config,device)],id=fresh();next=changeDeviceLayout(next,{action:'save_playlist',playlist_id:id,title:p.title+' · '+nameFor(device),tracks:p.tracks,loop:p.loop});next=changeDeviceLayout(next,{action:'assign',device_ids:[device],playlist_id:id});}commit(next);}
 }catch(error){notice.textContent=t('No guardado: ','Not saved: ')+error.message;}},opts);
 const stopLanguage=copy.observe(panel);
 return {
  get config(){return config;},
  async updatePlaylist(pid,value){
   if(busy)throw Error(t('Guardando…','Saving…'));const ids=DEVICE_IDS.filter(id=>assignedPlaylist(config,id)===pid);if(!ids.length)throw Error('Unknown destination');
   busy=true;try{const result=await shared.save(shared.known(pid)?pid:'',value,shared.revision(pid));activeShared.add(result.playlist_id);
    let next=changeDeviceLayout(config,{action:'save_playlist',playlist_id:result.playlist_id,title:result.title,tracks:result.tracks,loop:result.loop});next=changeDeviceLayout(next,{action:'assign',device_ids:ids,playlist_id:result.playlist_id});commit(next);return result.playlist_id;
   }finally{busy=false;}
  },
  reload:reloadOriginal,
  playbackChanged,
  select(id,event={}){if(!enabled||!DEVICE_IDS.includes(id))return;event.preventDefault?.();event.stopPropagation?.();if(event.ctrlKey||event.metaKey||multiple){if(selected.has(id))selected.delete(id);else selected.add(id);}else{selected.clear();selected.add(id);}panel.hidden=!selected.size;notice.textContent='';render();if(!panel.hidden)floating.restore();},
  enable(value){enabled=value;surface.classList.toggle('device-layout-active',value);if(!value){panel.hidden=true;selected.clear();highlight();}},
  refresh(){if(!panel.hidden&&!busy&&JSON.stringify(draft())===savedDraft)render();},
  remote(state){const revision=state.deviceLayoutRevision||0;if(revision<=seen)return;const next=validateDeviceLayout(state.deviceLayout||emptyDeviceLayout());for(const [id,p]of Object.entries(config.playlists))if(shared.known(id)){next.playlists[id]=p;for(const [device,pid]of Object.entries(config.assignments))if(pid===id)next.assignments[device]=id;}seen=revision;commit(next);notice.textContent=t('Configuración compartida recibida por MCP','Shared configuration received through MCP');},
  open(){floating.open();},
  dispose(){stopLanguage();disposed=true;floating.dispose();resize.disconnect();clearTimeout(pollTimer);controls.abort();panel.remove();}
 };
}
