import test from 'node:test';import assert from 'node:assert/strict';import {emptyDeviceLayout,changeDeviceLayout,assignedPlaylist,validateDeviceLayout} from './device-layout.mjs';
const track={id:'one',title:'One',url:'https://stock.admira.store/one.mp4'};
test('custom playlist edits, assignments and deletion preserve unrelated devices',()=>{let s=changeDeviceLayout(emptyDeviceLayout(),{action:'save_playlist',playlist_id:'playlist-local',title:'Local',tracks:[track]});s=changeDeviceLayout(s,{action:'assign',device_ids:['starbucks-wall-06','starbucks-tpv-01'],playlist_id:'playlist-local'});assert.equal(assignedPlaylist(s,'starbucks-wall-06'),'playlist-local');assert.equal(assignedPlaylist(s,'starbucks-wall-05'),'wall');s=changeDeviceLayout(s,{action:'save_playlist',playlist_id:'playlist-local',title:'Empty',tracks:[]});assert.equal(s.playlists['playlist-local'].tracks.length,0);s=changeDeviceLayout(s,{action:'remove_playlist',playlist_id:'playlist-local'});assert.equal(assignedPlaylist(s,'starbucks-tpv-01'),'tpv');assert.equal(assignedPlaylist(s,'starbucks-wall-06'),'wall');});
test('unknown devices/playlists, prototype keys and unsafe media cannot be saved',()=>{for(const args of [{action:'assign',device_ids:['unknown'],playlist_id:'wall'},{action:'assign',device_ids:['starbucks-wall-01'],playlist_id:'missing'},{action:'save_playlist',playlist_id:'__proto__',title:'Bad',tracks:[]},{action:'save_playlist',playlist_id:'playlist-bad',title:'Bad',tracks:[{...track,url:'https://youtube.com/shorts/test'}]},{action:'save_playlist',playlist_id:'playlist-bad',title:'Bad',tracks:[{...track,url:'https://user:password@test/a'}]}])assert.throws(()=>changeDeviceLayout(emptyDeviceLayout(),args));assert.throws(()=>validateDeviceLayout({playlists:{},assignments:{constructor:'wall'}}));});
test('loop migrates to true, validates booleans and survives edits without an explicit setting',()=>{
 let s=changeDeviceLayout(emptyDeviceLayout(),{action:'save_playlist',playlist_id:'playlist-local',title:'Demo',tracks:[track]});assert.equal(s.playlists['playlist-local'].loop,true);
 s=changeDeviceLayout(s,{action:'save_playlist',playlist_id:'playlist-local',title:'Demo',tracks:[track],loop:false});assert.equal(s.playlists['playlist-local'].loop,false);
 s=changeDeviceLayout(s,{action:'save_playlist',playlist_id:'playlist-local',title:'Renamed',tracks:[track]});assert.equal(s.playlists['playlist-local'].loop,false);
 assert.throws(()=>changeDeviceLayout(s,{action:'save_playlist',playlist_id:'playlist-local',title:'Demo',tracks:[track],loop:'false'}),/boolean/);
});
