import {mountPixeriaPicker} from './pixeria-picker.mjs?v=pixeria-1';
import {DEVICE_IDS,emptyDeviceLayout,validateDeviceLayout,changeDeviceLayout,assignedPlaylist} from './device-layout.mjs?v=devices-1';
export const DEVICE_STORAGE='xpaceos.starbucks.device-layout.v1';
export function mountDeviceEditor({root,surface,lang='es',nameFor,catalog,onChange}){
 const t=(es,en)=>lang==='en'?en:es,selected=new Set();let config=emptyDeviceLayout(),seen=0,enabled=false,multiple=false;
 try{const saved=JSON.parse(localStorage.getItem(DEVICE_STORAGE));if(saved){config=validateDeviceLayout(saved.config);seen=Number(saved.remoteRevision)||0;}}catch{}
 const panel=document.createElement('section');panel.className='matrix-device-editor';panel.hidden=true;panel.setAttribute('aria-label',t('Playlist del dispositivo','Device playlist'));
 panel.innerHTML=`<header><strong>${t('Dispositivos · Playlist','Devices · Playlist')}</strong><button type="button" data-device="close" aria-label="${t('Cerrar','Close')}">×</button></header><p class="device-selection"></p><label class="device-multiple"><input type="checkbox"> ${t('Selección múltiple (Ctrl / Cmd + clic)','Multiple selection (Ctrl / Cmd + click)')}</label><label>${t('Playlist disponible','Available playlist')}<select class="device-playlists"></select></label><button type="button" data-device="assign">${t('Usar playlist seleccionada','Use selected playlist')}</button><label>${t('Nombre de playlist','Playlist name')}<input class="device-title" maxlength="100"></label><p class="device-shared"></p><p class="pixeria-hint">${t('Añade una fila y escribe un título, #hashtag o número como #1329. Enter busca en Pixeria; después guarda la playlist.','Add a row and enter a title, #hashtag or number such as #1329. Enter searches Pixeria; then save the playlist.')}</p><ol class="device-tracks"></ol><button type="button" data-device="add">+ ${t('Añadir vídeo','Add video')}</button><div class="device-save-actions"><button type="button" data-device="delete">${t('Eliminar playlist','Delete playlist')}</button><button type="button" data-device="save">${t('Guardar playlist','Save playlist')}</button><button type="button" data-device="group">${t('Unir seleccionados','Group selected')}</button><button type="button" data-device="split">${t('Separar seleccionados','Ungroup selected')}</button><button type="button" data-device="reset">${t('Restaurar playlist original','Restore original playlist')}</button></div><p class="device-notice" role="status"></p><small>${t('Cambios guardados en este navegador. Para compartir con otros agentes: MCP matrix_device_layout.','Changes saved in this browser. To share with other agents: MCP matrix_device_layout.')}</small>`;
 root.append(panel);const controls=new AbortController(),opts={signal:controls.signal},select=panel.querySelector('select'),title=panel.querySelector('.device-title'),tracks=panel.querySelector('ol'),notice=panel.querySelector('.device-notice');
 for(const event of ['pointerdown','pointerup','click','keydown','wheel'])panel.addEventListener(event,e=>e.stopPropagation(),opts);
 const all=()=>({...catalog(),...config.playlists});
 function highlight(){for(const n of root.querySelectorAll('[data-device-id]')){const yes=selected.has(n.dataset.deviceId);n.classList.toggle('device-selected',yes);n.setAttribute('aria-pressed',String(yes));}}
 function row(track={id:crypto.randomUUID(),title:'',url:''}){const li=document.createElement('li');li.dataset.trackId=track.id||track.stockId||crypto.randomUUID();const label=document.createElement('input'),url=document.createElement('input');label.value=track.title;label.placeholder=t('Título, #hashtag o #1329','Title, #hashtag or #1329');label.setAttribute('aria-label',label.placeholder);url.value=track.url;url.type='url';url.placeholder='https://stock.admira.store/…/asset.mp4';url.setAttribute('aria-label',t('URL del vídeo','Video URL'));li.append(label,url);
  for(const [text,action] of [['↑',()=>li.previousElementSibling&&tracks.insertBefore(li,li.previousElementSibling)],['↓',()=>li.nextElementSibling&&tracks.insertBefore(li.nextElementSibling,li)],['×',()=>li.remove()]]){const b=document.createElement('button');b.type='button';b.textContent=text;b.setAttribute('aria-label',text==='↑'?t('Subir vídeo','Move video up'):text==='↓'?t('Bajar vídeo','Move video down'):t('Quitar vídeo','Remove video'));b.addEventListener('click',action,opts);li.append(b);}tracks.append(li);mountPixeriaPicker({row:li,title:label,url,signal:controls.signal,lang,onPick:item=>{if([...tracks.children].some(other=>other!==li&&(other.dataset.trackId===item.id||other.children[1].value===item.url)))throw Error(t('Ese vídeo ya está en esta playlist','That video is already in this playlist'));li.dataset.trackId=item.id;label.value=item.title;url.value=item.url;}});
 }
 function loadDraft(){panel.querySelector('[data-device=delete]').disabled=!Object.hasOwn(config.playlists,select.value);const p=all()[select.value];title.value=p?.title||'';tracks.replaceChildren();for(const track of p?.tracks||[])row(track);const members=DEVICE_IDS.filter(id=>assignedPlaylist(config,id)===select.value);panel.querySelector('.device-shared').textContent=t('Playlist usada por: ','Playlist used by: ')+members.map(nameFor).join(', ');}
 function render(){highlight();panel.querySelector('.device-selection').textContent=[...selected].map(nameFor).join(' · ');select.replaceChildren();for(const [id,p] of Object.entries(all()))select.add(new Option(p.title,id));select.value=assignedPlaylist(config,[...selected][0]);loadDraft();panel.querySelector('[data-device=group]').disabled=selected.size<2;}
 function commit(next){const checked=validateDeviceLayout(next);localStorage.setItem(DEVICE_STORAGE,JSON.stringify({config:checked,remoteRevision:seen}));config=checked;onChange(config);render();notice.textContent=t('Guardado · reproducción actualizada','Saved · playback updated');}
 const draft=()=>({title:title.value,tracks:[...tracks.children].map(li=>({id:li.dataset.trackId,title:li.children[0].value,url:li.children[1].value}))});
 const fresh=()=> 'playlist-'+crypto.randomUUID();
 function save(forceNew=false){const id=!forceNew&&Object.hasOwn(config.playlists,select.value)?select.value:fresh();let next=changeDeviceLayout(config,{action:'save_playlist',playlist_id:id,...draft(),title:(!Object.hasOwn(config.playlists,select.value)||forceNew)&&title.value===all()[select.value]?.title?'Playlist '+[...selected].map(nameFor).join(' + ').slice(0,85):title.value});next=changeDeviceLayout(next,{action:'assign',device_ids:[...selected],playlist_id:id});commit(next);}
 select.addEventListener('change',loadDraft,opts);panel.querySelector('input[type=checkbox]').addEventListener('change',e=>multiple=e.target.checked,opts);
 panel.addEventListener('click',e=>{const action=e.target.closest('[data-device]')?.dataset.device;if(!action)return;try{
  if(action==='close'){panel.hidden=true;return;}if(action==='add'){row();return;}if(!selected.size)return;
  if(action==='save')save();else if(action==='group')save(true);else if(action==='assign')commit(changeDeviceLayout(config,{action:'assign',device_ids:[...selected],playlist_id:select.value}));
  else if(action==='delete')commit(changeDeviceLayout(config,{action:'remove_playlist',playlist_id:select.value}));
  else if(action==='reset')commit(changeDeviceLayout(config,{action:'reset',device_ids:[...selected]}));
  else if(action==='split'){let next=config;for(const device of selected){const p=all()[assignedPlaylist(config,device)],id=fresh();next=changeDeviceLayout(next,{action:'save_playlist',playlist_id:id,title:p.title+' · '+nameFor(device),tracks:p.tracks});next=changeDeviceLayout(next,{action:'assign',device_ids:[device],playlist_id:id});}commit(next);}
 }catch(error){notice.textContent=t('No guardado: ','Not saved: ')+error.message;}},opts);
 return {
  get config(){return config;},
  select(id,event={}){if(!enabled||!DEVICE_IDS.includes(id))return;event.preventDefault?.();event.stopPropagation?.();if(event.ctrlKey||event.metaKey||multiple){if(selected.has(id))selected.delete(id);else selected.add(id);}else{selected.clear();selected.add(id);}panel.hidden=!selected.size;notice.textContent='';render();},
  enable(value){enabled=value;surface.classList.toggle('device-layout-active',value);if(!value){panel.hidden=true;selected.clear();highlight();}},
  refresh(){if(!panel.hidden)render();},
  remote(state){const revision=state.deviceLayoutRevision||0;if(revision<=seen)return;const next=validateDeviceLayout(state.deviceLayout||emptyDeviceLayout());seen=revision;commit(next);notice.textContent=t('Configuración compartida recibida por MCP','Shared configuration received through MCP');},
  dispose(){controls.abort();panel.remove();}
 };
}
