/* Generated media is a draft. Selection never emits; Launch or an explicit screen drop changes playback. */
(function(root){'use strict';const doc=root.document;if(!doc)return;
 const KEY='xpaceos.options-media-ready.v1',ready={},selected={},previewing={},hosts={},MIME='application/x-xpace-media';let drag=null,releases=[],pointer=null,suppressClick=false,observedAdapter=null,lastScreen={};
 const t=(es,en)=>doc.documentElement.lang==='en'?en:es;
 function asset(kind,value){const u=new URL(value.url);if(!['image','video','music'].includes(kind)||!value.id||(u.username||u.password||u.origin!=='https://api.admira.store')||u.pathname!=='/stock/asset/'+value.id)throw Error('Invalid Stock asset');let cover='';try{const c=new URL(value.thumbnail||value.poster);if(c.protocol==='https:'&&!c.username&&!c.password)cover=c.href;}catch{}return {id:String(value.id),url:u.href,kind,...(['audio','locucion'].includes(value.sourceType)?{sourceType:value.sourceType}:{}),num:value.num||null,title:String(value.title||value.prompt||'Stock '+(value.num||value.id)).slice(0,160),...(cover?{thumbnail:cover}:{})};}
 function element(tag,text,attrs={}){const e=doc.createElement(tag);if(text)e.textContent=text;for(const [key,value]of Object.entries(attrs))e.setAttribute(key,value);return e;}
 function adapter(){return root.XpaceMatrixOptions||root.XpaceOptionsPlayback;}
 function persist(){try{root.sessionStorage.setItem(KEY,JSON.stringify(ready));}catch(_){} }
 function quiet(except){for(const release of releases)release();releases=[];for(const media of doc.querySelectorAll('.media-ready audio,.options-playlist-preview audio,.options-playlist-preview video'))if(media!==except)media.pause();}
 function media(track,id){const e=element(track.kind==='image'?'img':track.kind==='music'?'audio':'video');if(id)e.id=id;if(track.kind==='image')e.alt=track.title;else{e.controls=true;e.preload='metadata';if(track.kind==='video'){e.muted=true;e.playsInline=true;}if(track.kind==='music'){
   e.addEventListener('play',()=>{quiet(e);const api=adapter();if(api?.suppressMusic)releases.push(api.suppressMusic());else{const music=doc.getElementById('bgMusic');if(music){const volume=music.volume;music.volume=0;releases.push(()=>{music.volume=volume;});}}});for(const event of ['pause','ended'])e.addEventListener(event,()=>{for(const release of releases)release();releases=[];});}}
  e.src=track.url;return e;}
 function source(node,value,preview=null){node.draggable=false;node.tabIndex=0;node.style.touchAction='none';node.style.userSelect='none';node.classList.add('media-drag-source');node.addEventListener('pointerdown',event=>{if(event.button!==0||pointer||event.target?.closest?.('button,input,select,a')&&event.target!==node)return;if(value.signage)root.XpaceSignagePointer?.active(true);pointer={value,node,preview,x:event.clientX,y:event.clientY,id:event.pointerId,active:false};node.classList.add('media-picked');if(preview){node.setPointerCapture?.(event.pointerId);event.preventDefault();node.focus({preventScroll:true});}});node.addEventListener('dragstart',event=>{drag=value;event.dataTransfer.setData(MIME,JSON.stringify(value));event.dataTransfer.effectAllowed=value.asset?'copy':'move';});node.addEventListener('dragend',()=>cancelDrag());node.addEventListener('lostpointercapture',()=>cancelDrag());}
 function previewSource(player,value){const frame=element('div'),grab=element('div');frame.className='media-preview-frame';if(player.tagName==='VIDEO')frame.classList.add('media-preview-video');grab.className='media-preview-grab';grab.title=t('Mantén pulsado y arrastra a una pantalla o playlist','Hold and drag to a screen or playlist');grab.setAttribute('aria-label',grab.title);let picture=player;if(player.tagName==='AUDIO'){frame.classList.add('media-preview-audio');const art=element('div');art.className='media-audio-art';const track=dragTrack(value);picture=track?.thumbnail?element('img',null,{src:track.thumbnail,alt:track.title}):element('span','♫');art.append(picture,grab);frame.append(art,player);}else frame.append(player,grab);source(grab,value,picture);root.XpaceMediaExperience?.bind(frame,dragTrack(value));return frame;}
 function ghostFor(current){const track=current.value.track,ghost=element('div'),visual=element('div');ghost.className='media-drag-ghost';visual.className='media-drag-visual';ghost.setAttribute('aria-hidden','true');let picture=current.preview;
  if(!picture&&track){const selector=current.value.asset?'[data-media-ready="'+current.value.asset+'"]':'.options-playlist-preview';picture=[...doc.querySelectorAll(selector+' img,'+selector+' video')].find(node=>node.getAttribute('src')===track.url);}
  if(picture?.tagName==='IMG'){const image=picture.cloneNode();image.removeAttribute('id');image.draggable=false;visual.append(image);}
  else if(picture?.tagName==='VIDEO'&&picture.readyState>=2){try{const canvas=element('canvas');canvas.width=picture.videoWidth;canvas.height=picture.videoHeight;canvas.getContext('2d').drawImage(picture,0,0);visual.append(canvas);}catch{}}
  if(!visual.children.length&&(picture?.poster||track?.thumbnail))visual.append(element('img',null,{src:picture?.poster||track.thumbnail,alt:''}));
  if(!visual.children.length)visual.append(element('span',track?.kind==='music'?'♫':'▣'));ghost.append(visual);
  ghost.append(element('strong',track?.title||t('Contenido','Content')));(current.node.closest('dialog[open]')||doc.body).append(ghost);return ghost;
 }
 function finishPointer(){const current=pointer;pointer=null;drag=null;if(!current)return;if(current.value.signage)root.XpaceSignagePointer?.active(false);current.ghost?.remove();current.node.classList.remove('media-picked');doc.documentElement.classList.remove('media-dragging');if(current.node.hasPointerCapture?.(current.id))current.node.releasePointerCapture(current.id);return current;}
 function cancelDrag(){finishPointer();clearHover();}
 async function insert(channel,before,launch=false,value=drag){const api=adapter();if(!api||!value)throw Error('No content');const group=selected[channel]||api.groups(channel)[0]?.id;if(!group)throw Error('No destination');if(value.asset||value.staged){const track=value.staged||ready[value.asset];if(!track||(channel==='music')!==(track.kind==='music'))throw Error(t('Elige la playlist de este tipo de contenido.','Choose a matching playlist.'));const id=await api.insert(channel,track,before,group);if(launch)await api.play(channel,id,selected[channel]||group);}else{if(value.channel!==channel||value.group!==group)throw Error(t('Arrastra dentro de la misma playlist.','Drag within the same playlist.'));await api.move(channel,value.id,before,group);}renderLists(true);}
 function drop(node,channel,before){node.dataset.mediaDropChannel=channel;node.dataset.mediaDropBefore=before||'';node.addEventListener('dragover',event=>{if(!drag)return;event.preventDefault();event.dataTransfer.dropEffect=drag.asset?'copy':'move';node.classList.add('media-drop-over');});node.addEventListener('dragleave',()=>node.classList.remove('media-drop-over'));node.addEventListener('drop',async event=>{event.preventDefault();event.stopPropagation();node.classList.remove('media-drop-over');try{await insert(channel,before);notice(channel,t('Añadido a la playlist. Pulsa ▶ para emitir.','Added to the playlist. Press ▶ to play.'));}catch(e){notice(channel,e.message);}finally{drag=null;}});}
 function screenAdapter(){if(doc.body?.classList?.contains?.('xpace-matrix-active'))return root.XpaceMatrixOptions;return root.XpaceMatrixOptions||root.XpaceSceneScreens||root.XpaceOptionsPlayback;}
 function dragTrack(value){if(value.staged)return value.staged;if(value.asset)return ready[value.asset];return adapter()?.state(value.channel,value.group)?.tracks.find(track=>track.id===value.id);}
 function targetAt(x,y,value=pointer?.value||drag){const element=doc.elementFromPoint(x,y);if(value?.signage){const target=root.XpaceSignagePointer?.target(element,x,y);if(target)return {signage:target};}const playlist=element?.closest('[data-media-drop-channel]');if(playlist)return {playlist};const api=screenAdapter(),id=api?.screenAt?.(x,y);return id?{api,id}:null;}
 function clearHover(){doc.querySelectorAll('.media-drop-over').forEach(node=>node.classList.remove('media-drop-over'));screenAdapter()?.screenHighlight?.(null);}
 async function applyDrop(target,value){if(target.signage){await root.XpaceSignagePointer.drop(value.signage,target.signage);return;}if(target.playlist){const channel=target.playlist.dataset.mediaDropChannel;await insert(channel,target.playlist.dataset.mediaDropBefore||null,false,value);notice(channel,t('Añadido a la playlist. Pulsa ▶ para emitir.','Added to the playlist. Press ▶ to play.'));return;}
  const track=value.track||dragTrack(value);if(!track?.url||!['image','video'].includes(track.kind))throw Error(t('Elige una imagen o un vídeo para esta pantalla.','Choose an image or video for this screen.'));
  await target.api.previewScreen(target.id,track);const kind=value.asset||track.kind;lastScreen[kind]={api:target.api,id:target.id};const node=doc.querySelector('[data-media-ready="'+kind+'"]');if(node?.querySelector('[data-media-hint]')){node.querySelector('[data-media-hint]').textContent=t('Mostrando sólo en ','Showing only on ')+(target.api.screenTitle?.(target.id)||target.id)+t(' · Recargar restaura la programación.',' · Reload restores the schedule.');node.querySelector('[data-media-restore]').hidden=false;}notice('screens',t('Contenido soltado en ','Content dropped on ')+(target.api.screenTitle?.(target.id)||target.id));
 }
 doc.addEventListener('pointermove',event=>{if(!pointer||event.pointerId!==pointer.id)return;if(!pointer.active&&Math.hypot(event.clientX-pointer.x,event.clientY-pointer.y)<6)return;if(!pointer.active){pointer.node.setPointerCapture?.(pointer.id);pointer.value={...pointer.value,track:dragTrack(pointer.value)};pointer.ghost=ghostFor(pointer);doc.documentElement.classList.add('media-dragging');}pointer.active=true;drag=pointer.value;Object.assign(pointer.ghost.style,{left:event.clientX+'px',top:event.clientY+'px'});event.preventDefault();event.stopPropagation();clearHover();const target=targetAt(event.clientX,event.clientY);pointer.ghost.classList.toggle('can-drop',!!target);if(target?.playlist)target.playlist.classList.add('media-drop-over');else if(target?.api)target.api.screenHighlight?.(target.id);else if(target?.signage?.node)target.signage.node.classList.add('media-drop-over');},{capture:true,passive:false});
 doc.addEventListener('pointerup',event=>{if(!pointer||event.pointerId!==pointer.id)return;const current=finishPointer();if(!current.active)return;event.preventDefault();event.stopImmediatePropagation();suppressClick=true;root.setTimeout(()=>suppressClick=false,0);const target=targetAt(event.clientX,event.clientY,current.value);clearHover();if(!target)return;applyDrop(target,current.value).catch(error=>{notice(current.value.asset==='music'?'music':'screens',error.message);const hint=doc.querySelector('[data-media-ready="'+(current.value.asset||'video')+'"] [data-media-hint]');if(hint)hint.textContent=error.message;});},true);
 doc.addEventListener('pointercancel',()=>cancelDrag(),true);
 doc.addEventListener('keydown',event=>{if(event.key==='Escape'&&pointer){event.preventDefault();event.stopImmediatePropagation();cancelDrag();}},true);
 root.addEventListener('blur',cancelDrag);
 doc.addEventListener('click',event=>{if(suppressClick){event.preventDefault();event.stopImmediatePropagation();suppressClick=false;}},true);
 function notice(channel,message){const h=hosts[channel];if(h)h.status.textContent=message;}
 function renderReady(kind){const track=ready[kind],node=doc.querySelector('[data-media-ready="'+kind+'"]');if(!node||!track)return;quiet();node.hidden=false;
  // Keep the original video element so the generation module retains its handle.
  let player=kind==='video'?doc.getElementById('videoPreview'):null;node.replaceChildren();if(!player)player=media(track,kind+'Preview');else{player.src=track.url;player.hidden=false;player.load();}node.append(previewSource(player,{asset:kind}));
  const title=element('p',track.title),hint=element('p',t('Previo · arrastra la imagen; su centro sigue al cursor hasta la pantalla o playlist.','Preview · drag the image; its centre follows the cursor to the screen or playlist.'));if(kind==='music')hint.textContent=t('Previo de audio · arrastra la carátula a la playlist musical o pulsa Lanzar.','Audio preview · drag the cover to the music playlist or press Launch.');hint.dataset.mediaHint=kind;source(title,{asset:kind},kind==='music'?null:player);node.append(title,hint);
  const launch=element('button',t('▶ Lanzar al hilo musical','▶ Launch to background music'));if(kind!=='music')launch.textContent=t('▶ Lanzar a pantallas','▶ Launch to screens');launch.type='button';launch.dataset.mediaLaunch=kind;
  const add=element('button',t('+ Añadir a playlist','+ Add to playlist'));add.type='button';add.dataset.mediaAdd=kind;
  for(const [button,playing]of [[launch,true],[add,false]])button.addEventListener('click',async()=>{button.disabled=true;const channel=kind==='music'?'music':'screens';try{quiet();await insert(channel,null,playing,{asset:kind});hint.textContent=playing?t('Lanzado al reproductor del Xpacio.','Launched to the Xpace player.'):t('Añadido. La emisión actual continúa.','Added. Current playback continues.');}catch(e){hint.textContent=t('No se pudo aplicar: ','Could not apply: ')+e.message;}finally{button.disabled=false;}});
  const restore=element('button',t('↺ Recargar pantalla','↺ Reload screen'));restore.type='button';restore.dataset.mediaRestore=kind;restore.hidden=!lastScreen[kind];restore.addEventListener('click',async()=>{restore.disabled=true;try{const previous=lastScreen[kind];if(!previous)return;if(previous.api.isActive?.()===false)throw Error(t('Vuelve a la vista del destino.','Return to the destination view.'));await previous.api.restoreScreen(previous.id);delete lastScreen[kind];restore.hidden=true;hint.textContent=t('Programación de la pantalla restaurada.','Screen schedule restored.');}catch(error){hint.textContent=error.message;}finally{restore.disabled=false;}});
  node.append(launch,add,restore);if(kind==='music'){const link=element('a',t('Ver en Stock','Open in Stock'),{href:'https://www.pixeria.com/stock.html?highlight='+encodeURIComponent(track.id),target:'_blank',rel:'noopener'});node.append(link);}
 }
 // created:true = recién creado en Experto → Crear contenidos: además del previo de Opciones, se abre en PREVIOS (3.ª columna).
 function stage(kind,value,{created=false}={}){const track=asset(kind,value);ready[kind]=track;persist();renderReady(kind);if(created&&root.XpaceCreatedMedia)root.XpaceCreatedMedia.add(kind,track);else if(created&&root.dispatchEvent&&root.CustomEvent)root.dispatchEvent(new root.CustomEvent('xpace:media-created',{detail:{kind,track:{...track}}}));return track;}
 // Lanzar desde PREVIOS: cualquier pieza de Stock validada, no sólo la última de cada tipo.
 async function launch(kind,value,{play=true}={}){const track=asset(kind,value),channel=kind==='music'?'music':'screens';quiet();await insert(channel,null,play,{staged:track});return track;}
 function initialiseLists(){for(const node of doc.querySelectorAll('[data-options-playlist]')){const channel=node.dataset.optionsPlaylist,body=node.querySelector('.options-playlist-body'),select=element('select',null,{'aria-label':t('Destino de playlist','Playlist destination')}),hint=element('p',t('Arrastra aquí el contenido nuevo. Añadir no cambia lo que está sonando.','Drop new content here. Adding keeps current playback.')),status=element('p','',{'role':'status'}),preview=element('div');preview.className='options-playlist-preview';const list=element('ol');list.setAttribute('aria-label',t('Playlist actual','Current playlist'));body.append(select,hint,preview,list,status);hosts[channel]={node,select,hint,status,preview,list,signature:''};drop(node.querySelector('summary'),channel,null);drop(hint,channel,null);drop(list,channel,null);select.addEventListener('change',()=>{selected[channel]=select.value;renderLists(true);});node.addEventListener('toggle',()=>{if(!node.open){for(const e of preview.querySelectorAll('audio,video'))e.pause();}renderLists(true);});}}
 function previewTrack(channel,track){quiet();const h=hosts[channel];h.preview.replaceChildren();if(track.url){const player=media(track),value={channel,group:selected[channel],id:track.id};h.preview.append(previewSource(player,value));previewing[channel]=track.id;}else h.preview.textContent=t('Contenido animado del Xpacio. Usa ▶ para verlo en pantalla.','Xpace animation. Press ▶ to display it.');}
 function renderLists(force=false){const api=adapter();if(!api)return;if(api!==observedAdapter){observedAdapter=api;for(const kind of Object.keys(ready))renderReady(kind);}for(const [channel,h]of Object.entries(hosts)){
  const groups=api.groups(channel)||[];if(!groups.some(g=>g.id===selected[channel]))selected[channel]=groups[0]?.id;const state=api.state(channel,selected[channel]);if(!state)continue;
  const signature=JSON.stringify([doc.documentElement.lang,selected[channel],groups,state.tracks,state.playing]);if(!force&&signature===h.signature)continue;h.signature=signature;
  h.node.querySelector('summary').textContent=t('Playlist actual · ','Current playlist · ')+(channel==='music'?t('Hilo musical','Background music'):t('Pantallas','Screens'))+' ('+state.tracks.length+')';h.select.replaceChildren(...groups.map(g=>{const o=element('option',g.title);o.value=g.id;return o;}));h.select.value=selected[channel]||'';h.select.hidden=groups.length<2;
  h.hint.textContent=t('Arrastra aquí el contenido nuevo. Añadir no cambia la emisión.','Drop new content here. Adding keeps current playback.');h.list.replaceChildren();
  for(let i=0;i<state.tracks.length;i++){const track=state.tracks[i],row=element('li');row.dataset.trackId=track.id;row.setAttribute('aria-current',String(!!track.active));source(row,{channel,group:selected[channel],id:track.id});drop(row,channel,track.id);
   const view=element('button',(track.active?'● ':'')+(i+1)+'. '+track.title,{'title':t('Ver previo','Preview')});view.type='button';view.addEventListener('click',()=>previewTrack(channel,track));
   const play=element('button','▶',{'aria-label':t('Lanzar ','Launch ')+track.title});play.type='button';play.addEventListener('click',async()=>{try{quiet();await api.play(channel,track.id,selected[channel]);notice(channel,t('Contenido lanzado.','Content launched.'));renderLists(true);}catch(e){notice(channel,t('No se pudo reproducir: ','Could not play: ')+e.message);}});
   const up=element('button','↑',{'aria-label':t('Subir ','Move up ')+track.title});up.type='button';up.disabled=i===0;up.addEventListener('click',async()=>{try{await api.move(channel,track.id,state.tracks[i-1].id,selected[channel]);renderLists(true);}catch(e){notice(channel,e.message);}});row.append(view,play,up);h.list.append(row);}
  if(!state.tracks.length)h.status.textContent=t('Playlist vacía.','Empty playlist.');
 }}
 root.XpaceMediaOptions={stage,launch,attachSignage:(node,name,track,picture)=>source(node,{signage:name,staged:track},picture),preview:(kind,stock,player)=>previewSource(player,{asset:kind,staged:asset(kind,stock)}),attachPreview:(node,kind,stock,picture)=>source(node,{asset:kind,staged:asset(kind,stock)},picture),get:kind=>ready[kind]||null};
 try{const stored=JSON.parse(root.sessionStorage.getItem(KEY)||'{}');for(const [kind,value]of Object.entries(stored))try{ready[kind]=asset(kind,value);}catch(_){} }catch(_){}
 initialiseLists();for(const kind of Object.keys(ready))renderReady(kind);
 doc.addEventListener('click',event=>{const action=event.target.closest('[data-xp-do]')?.dataset.xpDo,api=adapter();if(api?.control&&['musicToggle','musicPrev','musicNext','dsToggle','dsPrev','dsNext'].includes(action)){event.preventDefault();event.stopImmediatePropagation();quiet();Promise.resolve(api.control(action,selected.screens)).then(()=>renderLists(true)).catch(e=>notice(action.startsWith('music')?'music':'screens',e.message));}},true);
 root.addEventListener('xpace:playlist-destination',event=>{selected[event.detail.channel]=event.detail.id;});
 root.addEventListener('xpace:playlist',()=>renderLists(true));root.addEventListener('pagehide',()=>{cancelDrag();quiet();});
 new root.MutationObserver(()=>{for(const kind of Object.keys(ready))renderReady(kind);renderLists(true);}).observe(doc.documentElement,{attributes:true,attributeFilter:['lang']});
 root.setInterval(()=>renderLists(),1000);renderLists();
})(typeof window!=='undefined'?window:globalThis);
