import test from 'node:test';import assert from 'node:assert/strict';import {searchPixeriaVideos} from './pixeria-picker.mjs';
test('query encodes literal hashtags and exposes results without publishing or sending credentials',async()=>{let call;const result=await searchPixeriaVideos('#1329',{fetcher:async(url,options)=>{call={url,options};return {ok:true,json:async()=>({total:1,items:[{id:'a',type:'video',title:'Good',url:'https://media.test/a.mp4'}]})}}});assert.match(call.url,/query=%231329/);assert.equal(call.options.method,undefined);assert.equal(call.options.headers,undefined);assert.equal(result.total,1);});
test('missing queries, upstream failures and invalid media are explicit and cannot enter a playlist',async()=>{await assert.rejects(searchPixeriaVideos(''),/Enter/);await assert.rejects(searchPixeriaVideos('a',{fetcher:async()=>({ok:false,json:async()=>({error:'offline'})})}),/offline/);await assert.rejects(searchPixeriaVideos('a',{fetcher:async()=>({ok:true,json:async()=>({items:[{id:'a',type:'video',title:'A',url:'javascript:alert(1)'}]})})}),/Invalid video/);});
test('leaving a searched field preserves result buttons until the user chooses',async()=>{
 const oldDocument=globalThis.document,oldFetch=globalThis.fetch;let searches=0,picked;
 class Element extends EventTarget{constructor(){super();this.children=[];this.value='';this.isConnected=true;}append(...children){this.children.push(...children);}replaceChildren(...children){this.children=children;}setAttribute(){}}
 globalThis.document={createElement:()=>new Element()};globalThis.fetch=async()=>{searches++;return {ok:true,json:async()=>({total:2,items:['a','b'].map(id=>({id,type:'video',title:id,url:'https://media.test/'+id+'.mp4'}))})}};
 const controller=new AbortController();try{const {mountPixeriaPicker}=await import('./pixeria-picker.mjs');const row=new Element(),title=new Element(),url=new Element();title.value='#coffee';mountPixeriaPicker({row,title,url,signal:controller.signal,onPick:async item=>{picked=item.id}});const enter=new Event('keydown');Object.defineProperty(enter,'key',{value:'Enter'});title.dispatchEvent(enter);await new Promise(resolve=>setImmediate(resolve));const results=row.children[2],first=results.children[0];assert.equal(results.children.length,2);title.dispatchEvent(new Event('change'));assert.equal(results.children[0],first);first.dispatchEvent(new Event('click'));await new Promise(resolve=>setImmediate(resolve));assert.equal(searches,1);assert.equal(picked,'a');}finally{controller.abort();globalThis.document=oldDocument;globalThis.fetch=oldFetch;}
});
