import {WATER_BOTTLE_ART} from './water-bottle-art.mjs';
export const WATER_INITIAL=13;
export const WATER_ITIL='PDG103-BOT-01';
export const WATER_MODEL=new URL('../../inventario/assets/catalog/50/good.glb',import.meta.url).href;
export const WATER_VIEW={yaw:-57,pitch:-30,fov:65};
// Basket top in the original 8192 × 4096 Matrix capture (sphere X = -3°).
export const WATER_CORNERS=[{yaw:-49.06811,pitch:-18.57274},{yaw:-68.63336,pitch:-19.45411},{yaw:-67.749,pitch:-33.71462},{yaw:-48.35783,pitch:-32.84074}];
export function waterQuantity(basket){return Math.min(WATER_INITIAL,Math.max(0,basket?.lines?.find(l=>l.id==='water')?.quantity||0));}
export function waterRemaining(basket){return WATER_INITIAL-waterQuantity(basket);}
export function occupiedWaterSlots(basket){const count=waterQuantity(basket),used=[...new Set((Array.isArray(basket?.waterSlots)?basket.waterSlots:[]).filter(n=>Number.isInteger(n)&&n>=0&&n<WATER_INITIAL))].slice(0,count);for(let i=0;used.length<count;i++)if(!used.includes(i))used.push(i);return used;}
export function waterOfferSVG(remaining,language='es',orientation='landscape'){
 if(!Number.isInteger(remaining)||remaining<0||remaining>=WATER_INITIAL)throw Error('Invalid water offer quantity');
 const en=language==='en',headline=remaining===0?(en?'Water sold out':'Agua agotada'):(en?'Only '+remaining+' bottles left':'Solo nos quedan '+remaining+' botellas');
 const subtitle=en?'So enjoy 10% off your water':'Por eso, un 10% de descuento en tu agua';
 if(orientation==='portrait')return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="1280" viewBox="0 0 720 1280"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#087b65"/><stop offset="1" stop-color="#003b32"/></linearGradient></defs><rect width="720" height="1280" fill="url(#g)"/><text x="360" y="90" text-anchor="middle" fill="#c3efdd" font-family="Arial,sans-serif" font-size="28" letter-spacing="4">STARBUCKS</text><text x="360" y="145" text-anchor="middle" fill="#c3efdd" font-family="Arial,sans-serif" font-size="24">SOLÁN DE CABRAS</text><g text-anchor="middle" font-family="Arial,sans-serif" fill="white"><text x="360" y="245" font-size="44" font-weight="700">${remaining===0?(en?'Water sold out':'Agua agotada'):(en?'Only '+remaining+' bottles left':'Solo nos quedan')}</text>${remaining>0&&!en?`<text x="360" y="310" font-size="52" font-weight="700">${remaining} botellas</text>`:''}<text x="360" y="480" font-size="156" font-weight="800" fill="#d9ffc3">${remaining===0?'0':'−10%'}</text><text x="360" y="555" font-size="32">${remaining===0?(en?'Ask us about':'Pregúntanos por'):(en?'So enjoy 10% off':'Por eso, un 10%')}</text><text x="360" y="600" font-size="32">${remaining===0?(en?'another drink':'otra bebida'):(en?'your water':'de descuento en tu agua')}</text></g><image href="${WATER_BOTTLE_ART}" x="240" y="650" width="240" height="400"/><text x="360" y="1150" text-anchor="middle" fill="#c3efdd" font-family="Arial,sans-serif" font-size="23">${en?'While supplies last':'Hasta agotar existencias'}</text><text x="360" y="1200" text-anchor="middle" fill="#c3efdd" font-family="Arial,sans-serif" font-size="20">${en?'Digital twin promotion':'Promoción del gemelo digital'}</text></svg>`;
 return `<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720"><defs><radialGradient id="g"><stop stop-color="#087b65"/><stop offset="1" stop-color="#003b32"/></radialGradient></defs><rect width="1280" height="720" fill="url(#g)"/><circle cx="1120" cy="90" r="260" fill="#b7e9dc" opacity=".08"/><text x="80" y="100" fill="#c3efdd" font-family="Arial,sans-serif" font-size="30" letter-spacing="6">STARBUCKS · SOLÁN DE CABRAS</text><text x="80" y="225" fill="white" font-family="Arial,sans-serif" font-size="58" font-weight="700">${headline}</text><text x="76" y="440" fill="#d9ffc3" font-family="Arial,sans-serif" font-size="200" font-weight="800">${remaining===0?'0':'−10%'}</text><text x="80" y="530" fill="white" font-family="Arial,sans-serif" font-size="40">${remaining===0?(en?'Ask us about another drink':'Pregúntanos por otra bebida'):subtitle}</text><image href="${WATER_BOTTLE_ART}" x="1000" y="270" width="200" height="340"/><text x="80" y="650" fill="#c3efdd" font-family="Arial,sans-serif" font-size="24">${en?'Digital twin promotion · While supplies last':'Promoción del gemelo digital · Hasta agotar existencias'}</text></svg>`;
}
export function waterOfferOrientation(id){return id==='starbucks-ipad-01'?'landscape':'portrait';}
export function waterOfferURL(remaining,language,orientation){return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(waterOfferSVG(remaining,language,orientation));}
