import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {ADAPTERS,projectContext,projectUrl,STARBUCKS_LOCATION} from './project-context.mjs';
const base='https://www.admira.store/admira-xp/?autostart=xtanco&lang=es&langlock=1&visual=better';
test('legacy Xtanco and Cafebrería links resolve without inventing a JTI association',()=>{assert.equal(projectContext(base).id,'estancos');assert.equal(projectContext(base,'cafeteria').id,'cafebreria');});
test('stable Starbucks venue overrides stale project identifiers',()=>{assert.equal(projectContext(base+'&project=estancos&loc='+STARBUCKS_LOCATION).id,'starbucks');});
test('project switch preserves host/language and removes previous live context',()=>{const u=new URL(projectUrl(base+'&loc=old&virtualPlayer=1&twinOrigin=old&twinSession=secret&analyzerOrigin=old#old','starbucks'));assert.equal(u.hostname,'www.admira.store');assert.equal(u.searchParams.get('lang'),'es');assert.equal(u.searchParams.get('langlock'),'1');assert.equal(u.searchParams.get('loc'),STARBUCKS_LOCATION);assert.equal(u.searchParams.get('circuit'),'alsea_starbucks');for(const key of ['visual','virtualPlayer','twinOrigin','twinSession','analyzerOrigin'])assert.equal(u.searchParams.has(key),false);assert.equal(u.hash,'');});
test('leaving Matrix cannot silently re-enter Starbucks',()=>{const u=new URL(projectUrl(base.replace('better','matrix')+'&loc='+STARBUCKS_LOCATION,'estancos'));assert.equal(u.searchParams.get('quality'),'better');assert.equal(u.searchParams.has('loc'),false);assert.equal(u.searchParams.get('autostart'),'xtanco');});
test('Cafebrería does not inherit unavailable Best quality; Xtanco keeps Best',()=>{assert.equal(new URL(projectUrl(base.replace('better','best'),'cafebreria')).searchParams.get('quality'),'better');assert.equal(new URL(projectUrl(base.replace('better','best'),'estancos')).searchParams.get('quality'),'best');});
test('unlinked projects are explicit and cannot navigate to a fake twin',()=>{assert.equal(projectContext(base+'&project=alcampo').unavailable,'alcampo');assert.throws(()=>projectUrl(base,'alcampo'),RangeError);});
test('adapters use exactly the backoffice project and circuit IDs',async()=>{const {projects}=JSON.parse(await readFile(new URL('./project-catalog.json',import.meta.url)));for(const [id,a] of Object.entries(ADAPTERS))assert.equal(projects.find(p=>p.id===id).circuit,a.circuit);assert.equal(projects.length,20);});

test('a project label cannot impersonate a linked Starbucks venue',()=>{assert.equal(projectContext(base+'&project=starbucks').unavailable,'starbucks');assert.equal(projectContext(base+'&project=starbucks&loc=unknown').id,'');assert.equal(projectContext(base+'&project=cafebreria','xtanco').id,'estancos');});
