(function(root){'use strict';const doc=root.document;if(!doc)return;
 const input=doc.getElementById('videoPrompt'),label=doc.getElementById('videoPromptLabel'),note=doc.getElementById('videoPromptNote'),status=doc.getElementById('videoPromptStatus'),login=doc.getElementById('videoPromptLogin'),button=doc.querySelector('[data-xp-do="videoGen"]'),preview=doc.getElementById('videoPreview');
 let busy=false,phase='idle',stock=null;const draftKey='xpace-video-login-draft';
 try{const draft=root.sessionStorage.getItem(draftKey);if(input)input.value=draft||root.XpaceMedia.pending('video')?.payload.text||'';root.sessionStorage.removeItem(draftKey);}catch(_){}
 function render(){const en=doc.documentElement.lang==='en';label.textContent=en?'What do you want to advertise?':'Qué quieres anunciar';input.placeholder=en?'Describe the advertising video you want to create…':'Describe el vídeo del producto, oferta o anuncio…';button.textContent=en?'✨ Generate video (Grok)':'✨ Generar vídeo (Grok)';note.textContent='Grok · 8 s · 16:9 · 720p · Stock · '+(root.XpaceAccess?.active()?(en?'Session active.':'Sesión activa.'):(en?'Connect your Admira account.':'Conecta tu cuenta de Admira.'));const messages={idle:en?'Write your advertising brief, then generate the video.':'Escribe lo que quieres anunciar y genera el vídeo.',empty:en?'Write what you want to advertise first.':'Escribe primero qué quieres anunciar.',generating:en?'Preparing the video…':'Preparando el vídeo…',pending:en?'Grok is generating your video…':'Grok está generando tu vídeo…',archiving:en?'Saving to Stock…':'Guardando en Stock…',auth:en?'Sign in to generate the video.':'Inicia sesión para generar el vídeo.',error:en?'Could not complete the video. Retry to recover the same job.':'No se pudo completar el vídeo. Reintenta para recuperar el mismo trabajo.',done:en?'Video saved to Stock.':'Vídeo guardado en Stock.'};status.textContent=messages[phase]||messages.error;status.dataset.phase=phase;if(stock)status.textContent+=' '+(stock.num?'#'+stock.num:'');button.disabled=busy;button.setAttribute('aria-busy',String(busy));login.hidden=phase!=='auth';login.textContent=en?'Sign in':'Iniciar sesión';login.href='/auth/login?return_to='+encodeURIComponent(root.location.pathname+root.location.search);}
 async function generate(){if(busy)return;const text=input.value.trim();if(!text){phase='empty';render();input.focus();return;}busy=true;phase='generating';render();try{const saved=root.XpaceMedia.pending('video');const payload=saved&&saved.payload.text===text?saved.payload:{text,language:doc.documentElement.lang==='en'?'en':'es'};const result=await root.XpaceMedia.generate('video',payload,{onProgress(value){phase=value;render();}});stock=result.stock;root.XpaceMedia.link('video',stock);preview.src=stock.url;preview.hidden=false;preview.load();phase='done';}catch(e){phase=e.code==='auth'?'auth':'error';}finally{busy=false;render();}}
 button.addEventListener('click',generate);login.addEventListener('click',()=>{try{root.sessionStorage.setItem(draftKey,input.value);}catch(_){}});for(const event of ['keydown','keyup','keypress'])input.addEventListener(event,e=>e.stopPropagation());
 new root.MutationObserver(render).observe(doc.documentElement,{attributes:true,attributeFilter:['lang']});root.addEventListener('xpace:session',render);render();if(root.XpaceMedia.pending('video'))generate();
})(typeof window!=='undefined'?window:globalThis);
