import * as T from '../../admira-xp/scripts/premium-three.mjs';
import {createLifeRenderer} from '../../admira-xp/scripts/life-renderer.mjs';
import {createImportedBridge} from '../../admira-xp/scripts/imported-space.mjs';
import {mountDistribuit} from '../../admira-xp/scripts/distribuit-ui.mjs';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),en=params.get('lang')==='en',t=(es,english)=>en?english:es;
if(params.get('embed')==='1')document.documentElement.classList.add('embed');
document.documentElement.lang=en?'en':'es';
$('store-stage').querySelector('canvas').setAttribute('aria-label',t('Sneakers Store 3D · arrastra para girar y rueda para ampliar','Sneakers Store 3D · drag to orbit and scroll to zoom'));$('inventory-edit').textContent=t('Distribuir','Distribute');$('manage-playlist').textContent=t('Gestionar en admira.biz ↗','Manage in admira.biz ↗');$('manage-playlist').href='https://www.admira.biz/demo/?lang='+(en?'en':'es');
$('scene-kind').textContent=t('Escena 3D de demostración','Demonstration 3D scene');$('show-playlist').textContent=t('Ver pantalla','View screen');$('close-playlist').setAttribute('aria-label',t('Cerrar','Close'));$('close-inventory').setAttribute('aria-label',t('Cerrar inventario','Close inventory'));$('inventory-title').textContent=t('Inventario','Inventory');$('inventory-note').textContent=t('Mobiliario de demostración. Distribución editable guardada en este navegador; dimensiones interpretativas, pendientes de medición.','Demonstration furniture. Editable layout saved in this browser; interpretative dimensions awaiting measurement.');
const root=new T.Group(),actors=new T.Group(),scene=new T.Scene(),resources=new Set(),objects=new Map();
scene.background=new T.Color('#0d1920');scene.add(root,actors);
const own=x=>(resources.add(x),x),mat=(color,extra={})=>own(new T.MeshStandardMaterial({color,roughness:.55,metalness:.12,...extra}));
const mint=mat('#31eb86'),black=mat('#131c23'),stone=mat('#697277'),wood=mat('#b29876'),white=mat('#e3e7dc'),pink=mat('#e15e87'),blue=mat('#52a3e3');
function box(w,h,d,m,x=0,y=0,z=0){const mesh=new T.Mesh(own(new T.BoxGeometry(w,h,d)),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;return mesh;}
function label(text,w,h,color='#35ed88'){const c=document.createElement('canvas');c.width=1024;c.height=256;const cx=c.getContext('2d');cx.fillStyle='#101a20';cx.fillRect(0,0,c.width,c.height);cx.fillStyle=color;cx.font='bold 90px system-ui';cx.textAlign='center';cx.textBaseline='middle';cx.fillText(text,512,128,980);const texture=own(new T.CanvasTexture(c));texture.colorSpace=T.SRGBColorSpace;return new T.Mesh(own(new T.PlaneGeometry(w,h)),own(new T.MeshBasicMaterial({map:texture,side:T.DoubleSide,toneMapped:false})));}
const layout=[];
function item(id,name,col,row,w,d,builder,{locked=false,y=0}={}){const group=new T.Group();builder(group);const data={id,type:'custom',source:'SneakerStore',label:name,col,row,rot:0,sx:1,sy:1,fp:[w,d],locked,nativeFixed:locked,solid:!locked,inventoryId:'sneakerstore:'+id};group.userData.item=data;group.position.set(col,y,row);group.userData.baseY=y;root.add(group);objects.set(id,group);layout.push(data);return group;}
item('floor',t('Suelo','Floor'),0,0,6,10,g=>g.add(box(6,.12,10,stone,3,-.06,5)),{locked:true});
item('back-wall',t('Pared de fondo','Back wall'),0,9.9,6,.1,g=>{g.add(box(6,3.2,.12,black,3,1.6,0));const l=label('SNEAKERS STORE',4.6,.65);l.position.set(3,2.65,-.08);l.rotation.y=Math.PI;g.add(l);},{locked:true});
item('side-wall',t('Pared lateral','Side wall'),0,0,.12,10,g=>g.add(box(.12,3.2,10,black,0,1.6,5)),{locked:true});
for(let i=1;i<10;i++){const line=box(6,.003,.018,black,3,.004,i);root.add(line);}
function shoe(g,x,y,z,color,rotation=0){const s=new T.Group();s.position.set(x,y,z);s.rotation.y=rotation;const sole=box(.42,.06,.18,white,0,.03,0),upper=box(.32,.12,.17,color,-.035,.1,0);upper.rotation.z=-.13;s.add(sole,upper,box(.12,.12,.15,color,-.15,.16,0));for(let l=0;l<4;l++)s.add(box(.015,.012,.15,white,-.04+l*.035,.18,0));g.add(s);}
for(let n=0;n<3;n++)item('rack-'+n,t('Expositor de zapatillas ','Shoe display ')+(n+1),.12,1+n*2.5,1,2.1,g=>{g.add(box(.7,2.7,.07,wood,.35,1.35,1.05));for(let r=0;r<4;r++){g.add(box(.95,.055,2.1,black,.475,.45+r*.55,1.05));for(let j=0;j<3;j++)shoe(g,.5,.48+r*.55,.35+j*.65,[mint,pink,blue,white][(r+j+n)%4],Math.PI/2);}g.add(box(.03,2.65,.03,mint,.95,1.35,.03));});
for(let n=0;n<2;n++)item('island-'+n,t('Mesa de colección ','Collection table ')+(n+1),2,2+n*3.2,2,1.1,g=>{g.add(box(2,.12,1.1,wood,1,.85,.55),box(.12,.8,.8,black,.2,.4,.55),box(.12,.8,.8,black,1.8,.4,.55));for(let j=0;j<3;j++)shoe(g,.4+j*.6,.92,.55,[mint,pink,blue][j]);});
item('bench',t('Banco de prueba','Fitting bench'),4.7,2.7,.8,2,g=>g.add(box(.8,.45,2,wood,.4,.225,1),box(.75,.1,1.95,black,.4,.5,1)));
item('counter',t('Mostrador','Checkout counter'),3.8,8,1.7,.8,g=>{g.add(box(1.7,1.1,.8,wood,.85,.55,.4),box(1.8,.08,.9,black,.85,1.14,.4),box(.3,.03,.22,black,1.1,1.2,.4));const l=label('SANTA ROSA 19',1.3,.28);l.position.set(.85,.8,-.015);l.rotation.y=Math.PI;g.add(l);});
const video=$('store-video'),videoTexture=own(new T.VideoTexture(video));videoTexture.colorSpace=T.SRGBColorSpace;
const screen=item('screen',t('Pantalla virtual · playlist','Virtual screen · playlist'),2.25,9.65,1.2,.2,g=>{g.add(box(1.3,2,.14,black,.65,1.3,.1));const mesh=new T.Mesh(own(new T.PlaneGeometry(1.12,1.78)),own(new T.MeshBasicMaterial({map:videoTexture,side:T.DoubleSide,toneMapped:false})));mesh.rotation.y=Math.PI;mesh.position.set(.65,1.3,.018);mesh.userData.screenTarget='sneakers-store-santa-rosa-19-screen';g.add(mesh);});
const hemisphere=new T.HemisphereLight('#c8f9df','#182730',2.7),sun=new T.DirectionalLight('#ffffff',4);sun.position.set(5,12,4);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-10;sun.shadow.camera.right=10;sun.shadow.camera.top=12;sun.shadow.camera.bottom=-12;scene.add(hemisphere,sun);
let viewer,bridge,editor,playlist,index=0,raf=0,disposed=false,mediaTimer;
function apply(next){for(const data of next.layout){const g=objects.get(data.id);if(!g)continue;g.userData.item=data;g.visible=!data.hidden;g.position.set(data.col,g.userData.baseY,data.row);g.rotation.y=-data.rot*Math.PI/2;g.scale.set(data.sx,data.sy,data.sx);}for(const [id,g]of objects)if(!next.layout.some(i=>i.id===id))g.visible=false;}
bridge=createImportedBridge({roomId:'sneakers-store-santa-rosa-19',cols:6,rows:10,layout,onSave:next=>{apply(next);viewer?.update({...next,wallHeight:3.2,actors:[]});renderInventory();}});apply(bridge.read());
function status(text){$('store-status').textContent=text;}
try{viewer=createLifeRenderer({canvas:document.querySelector('canvas'),snapshot:{...bridge.read(),wallHeight:3.2,actors:[]},stockCamera:true,sceneFactory:snapshot=>{let state=snapshot;return {scene,world:root,actors,get snapshot(){return state;},update:next=>{state=next;apply(next);},animate:()=>{},refreshMedia:()=>{},screenPreviewIds:[],setLighting:mode=>{hemisphere.intensity=mode==='night'?.8:2.7;sun.intensity=mode==='night'?1.2:4;},dispose:()=>resources.forEach(r=>r.dispose())};},onSelect:data=>{if(editor){editor.select(data);return;}if(data?.item?.id==='screen')openPlaylist();else if(data?.item){status(data.item.label+' · '+t('/distribuir para editar','/distribuir to edit'));}}});viewer.preset('home');viewer.rotate(-Math.PI/(2*.18));const resize=new ResizeObserver(()=>{const r=$('store-stage').getBoundingClientRect();viewer.resize(r.width,r.height);});resize.observe($('store-stage'));const draw=now=>{if(disposed)return;viewer.render(now);raf=requestAnimationFrame(draw);};raf=requestAnimationFrame(draw);window.addEventListener('pagehide',()=>{disposed=true;cancelAnimationFrame(raf);clearInterval(mediaTimer);resize.disconnect();editor?.dispose();bridge.dispose?.();video.pause();video.removeAttribute('src');video.load();viewer.dispose();},{once:true});}catch(e){status(t('No se pudo abrir la escena: ','Could not open the scene: ')+e.message);}
function openPlaylist(){if(!$('playlist-dialog').open)$('playlist-dialog').showModal();video.play().catch(()=>{});}
function edit(){if(!viewer)return;if(editor){editor.dispose();editor=null;viewer.setEditor(null);return;}editor=mountDistribuit({dialog:$('store-stage'),viewer,bridge,lang:en?'en':'es',onClose:()=>{editor?.dispose();editor=null;viewer.setEditor(null);}});viewer.setEditor(editor);$('store-stage').querySelector('[data-action="catalog"]').hidden=true;}
function renderInventory(){$('inventory-list').replaceChildren(...bridge.read().layout.filter(i=>!i.hidden).map(i=>{const li=document.createElement('li');li.textContent=i.label+' · '+i.id;return li;}));}
function tracks(){const list=$('tracks');list.replaceChildren();playlist.tracks.forEach((track,i)=>{const li=document.createElement('li'),b=document.createElement('button');b.textContent=track.title;b.setAttribute('aria-current',String(i===index));b.onclick=()=>play(i);li.append(b);list.append(li);});$('playlist-title').textContent=playlist.title;$('playlist-status').textContent=playlist.id+' · '+t('revisión ','revision ')+playlist.revision;}
function play(i){if(!playlist?.tracks.length)return;index=i;video.src=playlist.tracks[i].url;video.play().then(()=>status(t('Pantalla conectada · ','Screen connected · ')+playlist.tracks[i].title)).catch(()=>status(t('Playlist conectada · pulsa Ver pantalla para reproducir','Playlist connected · click View screen to play')));tracks();}
video.addEventListener('ended',()=>{if(index+1<playlist.tracks.length)play(index+1);else if(playlist.loop)play(0);});video.addEventListener('error',()=>{const message=t('Error de vídeo · abre la playlist para reintentar.','Video error · open the playlist to retry.');status(message);$('playlist-status').textContent=message;});
async function loadPlaylist(){try{const r=await fetch('https://www.admira.biz/api/demo-global?project=sneakers-store',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();if(!data.playlist){status(t('Escena lista · playlist pendiente en admira.biz/demo/','Scene ready · playlist pending at admira.biz/demo/'));return;}const changed=playlist?.revision!==data.playlist.revision;playlist=data.playlist;if(changed)play(0);}catch(e){status(t('Escena lista · conexión de playlist pendiente: ','Scene ready · playlist connection pending: ')+e.message);}}
// Foto real: la tienda fotografiada con sus 3 pantallas virtuales por 4 esquinas (admira-xp/scripts/xpacio-foto-player.mjs).
let foto=null;async function openFoto(modo='live'){const host=$('foto-real');if(foto){foto.setModo(modo);host.hidden=false;return foto;}host.hidden=false;const {montarFotoPlayer}=await import('../../admira-xp/scripts/xpacio-foto-player.mjs?v=20261009-esquinas-1');foto=await montarFotoPlayer(host,{xpacio:'sneakers-store-santa-rosa-19',lang:en?'en':'es',modo,alCerrar:closeFoto});return foto;}
function closeFoto(){foto?.destruir();foto=null;$('foto-real').hidden=true;const u=new URL(location.href);if(u.searchParams.has('vista')){u.searchParams.delete('vista');u.searchParams.delete('modo');history.replaceState(null,'',u.href);}}
window.XpaceFotoReal={xpacio:'sneakers-store-santa-rosa-19',abrir:openFoto,cerrar:closeFoto};
$('show-foto').textContent=t('Foto real','Real photo');$('show-foto').onclick=()=>openFoto('live');
if(params.get('vista')==='foto')openFoto(params.get('modo')==='demo'?'demo':'live');
$('show-playlist').onclick=openPlaylist;$('close-playlist').onclick=()=>$('playlist-dialog').close();$('close-inventory').onclick=()=>$('inventory-dialog').close();$('inventory-edit').onclick=()=>{$('inventory-dialog').close();edit();};
const actions={'sneakers-foto':()=>openFoto('live'),'sneakers-playlist':openPlaylist,'sneakers-edit':edit,'sneakers-home':()=>{viewer?.preset('home');viewer?.rotate(-Math.PI/(2*.18));},'sneakers-front':()=>{viewer?.preset('front');viewer?.rotate(-Math.PI/.18);},'sneakers-floor':()=>viewer?.preset('floor'),'sneakers-plus':()=>viewer?.zoomBy(1.15),'sneakers-minus':()=>viewer?.zoomBy(1/1.15),'sneakers-day':()=>viewer?.setLighting('day'),'sneakers-night':()=>viewer?.setLighting('night'),'sneakers-inventory':()=>{renderInventory();$('inventory-dialog').showModal();}};
document.addEventListener('click',e=>{const a=e.target.closest('[id]');actions[a?.id]?.();});
function register(){if(!window.XpaceShell?.registerVerb){setTimeout(register,100);return;}window.XpaceShell.registerVerb({id:'distribuir',es:'Editar mobiliario de Sneakers Store',en:'Edit Sneakers Store furniture',run:()=>{edit();return t('Editor de Sneakers Store','Sneakers Store editor');}});window.XpaceShell.registerVerb({id:'inventario',es:'Inventario de Sneakers Store',en:'Sneakers Store inventory',run:()=>{actions['sneakers-inventory']();return 'SneakerStore';}});}
window.addEventListener('admira:languagechange',e=>{const next=e.detail?.lang;if(['es','en'].includes(next)&&next!==(en?'en':'es')){const u=new URL(location.href);u.searchParams.set('lang',next);location.assign(u.href);}});
register();status(t('Escena lista · conectando playlist…','Scene ready · connecting playlist…'));loadPlaylist();mediaTimer=setInterval(loadPlaylist,15000);
