'use strict';
// Local presentation only. No remote API, tracking, checkout or copied third-party scripts.
const products=[
 {id:'chocolate',name:'Chocolate Hazelnut',type:'aroma',image:'chocolate.jpg',description:'Una pausa de café con notas de chocolate y avellana.',roast:'Aromatizado'},
 {id:'ristretto',name:'Ristretto',type:'intenso',image:'ristretto.jpg',description:'Para quienes prefieren un café corto y de carácter intenso.',roast:'Intenso'},
 {id:'nespresso',name:'Café para tu Nespresso',type:'medio',image:'nespresso.jpg',description:'Explora el café en cápsulas y encuentra tu momento favorito.',roast:'Medio'}];
const recipes=[
 {id:'mocha',name:'Caffè Mocha',image:'mocha.png',description:'Café, leche y chocolate para disfrutar en casa.',ingredients:['Un espresso','150 ml de leche','Chocolate al gusto'],steps:['Prepara tu espresso favorito.','Mezcla el chocolate con el café caliente.','Añade leche caliente y termina con espuma.']},
 {id:'vanilla',name:'Vanilla Latte',image:'vanilla.png',description:'Una combinación suave de espresso, leche y vainilla.',ingredients:['Un espresso','150 ml de leche','Vainilla al gusto'],steps:['Prepara un espresso en una taza.','Añade la vainilla y mezcla.','Calienta la leche, crea espuma y viértela sobre el café.']},
 {id:'iced',name:'Iced Caramel Latte',image:'iced.png',description:'Tu momento de café frío con un toque de caramelo.',ingredients:['Un espresso','150 ml de leche fría','Hielo','Caramelo al gusto'],steps:['Llena un vaso de hielo.','Añade la leche y el caramelo.','Vierte el espresso y mezcla antes de disfrutar.']}];
const content=document.querySelector('#content'),menu=document.querySelector('#menu'),menuToggle=document.querySelector('#menuToggle'),search=document.querySelector('#search');
const card=(item,route)=>`<a class="card" href="#${route}/${item.id}"><img src="assets/${item.image}" alt="${item.name}" loading="lazy"><div><h3>${item.name}</h3><p>${item.description}</p><p aria-hidden="true">Descubrir →</p></div></a>`;
let filter='all';
function render(){
 const [rawRoute,id='']=location.hash.slice(1).split('/'),route=rawRoute||'home';
 menu.hidden=true;menuToggle.setAttribute('aria-expanded','false');
 if(route==='home')content.innerHTML=`<section class="hero"><img src="assets/hero.jpg" alt="Café Starbucks Chocolate Hazelnut"><div><p class="eyebrow">Chocolate · Avellana</p><h1>Tu próximo momento de café</h1><p>Descubre sabores y recetas para disfrutar Starbucks en casa.</p><a class="pill" href="#products/chocolate">Descubre más</a></div></section><section class="intro"><p class="eyebrow">Starbucks at Home</p><h2>Elige tu café. Hazlo tuyo.</h2><p>Recorre nuestra selección y prepara tu bebida favorita.</p><div class="cards">${products.map(x=>card(x,'products')).join('')}</div><a class="pill" href="#finder">Encuentra tu café</a><h2>Recetas para cada momento</h2><div class="cards">${recipes.map(x=>card(x,'recipes')).join('')}</div></section>`;
 else if(route==='products'&&id){const p=products.find(x=>x.id===id);if(!p){location.hash='products';return;}content.innerHTML=`<section class="page"><a class="back" href="#products">← Nuestros cafés</a><img class="detail-image" src="assets/${p.image}" alt="${p.name}"><p class="eyebrow">${p.roast}</p><h1>${p.name}</h1><p>${p.description}</p><a class="pill" href="#recipes">Ideas para prepararlo</a></section>`;}
 else if(route==='products')content.innerHTML=`<section class="page"><p class="eyebrow">Descubre</p><h1>Nuestros cafés</h1><div class="filters" aria-label="Filtrar cafés">${[['all','Todos'],['aroma','Aromatizados'],['medio','Medio'],['intenso','Intenso']].map(([value,label])=>`<button data-filter="${value}" aria-pressed="${filter===value}">${label}</button>`).join('')}</div><div class="cards">${products.filter(p=>filter==='all'||p.type===filter).map(x=>card(x,'products')).join('')}</div></section>`;
 else if(route==='recipes'&&id){const r=recipes.find(x=>x.id===id);if(!r){location.hash='recipes';return;}content.innerHTML=`<section class="page"><a class="back" href="#recipes">← Todas las recetas</a><img class="detail-image" src="assets/${r.image}" alt="${r.name}"><h1>${r.name}</h1><p>${r.description}</p><h2>Qué necesitas</h2><ul>${r.ingredients.map(x=>`<li>${x}</li>`).join('')}</ul><h2>Preparación de ejemplo</h2><ol>${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol></section>`;}
 else if(route==='recipes')content.innerHTML=`<section class="page"><p class="eyebrow">Prepáralo en casa</p><h1>Recetas de café</h1><div class="cards">${recipes.map(x=>card(x,'recipes')).join('')}</div></section>`;
 else if(route==='finder')content.innerHTML=`<section class="page finder"><p class="eyebrow">Tu momento, tu café</p><h1>Encuentra tu café</h1><label for="taste">¿Qué sabor te apetece?</label><select id="taste"><option value="medio">Equilibrado y suave</option><option value="aroma">Chocolate y avellana</option><option value="intenso">Corto e intenso</option></select><button class="pill" id="recommend">Ver mi recomendación</button><div id="recommendation" aria-live="polite"></div></section>`;
 else if(route==='search'){content.innerHTML='<section class="page"><h1>Resultados de búsqueda</h1><div class="cards" id="results"></div></section>';const query=new URLSearchParams(id).get('q')||'';const found=[...products.map(x=>({...x,route:'products'})),...recipes.map(x=>({...x,route:'recipes'}))].filter(x=>(x.name+' '+x.description).toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')));document.querySelector('#results').innerHTML=found.length?found.map(x=>card(x,x.route)).join(''):'<p>No encontramos ese café. Prueba con «latte» o explora el catálogo.</p>';}
 else content.innerHTML='<section class="page"><p class="eyebrow">Desde Seattle, 1971</p><h1>Una historia alrededor del café</h1><p>Esta experiencia reúne sabores, ideas y momentos de café en una demo para Alsea.</p><h2>Explora a tu ritmo</h2><p>Descubre cafés, prueba el selector y consulta recetas de ejemplo. Para conocer información actualizada de la marca, visita la web oficial.</p><a class="pill" href="#products">Explorar cafés</a></section>';
 window.scrollTo(0,0);
}
menuToggle.addEventListener('click',()=>{menu.hidden=!menu.hidden;menuToggle.setAttribute('aria-expanded',String(!menu.hidden));});
document.querySelector('#searchToggle').addEventListener('click',()=>{search.hidden=!search.hidden;if(!search.hidden)document.querySelector('#query').focus();});
search.addEventListener('submit',e=>{e.preventDefault();location.hash='search/q='+encodeURIComponent(document.querySelector('#query').value.trim());search.hidden=true;});
content.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render();}if(e.target.closest('#recommend')){const p=products.find(x=>x.type===document.querySelector('#taste').value);document.querySelector('#recommendation').innerHTML=`<div class="result"><h2>Tu recomendación de demo</h2>${card(p,'products')}</div>`;}});
window.addEventListener('hashchange',()=>{render();content.focus({preventScroll:true});});render();

window.addEventListener('keydown',e=>{if(e.key==='Escape'&&window.parent!==window){window.parent.postMessage({type:'starbucks-kiosk:close'},location.origin);}});
