"""Build clothed, skinned Best visitors from MakeHuman CC0 data, in Blender.
No add-ons or downloaded code execute. Uses OBJ/MHCLO/JSON data only.
Blender coordinates X=right, -Y=forward, Z=up; GLB is +Z forward, Y up.
"""
import argparse,json,math,sys
from pathlib import Path
from collections import defaultdict
import bpy
import numpy as np
from mathutils import Vector,Quaternion

ap=argparse.ArgumentParser();ap.add_argument('--source',required=True);ap.add_argument('--output',required=True);ap.add_argument('--profile',default='male');ap.add_argument('--render',action='store_true')
a=ap.parse_args(sys.argv[sys.argv.index('--')+1:]);SRC=Path(a.source);OUT=Path(a.output);OUT.mkdir(parents=True,exist_ok=True)
PROFILE=a.profile;FEMALE='female' in PROFILE;CHILD=PROFILE.startswith('child-')
bpy.context.preferences.filepaths.save_version=0
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
sc=bpy.context.scene;sc.render.engine='CYCLES';sc.cycles.samples=16;sc.render.resolution_x=900;sc.render.resolution_y=1100;sc.render.resolution_percentage=100
sc.render.image_settings.file_format='PNG';sc.render.film_transparent=False

def obj_data(path):
 v=[];uv=[];faces=[];groups=[];g=''
 for line in Path(path).read_text().splitlines():
  s=line.split()
  if not s:continue
  if s[0]=='v':v.append(list(map(float,s[1:4])))
  elif s[0]=='vt':uv.append(list(map(float,s[1:3])))
  elif s[0]=='g':g=' '.join(s[1:])
  elif s[0]=='f':faces.append([tuple(int(i)-1 if i else -1 for i in t.split('/')) for t in s[1:]]);groups.append(g)
 return np.array(v),uv,faces,groups

BASE,BASE_UV,BASE_FACES,BASE_GROUPS=obj_data(SRC/'base.obj');V=BASE.copy()
# Optional profiles generated by official macro targets. The source OBJ keeps
# its original indices (including helpers) until rig and garments have fitted.
target_name=f"caucasian-{'female' if FEMALE else 'male'}-{'child' if CHILD else 'young'}.target"
target_file=SRC/'targets'/target_name
if not target_file.exists():raise FileNotFoundError(target_file)
for line in target_file.read_text().splitlines():
 s=line.split()
 if len(s)==4 and not line.startswith('#'):V[int(s[0])]+=np.array(list(map(float,s[1:])))

SKEL=json.load(open(SRC/'default.mhskel'));RAW_WEIGHTS=json.load(open(SRC/'default_weights.mhw'))['weights']
# Collapse deformation to 25 game bones; facial detail stays geometric.
KEEP=['root','spine05','spine03','spine01','neck01','head']
for side in ['L','R']:KEEP += [f'{n}.{side}' for n in ['clavicle','upperarm01','lowerarm01','wrist','upperleg01','lowerleg01','foot']]
MAP={}
for name in SKEL['bones']:
 key=name
 while key and key not in KEEP:key=SKEL['bones'][key]['parent']
 MAP[name]=key or 'root'
WEIGHTS=[defaultdict(float) for _ in V]
for name,rows in RAW_WEIGHTS.items():
 for i,w in rows:WEIGHTS[i][MAP[name]]+=w
for ws in WEIGHTS:
 total=sum(ws.values())
 if total:
  for b in ws:ws[b]/=total

body_indices={t[0] for f,g in zip(BASE_FACES,BASE_GROUPS) if g=='body' for t in f}
BOTTOM=min(V[i,1] for i in body_indices)
SCALE=1.70/(max(V[i,1] for i in body_indices)-BOTTOM)
def coord(p):return (float(p[0]*SCALE),float(-p[2]*SCALE),float((p[1]-BOTTOM)*SCALE))
def joint(key):return V[SKEL['joints'][key]].mean(0)

rigdata=bpy.data.armatures.new('Best visitor · 20 deformation bones');rig=bpy.data.objects.new('VisitorRig',rigdata);sc.collection.objects.link(rig);bpy.context.view_layer.objects.active=rig;rig.select_set(True);bpy.ops.object.mode_set(mode='EDIT')
for name in KEEP:
 src=SKEL['bones'][name];b=rigdata.edit_bones.new(name);b.head=coord(joint(src['head']));b.tail=coord(joint(src['tail']))
 # Extend collapsed segments to the next articulation.
 next_name={'spine05':'spine03','spine03':'spine01','spine01':'neck01','neck01':'head'}.get(name)
 for side in ['L','R']:
  for old,nxt in [('upperarm01','lowerarm01'),('lowerarm01','wrist'),('upperleg01','lowerleg01'),('lowerleg01','foot')]:
   if name==f'{old}.{side}':next_name=f'{nxt}.{side}'
 if next_name:b.tail=coord(joint(SKEL['bones'][next_name]['head']))
 if (b.tail-b.head).length<.005:b.tail=b.head+Vector((0,0,.03))
 # Reproducible global-axis alignment; animation uses converted world axes.
 b.align_roll(Vector((0,1,0)))
for name in KEEP:
 p=SKEL['bones'][name]['parent']
 while p and p not in KEEP:p=SKEL['bones'][p]['parent']
 if p:rigdata.edit_bones[name].parent=rigdata.edit_bones[p]
bpy.ops.object.mode_set(mode='OBJECT');rig.select_set(False)
rig['profile']=PROFILE;rig['sourceLicense']='CC0';rig['units']='uncalibrated_grid_units';rig['forward']='+Z in glTF';rig['height']=1.70

IMAGES={}
def image(path,maxsize=1024,noncolor=False):
 path=Path(path);key=(str(path),noncolor)
 if key not in IMAGES:
  im=bpy.data.images.load(str(path),check_existing=False)
  if noncolor:im.colorspace_settings.name='Non-Color'
  if max(im.size)>maxsize:factor=maxsize/max(im.size);im.scale(round(im.size[0]*factor),round(im.size[1]*factor))
  # Persist resized pixels before packing: exporters can otherwise reuse the
  # original file's compressed bytes (e.g. a 2048 normal after a 1024 resize).
  opaque=not noncolor and not any(k in str(path) for k in ['hair/','eyebrows/','eyelashes/'])
  im.file_format='JPEG' if opaque else 'PNG'
  baked=OUT/'textures';baked.mkdir(exist_ok=True)
  im.filepath_raw=str(baked/(path.stem+('-data' if noncolor else '')+('.jpg' if opaque else '.png')))
  im.save();im.pack();IMAGES[key]=im
 return IMAGES[key]

def mat(name,mhmat=None,part=None,base=None,normal=None,alpha=False,flat=False):
 data={}
 if mhmat:
  for l in Path(mhmat).read_text().splitlines():
   s=l.split()
   if s and not l.startswith('#'):data[s[0]]=' '.join(s[1:])
  folder=Path(mhmat).parent
  if not base and data.get('diffuseTexture') and not flat:base=folder/data['diffuseTexture']
  if not normal and data.get('normalmapTexture'):normal=folder/data['normalmapTexture']
 m=bpy.data.materials.new(name);m.use_nodes=True;m['personPart']=part or name
 bs=m.node_tree.nodes.get('Principled BSDF');bs.inputs['Base Color'].default_value=(.6,.6,.6,1) if flat else (1,1,1,1);bs.inputs['Roughness'].default_value=.68 if 'skin' in name else .82
 if 'eye' in name:bs.inputs['Roughness'].default_value=.24
 if 'skin' in name:bs.inputs['Subsurface Weight'].default_value=.075
 def tex(img):
  n=m.node_tree.nodes.new('ShaderNodeTexImage');n.image=img;return n
 if base and Path(base).exists():
  n=tex(image(base,1024));m.node_tree.links.new(n.outputs['Color'],bs.inputs['Base Color'])
  if alpha:m.node_tree.links.new(n.outputs['Alpha'],bs.inputs['Alpha']);m.surface_render_method='DITHERED';m.use_transparency_overlap=False
 if normal and Path(normal).exists():
  n=tex(image(normal,1024,True));nm=m.node_tree.nodes.new('ShaderNodeNormalMap');nm.inputs['Strength'].default_value=.65;m.node_tree.links.new(n.outputs['Color'],nm.inputs['Color']);m.node_tree.links.new(nm.outputs['Normal'],bs.inputs['Normal'])
 m.use_backface_culling=not alpha
 return m

SKIN=mat('skin',SRC/'system/skins'/('young_caucasian_female' if FEMALE else 'young_caucasian_male')/(('young_caucasian_female' if FEMALE else 'young_caucasian_male')+'.mhmat'))
MESHES=[]
def mesh(name,points,uv,faces,weights,mats,indices=None):
 used=sorted({t[0] for f in faces for t in f});remap={old:i for i,old in enumerate(used)}
 me=bpy.data.meshes.new(name);me.from_pydata([coord(points[i]) for i in used],[],[[remap[t[0]] for t in f] for f in faces]);me.update()
 ob=bpy.data.objects.new(name,me);sc.collection.objects.link(ob);ob.parent=rig
 for m in mats:me.materials.append(m)
 for i,p in enumerate(me.polygons):p.use_smooth=True;p.material_index=indices[i] if indices else 0
 if uv:
  layer=me.uv_layers.new(name='UVMap')
  for poly,face in zip(me.polygons,faces):
   for loop,t in zip(poly.loop_indices,face):layer.data[loop].uv=uv[t[1]] if len(t)>1 and t[1]>=0 else (0,0)
 groups={name:ob.vertex_groups.new(name=name) for name in KEEP}
 for old,new in remap.items():
  ws=weights[old];largest=sorted(ws.items(),key=lambda t:t[1],reverse=True)[:4];total=sum(max(0,w) for _,w in largest)
  if total:
   for b,w in largest:
    if w>0:groups[b].add([new],w/total,'REPLACE')
  else:groups['root'].add([new],1,'REPLACE')
 mod=ob.modifiers.new('Human skin deformation','ARMATURE');mod.object=rig;mod.use_deform_preserve_volume=True
 MESHES.append(ob);return ob

MASK=set();SOURCE_FILES=[]
def proxy(rel,part,split_clothes=False):
 path=SRC/'system'/rel;info={};refs=[];mode=None;deleted=[]
 for line in path.read_text().splitlines():
  s=line.split()
  if not s or line.startswith('#'):continue
  if s[0]=='verts':mode='verts';continue
  if s[0]=='delete_verts':mode='delete';continue
  if mode=='verts' and (s[0][0].isdigit() or s[0][0]=='-'):
   if len(s)==1:refs.append(([int(s[0])],[1.],np.zeros(3)))
   elif len(s)>=9:refs.append((list(map(int,s[:3])),list(map(float,s[3:6])),np.array(list(map(float,s[6:9])))))
  elif mode=='delete':deleted+=s
  else:info[s[0]]=' '.join(s[1:])
 i=0
 while i<len(deleted):
  start=int(deleted[i]);i+=1
  if i<len(deleted) and deleted[i]=='-':end=int(deleted[i+1]);i+=2;MASK.update(range(start,end+1))
  else:MASK.add(start)
 scales=np.ones(3)
 for axis,k in enumerate(['x_scale','y_scale','z_scale']):
  if k in info:
   i,j,d=info[k].split();scales[axis]=abs(V[int(i),axis]-V[int(j),axis])/float(d)
 p,uv,faces,_=obj_data(path.parent/info['obj_file']);fitted=[];weights=[]
 for ids,ws,offset in refs:
  fitted.append((V[ids]*np.array(ws)[:,None]).sum(0)+offset*scales)
  result=defaultdict(float)
  for i,w in zip(ids,ws):
   for b,v in WEIGHTS[i].items():result[b]+=max(0,w)*v
  weights.append(result)
 assert len(refs)==len(p),(part,len(refs),len(p));p=np.array(fitted)
 if info.get('vertexboneweights_file'):
  own_weights=json.load(open(path.parent/info['vertexboneweights_file'])).get('weights',{})
  if own_weights:
   explicit=[defaultdict(float) for _ in p]
   for bone,rows in own_weights.items():
    for vertex,weight in rows:explicit[vertex][MAP.get(bone,'root')]+=weight
   weights=[e if e else old for e,old in zip(explicit,weights)]
 if part=='shoe_upper':
  # shoes02 includes tall white socks. The full-length jeans cover those socks;
  # crop their hidden upper faces so they cannot intersect the trouser calves.
  cuff=max(joint(SKEL['bones'][f'foot.{side}']['head'])[1] for side in ['L','R'])+.35
  faces=[face for face in faces if np.mean(p[[t[0] for t in face],1])<=cuff]
 material_path=path.parent/info['material'];alpha=part in ['hair','brows','lashes']
 if split_clothes:
  bottom=mat('trousers',material_path,part='trousers');top=mat('shirt',material_path,part='shirt',flat=FEMALE)
  # Clothing outfit contains independent shirt/pants components. Height boundary
  # is between waist and belt; no logos copied to the new shirt material.
  threshold=joint(SKEL['bones']['spine05']['head'])[1]+.9
  mi=[1 if np.mean(p[[t[0] for t in f],1])>threshold else 0 for f in faces]
  if FEMALE:
   # This outfit has separate top/pants islands; classify whole garments so a
   # height threshold cannot paint an accidental band across the shirt hem.
   parents=list(range(len(p)))
   def component(i):
    while parents[i]!=i:parents[i]=parents[parents[i]];i=parents[i]
    return i
   for face in faces:
    for va,vb in zip(face,face[1:]):parents[component(va[0])]=component(vb[0])
   heights=defaultdict(lambda:-math.inf)
   for i in range(len(p)):heights[component(i)]=max(heights[component(i)],p[i,1])
   mi=[int(heights[component(f[0][0])]>threshold+1) for f in faces]
  ob=mesh(part,p,uv,faces,weights,[bottom,top],mi)
 else:ob=mesh(part,p,uv,faces,weights,[mat(part,material_path,part=part,alpha=alpha)])
 SOURCE_FILES.append(str(path.relative_to(SRC)));return ob

clothing='female_casualsuit01' if FEMALE else 'male_casualsuit01'
proxy(f'clothes/{clothing}/{clothing}.mhclo','clothes',True)
proxy('clothes/shoes02/shoes02.mhclo','shoe_upper')
hair='ponytail01' if FEMALE else 'short02'
proxy(f'hair/{hair}/{hair}.mhclo','hair')
proxy('eyes/low-poly/low-poly.mhclo','eyes')
proxy('eyebrows/eyebrow001/eyebrow001.mhclo','brows')
# Export only visible anatomical skin, never helper geometry, nor skin covered
# by garments. Occluded faces would clip through clothes while walking.
def covered_lower_body(face):
 # This wardrobe always includes full trousers and shoes. Remove occluded leg
 # skin as well as the original proxy mask to prevent calf/knee poke-through.
 ws=defaultdict(float)
 for t in face:
  for bone,weight in WEIGHTS[t[0]].items():ws[bone]+=weight/len(face)
 leg=sum(w for b,w in ws.items() if b.startswith(('upperleg','lowerleg','foot')))
 return leg>.55
faces=[f for f,g in zip(BASE_FACES,BASE_GROUPS) if g=='body' and not all(t[0] in MASK for t in f) and not covered_lower_body(f)]
mesh('skin',V,BASE_UV,faces,WEIGHTS,[SKIN])

# Motion is authored once into two looping Blender actions. Runtime only samples
# these clips at the live simulation's requested walking/idle state.
def world_rotation(bone,axis,angle):
 rest=rig.data.bones[bone].matrix_local.to_quaternion();return rest.inverted() @ Quaternion(axis,angle) @ rest
rest_pose={}
for side,sign in [('L',1),('R',-1)]:
 # Narrow the A-pose, leave a natural gap between hands and clothing.
 rest_pose[f'upperarm01.{side}']=world_rotation(f'upperarm01.{side}',(0,1,0),sign*.40)
 rest_pose[f'upperleg01.{side}']=world_rotation(f'upperleg01.{side}',(0,1,0),sign*.10)
for pb in rig.pose.bones:pb.rotation_mode='QUATERNION';pb.rotation_quaternion=rest_pose.get(pb.name,Quaternion())
# Bake the relaxed stance as bind pose so animation is editable in Blender.
bpy.context.view_layer.objects.active=rig;rig.select_set(True)
for ob in MESHES:
 bpy.context.view_layer.objects.active=ob
 for mod in list(ob.modifiers):
  if mod.type=='ARMATURE':bpy.ops.object.modifier_apply(modifier=mod.name)
bpy.context.view_layer.objects.active=rig;bpy.ops.object.mode_set(mode='POSE');bpy.ops.pose.armature_apply(selected=False);bpy.ops.object.mode_set(mode='OBJECT')
for ob in MESHES:
 mod=ob.modifiers.new('Game rig','ARMATURE');mod.object=rig
for pb in rig.pose.bones:pb.rotation_mode='QUATERNION';pb.rotation_quaternion=Quaternion()
sc.render.fps=30
for name,duration in [('Idle',90),('Walk',30)]:
 rig.animation_data_create();action=bpy.data.actions.new(name);rig.animation_data.action=action
 for frame in range(1,duration+2,2):
  t=(frame-1)/duration*math.tau
  for pb in rig.pose.bones:pb.rotation_quaternion=Quaternion();pb.location=(0,0,0)
  if name=='Walk':
   for side,off in [('L',0),('R',math.pi)]:
    sine=math.sin(t+off)
    angles=[(f'upperleg01.{side}',sine*.30),(f'lowerleg01.{side}',max(0,-sine)*.52),(f'foot.{side}',-.11*max(0,sine)),(f'upperarm01.{side}',-sine*.20),(f'lowerarm01.{side}',-.12-max(0,sine)*.10)]
    for bone,angle in angles:rig.pose.bones[bone].rotation_quaternion=world_rotation(bone,(1,0,0),angle)
   rig.pose.bones['root'].location.z=abs(math.sin(t))*.014
   rig.pose.bones['spine01'].rotation_quaternion=world_rotation('spine01',(0,0,1),math.sin(t)*.025)
  else:
   rig.pose.bones['spine01'].rotation_quaternion=world_rotation('spine01',(1,0,0),math.sin(t)*.012)
   rig.pose.bones['head'].rotation_quaternion=world_rotation('head',(0,0,1),math.sin(t)*.035)
   for side in ['L','R']:rig.pose.bones[f'lowerarm01.{side}'].rotation_quaternion=world_rotation(f'lowerarm01.{side}',(1,0,0),-.10)
  for pb in rig.pose.bones:
   pb.keyframe_insert('rotation_quaternion',frame=frame,group=pb.name)
   if pb.name=='root':pb.keyframe_insert('location',frame=frame,group=pb.name)
 action.use_fake_user=True
 # NLA tracks provide reliable names/actions to the GLTF exporter.
 track=rig.animation_data.nla_tracks.new();track.name=name;strip=track.strips.new(name,1,action)
rig.animation_data.action=None
for track in rig.animation_data.nla_tracks:track.mute=True
sc.frame_set(1)
# Static export with NLA clips; do not bake studio lighting or simulation.
bpy.ops.object.select_all(action='DESELECT');rig.select_set(True)
for ob in MESHES:ob.select_set(True)
bpy.context.view_layer.objects.active=rig
bpy.ops.wm.save_as_mainfile(filepath=str(OUT/f'{PROFILE}.blend'))
bpy.ops.export_scene.gltf(filepath=str(OUT/f'{PROFILE}.glb'),export_format='GLB',use_selection=True,export_animations=True,export_animation_mode='NLA_TRACKS',export_nla_strips=True,export_frame_range=False,export_skins=True,export_all_influences=False,export_def_bones=True,export_extras=True,export_lights=False,export_cameras=False)
manifest={'profile':PROFILE,'source':'MakeHuman CC0 + original Blender clothing/rig adaptation','license':'CC0-1.0','height':1.70,'bones':len(KEEP),'triangles':sum(sum(len(p.vertices)-2 for p in o.data.polygons) for o in MESHES),'parts':[o.name for o in MESHES],'sources':SOURCE_FILES,'animations':['Idle','Walk'],'author':'XpaceOS','measured':False}
(OUT/f'{PROFILE}.json').write_text(json.dumps(manifest,indent=2))

if a.render:
 # Studio exists only for inspection; not in the web GLB or model source file.
 for track in rig.animation_data.nla_tracks:track.mute=track.name!='Idle'
 sc.frame_set(12)
 def area(name,loc,power,size):
  d=bpy.data.lights.new(name,'AREA');d.energy=power;d.shape='DISK';d.size=size;o=bpy.data.objects.new(name,d);sc.collection.objects.link(o);o.location=loc;o.rotation_euler=(Vector((0,0,1))-o.location).to_track_quat('-Z','Y').to_euler()
 area('Key',(2,-4,4),500,4);area('Fill',(-3,-2,2),250,3);area('Rim',(2,3,3),400,2)
 sc.world.color=(.28,.28,.28)
 bpy.ops.mesh.primitive_plane_add(size=200);floor=bpy.context.object;floor.name='STUDIO';floor.location.z=-.005;m=mat('studio');m.node_tree.nodes['Principled BSDF'].inputs['Base Color'].default_value=(.11,.14,.15,1);floor.data.materials.append(m)
 bpy.ops.object.camera_add(location=(2.9,-5.7,2.35));camera=bpy.context.object;camera.rotation_euler=(Vector((0,0,.92))-camera.location).to_track_quat('-Z','Y').to_euler();camera.data.type='ORTHO';camera.data.ortho_scale=2.18;sc.camera=camera;sc.view_settings.view_transform='AgX';sc.render.filepath=str(OUT/f'{PROFILE}.png');bpy.ops.render.render(write_still=True)
print('BUILT',PROFILE,json.dumps(manifest))
