// Presentation only: canonical records, IDs and exported data remain unchanged.
const names={
 "Pilar": "Pillar",
 "Mostrador": "Counter",
 "Estantería": "Shelf",
 "Botellero": "Bottle rack",
 "Lotería": "Lottery stand",
 "Vending": "Vending machine",
 "Revistero": "Magazine rack",
 "Escritorio": "Desk",
 "Puerta": "Door",
 "Planta": "Plant",
 "Lámpara": "Floor lamp",
 "Alfombra": "Rug",
 "Pantalla TFT": "TFT screen",
 "Mupi Metahuman": "MetaHuman display",
 "Tablet Satisf.": "Satisfaction tablet",
 "Aroma": "Aroma diffuser",
 "Mesa DJ · Audio": "DJ desk · Audio",
 "Gestor Turnos": "Queue kiosk",
 "Barra de preparación Starbucks": "Starbucks preparation counter",
 "Mostrador de caja Starbucks": "Starbucks checkout counter",
 "Vitrina Starbucks": "Starbucks display case",
 "Estantería de tazas y café Starbucks": "Starbucks mug and coffee shelf",
 "Mesa redonda Starbucks": "Starbucks round table",
 "Silla Starbucks": "Starbucks chair",
 "Botellero Solán de Cabras Starbucks": "Starbucks Solán de Cabras bottle rack",
 "Librería interactiva de Cafebrería": "Cafebrería interactive bookcase",
 "Barra de preparación · Espresso": "Preparation counter · Espresso",
 "Caja · TPV": "Checkout · POS",
 "Vitrina · Bollería y bebidas": "Display case · Pastries and drinks",
 "Tazas · Café en grano": "Mugs · Coffee beans",
 "Mesa redonda": "Round table",
 "Mesa redonda 1": "Round table 1",
 "Mesa redonda 2": "Round table 2",
 "Altavoz · hilo musical": "Speaker · Background music",
 "Starbucks · TPV / POS": "Starbucks · POS",
 "Mostrador+Caja+PC": "Counter + Checkout + PC",
 "Caja+TPV": "Checkout + POS",
 "Aroma Fresco": "Fresh aroma",
 "Frescos": "Fresh produce",
 "Helados y Comida": "Ice cream and food",
 "Hilo Musical": "Background music",
 "Impulso": "Impulse display",
 "LED Ofertas": "LED offers",
 "Lámpara pie": "Floor lamp",
 "Mesa DJ": "DJ desk",
 "Máquina olores": "Aroma diffuser",
 "Oficina": "Office",
 "Panadería": "Bakery",
 "Pasillo Seco": "Dry goods aisle",
 "Tablet Satisfacción": "Satisfaction tablet",
 "Tablet Valoración": "Rating tablet",
 "Scooter retro": "Retro scooter",
 "Moto deportiva verde": "Green sports motorcycle",
 "Sofá Cazafantasmas": "Ghostbusters sofa",
 "Sofá modular verde Matrix": "Matrix green modular sofa",
 "Moto custom": "Custom motorcycle",
 "Televisor de piedra": "Stone television",
 "Sofá futurista rojo": "Red futuristic sofa",
 "Sofá dragón": "Dragon sofa",
 "Sofá bárbaro": "Barbarian sofa",
 "Coche Cazafantasmas": "Ghostbusters car",
 "Pinball espacial": "Space pinball",
 "Sofá murciélago": "Bat sofa",
 "Cuadro familia ogro": "Ogre family painting",
 "Mesa sándwich": "Sandwich table",
 "Sofá familia amarilla": "Yellow family sofa",
 "Sofá amarillo": "Yellow sofa",
 "Mesa casco espacial": "Space helmet table",
 "Mesa ogro": "Ogre table",
 "Sillón gorila": "Gorilla armchair",
 "Sofá verde": "Green sofa",
 "Chanclas azules": "Blue flip-flops",
 "Máquina arcade": "Arcade machine",
 "Caballo de madera": "Wooden horse",
 "Silla de madera": "Wooden chair",
 "Barra frente verde friso + encimera roble": "Green panelled counter + Oak worktop",
 "Mueble trasero nogal": "Walnut back cabinet",
 "Cafetera espresso 3 grupos + molinos": "Three-group espresso machine + Grinders",
 "Vitrina de bollería refrigerada": "Refrigerated pastry display case",
 "Pizarra digital 49\" · cafés": "49\" digital menu · Coffee",
 "Pizarra digital 49\" · bollería · vertical": "49\" digital menu · Pastries · Portrait",
 "Pizarra digital 49\" · temporada": "49\" digital menu · Seasonal",
 "Pantalla recogida de pedidos 43\"": "43\" order collection screen",
 "Balda de recogida (latón/roble)": "Collection shelf (brass/oak)",
 "Nevera bebidas frías puerta vidrio": "Cold drinks refrigerator with glass door",
 "Barra de ventana roble": "Oak window counter",
 "Taburete negro/roble · 1": "Black/oak stool · 1",
 "Taburetes": "Stools",
 "Mesa redonda Ø70 roble + pie negro · 1": "Round oak table Ø70 + Black base · 1",
 "Mesas": "Tables",
 "Silla de madera · 1": "Wooden chair · 1",
 "Sillas": "Chairs",
 "Sofá terciopelo verde 3 plazas": "Three-seat green velvet sofa",
 "Mesa baja nogal": "Walnut coffee table",
 "Estantería de libros nogal · cápsulas Blinkist": "Walnut bookcase · Blinkist capsules",
 "Lámpara colgante latón Ø40 · 1": "Brass pendant lamp Ø40 · 1",
 "Lámparas": "Lamps",
 "Planta en maceta · 1": "Potted plant · 1",
 "Plantas": "Plants",
 "TPV / caja": "POS / Checkout",
 "Altavoz techo · hilo musical": "Ceiling speaker · Background music",
 "Difusor de aroma (pared)": "Aroma diffuser (wall)",
 "Punto de acceso wifi (techo)": "Wi-Fi access point (ceiling)",
 "Gateway IoT / players (obrador)": "IoT gateway / Players (workroom)",
 "Router de la tienda": "Shop router",
 "Switch de red": "Network switch",
 "SAI": "UPS",
 "Cámara": "Camera",
 "Alarma": "Alarm",
 "Molinillo propio": "Coffee grinder",
 "Datáfono": "Card terminal",
 "Impresora de tickets": "Receipt printer",
 "Lavavajillas": "Dishwasher",
 "Horno": "Oven",
 "Frío bajo barra": "Under-counter refrigeration",
 "Climatización": "Air conditioning",
 "Amplificador de hilo musical": "Background music amplifier",
 "Cubo auxiliar del archivo original": "Auxiliary cube from the original file",
 "Silla Starbucks 1": "Starbucks chair 1",
 "Silla Starbucks 2": "Starbucks chair 2",
 "Silla Starbucks 3": "Starbucks chair 3",
 "Silla Starbucks 4": "Starbucks chair 4",
 "Planta 1": "Plant 1",
 "Planta 2": "Plant 2",
 "suelo": "floor",
 "pared fachada": "front wall",
 "escaparate 1": "shop window 1",
 "escaparate 3": "shop window 3",
 "puerta entrada": "entrance door",
 "puerta obrador": "workroom door",
 "pared fondo": "back wall",
 "marco 0 jamba 0.9": "frame 0 jamb 0.9",
 "marco 0 jamba 2.975": "frame 0 jamb 2.975",
 "marco 0 travesano 0.25": "frame 0 crosspiece 0.25",
 "marco 0 travesano 2.6750000000000003": "frame 0 crosspiece 2.6750000000000003",
 "marco 1 jamba 3.2": "frame 1 jamb 3.2",
 "marco 1 jamba 5.2749999999999995": "frame 1 jamb 5.2749999999999995",
 "marco 1 travesano 0.25": "frame 1 crosspiece 0.25",
 "marco 1 travesano 2.6750000000000003": "frame 1 crosspiece 2.6750000000000003",
 "marco 2 jamba 5.9": "frame 2 jamb 5.9",
 "marco 2 jamba 6.975": "frame 2 jamb 6.975",
 "marco 2 travesano 0": "frame 2 crosspiece 0",
 "marco 2 travesano 2.475": "frame 2 crosspiece 2.475",
 "puerta entrada · tirador": "entrance door · handle",
 "puerta obrador · tirador": "workroom door · handle",
 "led perimetral fachada0": "front perimeter LED0",
 "led perimetral fachada1": "front perimeter LED1",
 "led perimetral fachada2": "front perimeter LED2",
 "led perimetral fachada3": "front perimeter LED3",
 "led perimetral fondo0": "back perimeter LED0",
 "led perimetral fondo1": "back perimeter LED1",
 "Libro · the-hero-with-a-thousand-faces-en": "Book · the-hero-with-a-thousand-faces-en",
 "Libro · sapiens-en": "Book · sapiens-en",
 "Libro · creatividad-sa-es": "Book · creatividad-sa-es",
 "Libro · the-impossible-factory-en": "Book · the-impossible-factory-en",
 "Libro · co-intelligence-en": "Book · co-intelligence-en",
 "Libro · creative-confidence-en": "Book · creative-confidence-en",
 "Librería original · lateral": "Original bookcase · side",
 "Librería original · lateral.001": "Original bookcase · side.001",
 "Librería original · balda": "Original bookcase · shelf",
 "Librería original · balda.001": "Original bookcase · shelf.001",
 "Librería original · balda.002": "Original bookcase · shelf.002",
 "Librería original · balda.003": "Original bookcase · shelf.003",
 "Librería original · trasera": "Original bookcase · back",
 "Librería original · liston-laton": "Original bookcase · brass trim"
};
const categories={"Mobiliario": ["Mobiliario", "Furniture"], "Decoración": ["Decoración", "Decoration"], "Equipamiento": ["Equipamiento", "Equipment"], "Pantallas": ["Pantallas", "Screens"], "Iluminacion": ["Iluminación", "Lighting"], "Vegetacion": ["Vegetación", "Plants"], "Arquitectura": ["Arquitectura", "Architecture"], "Desglose": ["Desglose", "Breakdown"]};
export function inventoryName(value,lang='es'){return lang==='en'?(names[value]||value):value;}
export function inventoryCategory(value,lang='es'){return categories[value]?.[lang==='en'?1:0]||value;}
export function inventoryCaption(count,lang='es'){return (lang==='en'?'Inventory/ITIL':'Inventario/ITIL')+' · '+count+' '+(lang==='en'?'items':'elementos');}
export function localizedRow(row,lang='es'){
 const asset=row.asset?{...row.asset,name:inventoryName(row.asset.name,lang)}:undefined;
 const custom=row.item?.type==='custom';
 return {...row,asset,name:custom&&row.name!==row.asset?.name?row.name:inventoryName(row.name,lang),category:inventoryCategory(row.category,lang)};
}
export function cafeRecordName(row,original,lang='es'){
 return original&&row.nombre===original.nombre?inventoryName(row.nombre,lang):row.nombre;
}
