import {clone,parseBundle,documentKey} from './surface-state.mjs';
import {readAppearance,saveAppearance,readImage} from './surface-store.mjs';
const sessions=new Map();
const names={es:{'#ad855b':'Madera · tablero / cuerpo','#181c1c':'Base y estructura negra','#745640':'Listones de madera','#8f9693':'Metal','#d3c7ae':'Piedra / encimera','#9eccc6':'Cristal','#e6dbc5':'Crema','#006241':'Verde Starbucks','#ffe2a0':'Luz cálida','#61544b':'Paneles oscuros'},en:{'#ad855b':'Wood · top / body','#181c1c':'Black base and frame','#745640':'Wood slats','#8f9693':'Metal','#d3c7ae':'Stone / countertop','#9eccc6':'Glass','#e6dbc5':'Cream','#006241':'Starbucks green','#ffe2a0':'Warm light','#61544b':'Dark panels'}};
export async function mountSurfaceEditor(host,api,identity,{en=false}={}){
 const t=(es,english)=>en?english:es,language=en?'en':'es';
 const button=host.querySelector('[data-edit-surfaces]'),panel=document.createElement('section');panel.className='surface-editor';panel.hidden=true;panel.setAttribute('aria-label',t('Editor de superficies 3D','3D surface editor'));host.append(panel);
 panel.innerHTML=`<header><div><h3>${t('Diseña esta unidad','Design this unit')}</h3><p data-identity></p></div><button type="button" data-close aria-label="${t('Cerrar editor','Close editor')}">×</button></header>
 <p>${t('Elige una superficie o tócala en el modelo. Arrastra para girarlo.','Choose a surface or click it on the model. Drag to orbit.')}</p>
 <fieldset><label>${t('Superficie','Surface')}<select data-surface></select></label>
 <div class="surface-swatches" data-swatches aria-label="${t('Paleta rápida','Quick palette')}"></div>
 <div class="surface-grid"><label>${t('Color','Colour')}<input type="color" data-color></label><label>${t('Código de color','Colour code')}<input data-hex maxlength="7" pattern="#[0-9a-fA-F]{6}" spellcheck="false"></label></div>
 <label>${t('Imagen importada · PNG, JPG o WebP · máx. 20 MB','Imported image · PNG, JPG or WebP · max 20 MB')}<input type="file" data-image accept="image/png,image/jpeg,image/webp"></label>
 <div class="surface-toolbar"><img class="surface-image" data-thumbnail alt="${t('Textura de la superficie','Surface texture')}" hidden><button type="button" data-remove>${t('Quitar imagen','Remove image')}</button><button type="button" data-pattern="checks">${t('Cuadros','Checks')}</button><button type="button" data-pattern="stripes">${t('Rayas','Stripes')}</button><button type="button" data-pattern="terrazzo">${t('Terrazo','Terrazzo')}</button></div>
 <div class="surface-grid"><label>${t('Repetición','Repeat')} <output data-repeat-value></output><input type="range" data-repeat min="0.25" max="16" step="0.25"></label><label>${t('Rotación','Rotation')} <output data-rotation-value></output><input type="range" data-rotation min="-180" max="180" step="5"></label><label>${t('Rugosidad · mate ↔ pulido','Roughness · matte ↔ polished')} <output data-roughness-value></output><input type="range" data-roughness min="0" max="1" step="0.05"></label><label>${t('Metalizado','Metalness')} <output data-metalness-value></output><input type="range" data-metalness min="0" max="1" step="0.05"></label></div>
 <div class="surface-toolbar"><button type="button" data-undo>${t('Deshacer','Undo')}</button><button type="button" data-redo>${t('Rehacer','Redo')}</button><button type="button" data-original aria-pressed="false">${t('Comparar original','Compare original')}</button><button type="button" data-reset>${t('Restaurar superficie','Reset surface')}</button></div>
 <div class="surface-toolbar"><button type="button" class="surface-primary" data-apply>${t('Aplicar al Xpacio','Apply to Xpacio')}</button><button type="button" data-cancel>${t('Descartar borrador','Discard draft')}</button><a data-xpacio target="_blank" rel="noopener">${t('Ver Xpacio Best ↗','View Best Xpacio ↗')}</a></div>
 <details><summary>${t('Histórico de acabados','Finish history')}</summary><ol data-history></ol></details>
 <details><summary>${t('Copia y transferencia','Backup and transfer')}</summary><p>${t('Exporta imágenes e histórico en JSON. Importar recupera el acabado como una nueva versión de esta unidad.','Export images and history as JSON. Import restores the finish as a new version of this unit.')}</p><div class="surface-toolbar"><button type="button" data-export>${t('Exportar copia JSON','Export JSON backup')}</button></div><label>${t('Importar copia de esta unidad','Import this unit’s backup')}<input type="file" data-import accept="application/json,.json"></label></details></fieldset>
 <p class="surface-status" data-message role="status" aria-live="polite"></p><p>${t('Guardado local en este navegador y dominio; se comparte entre sus pestañas. Imágenes optimizadas a 1024 px. Better y Best muestran el acabado; Good y la foto Matrix conservan su vista. Los GLB/Blender originales y la ficha patrimonial de Yokup permanecen como referencia. Exporta una copia para llevarlo a otro navegador.','Stored locally in this browser and domain, shared between its tabs. Images optimized to 1024 px. Better and Best show the finish; Good and the Matrix photo retain their view. Original GLB/Blender and Yokup lifecycle records remain reference sources. Export a backup to transfer to another browser.')}</p>`;
 const stage=host.querySelector('.model-stage'),placeholder=document.createComment('3D stage'),workspace=document.createElement('dialog'),previewWrap=document.createElement('div'),camera=document.createElement('div');workspace.className='surface-workspace';workspace.setAttribute('aria-label',t('Editor de superficies 3D','3D surface editor'));stage.before(placeholder);previewWrap.className='surface-preview';camera.className='surface-camera surface-toolbar';
 for(const [label,action] of [[t('Perspectiva','Perspective'),()=>api.view('home')],[t('Frontal','Front'),()=>api.view('front')],[t('Planta','Top'),()=>api.view('top')],[t('Acercar','Zoom in'),()=>api.zoom(.15)],[t('Alejar','Zoom out'),()=>api.zoom(-.15)]]){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=action;camera.append(b);}
 previewWrap.append(camera);workspace.append(previewWrap,panel);host.append(workspace);
 const $=selector=>panel.querySelector(selector),surfaces=api.binding.surfaces,key=documentKey(identity);let disposed=false,busy=false,original=false,previewTicket=0,doc=null,previewReady=false,gesture=null;
 const state=sessions.get(key)||{patches:{},undo:[],redo:[],images:{},dirty:false};sessions.set(key,state);
 $('[data-identity]').textContent=identity.code+' · '+identity.instance;
 button.textContent=t('✎ Editar','✎ Edit');button.disabled=true;button.setAttribute('aria-expanded','false');panel.id='surface-editor';button.setAttribute('aria-controls',panel.id);
 const xpacio=new URL('/admira-xp/',location.href);xpacio.searchParams.set('autostart','xtanco');xpacio.searchParams.set('visual','best');xpacio.searchParams.set('loc',identity.venue);xpacio.searchParams.set('lang',language);const brand=new URL(location.href).searchParams.get('marca');if(brand)xpacio.searchParams.set('marca',brand);$('[data-xpacio]').href=xpacio.href;
 for(const surface of surfaces){const option=document.createElement('option');option.value=surface.key;option.textContent=identity.instance.startsWith('sb-table')&&surface.key==='#ad855b'?t('Tablero','Tabletop'):identity.instance.startsWith('sb-table')&&surface.key==='#181c1c'?t('Pie y base','Pedestal and base'):names[language][surface.key]||surface.key;$('[data-surface]').append(option);}
 if(surfaces.some(s=>s.key==='#ad855b'))$('[data-surface]').value='#ad855b';
 const message=(value,error=false)=>{if(disposed)return;$('[data-message]').textContent=value;$('[data-message]').classList.toggle('surface-error',error);};
 const dirty=()=>JSON.stringify(state.patches)!==JSON.stringify(doc?.patches||{});
 function updateButtons(){state.dirty=dirty();$('[data-undo]').disabled=!state.undo.length;$('[data-redo]').disabled=!state.redo.length;$('[data-apply]').disabled=!state.dirty||!previewReady;$('[data-cancel]').disabled=!state.dirty;}
 function selected(){const s=surfaces.find(s=>s.key===$('[data-surface]').value);return {...s,...state.patches[s.key]};}
 async function preview(){const ticket=++previewTicket;previewReady=false;updateButtons();try{const applied=await api.binding.apply(original?{}:state.patches,state.images);if(disposed||ticket!==previewTicket||!applied)return;api.draw();previewReady=true;updateButtons();message(state.dirty?t('Vista previa · cambios sin aplicar','Preview · unapplied changes'):t('Acabado aplicado · versión ','Applied finish · version ')+(doc?.revision||0));if(original)message(t('Comparando con el original · tu borrador se conserva','Comparing original · your draft is retained'));}catch(error){if(ticket===previewTicket)message(t('No se pudo cargar la textura: ','Could not load texture: ')+error.message,true);}}
 async function fields(){const p=selected();$('[data-color]').value=p.color;$('[data-hex]').value=p.color;for(const k of ['repeat','rotation','roughness','metalness']){$('[data-'+k+']').value=p[k];$('[data-'+k+'-value]').textContent=Math.round(p[k]*100)/100+(k==='rotation'?'°':'');$('[data-'+k+']').disabled=(k==='repeat'||k==='rotation')&&!p.image;}
  const image=$('[data-thumbnail]');image.hidden=!p.image;image.removeAttribute('src');if(p.image){const id=p.image,data=state.images[id]||await readImage(id).catch(error=>{message(error.message,true);return null;});if(!disposed&&selected().image===id&&data)image.src=data;}$('[data-remove]').disabled=!p.image;updateButtons();}
 function edit(change,group=null){if(busy||disposed)return;if(!group||gesture!==group)state.undo.push(clone(state.patches));if(state.undo.length>100)state.undo.shift();state.redo=[];gesture=group;state.action='apply';const surface=selected();state.patches[surface.key]={...surface,...change};delete state.patches[surface.key].key;original=false;$('[data-original]').setAttribute('aria-pressed','false');fields();preview();}
 const run=async task=>{if(busy||disposed)return;busy=true;$('fieldset').disabled=true;button.disabled=true;try{await task();}catch(error){message(error.message==='CONFLICT'?t('Otra pestaña guardó una versión. Exporta tu borrador y pulsa Recargar versión guardada.','Another tab saved a version. Export your draft, then click Reload saved version.'):t('No se pudo completar: ','Could not complete: ')+error.message,true);
 if(error.message==='CONFLICT'){$('[data-cancel]').textContent=t('Recargar versión guardada','Reload saved version');$('[data-cancel]').disabled=false;}}
 finally{busy=false;if(!disposed){$('fieldset').disabled=false;button.disabled=false;}}};
 function show(value){panel.hidden=!value;button.setAttribute('aria-expanded',String(value));if(value){previewWrap.prepend(stage);workspace.showModal();$('[data-surface]').focus();}else{workspace.close();placeholder.after(stage);button.focus();}api.draw();}
 workspace.addEventListener('cancel',event=>{event.preventDefault();show(false);});
 button.onclick=()=>show(panel.hidden);$('[data-close]').onclick=()=>show(false);
 api.onPick=surface=>{if(!panel.hidden&&surface){$('[data-surface]').value=surface;fields();}};
 $('[data-surface]').onchange=()=>fields();
 $('[data-color]').oninput=event=>edit({color:event.target.value},'color');$('[data-color]').onchange=()=>{gesture=null;};$('[data-hex]').onchange=event=>{if(/^#[0-9a-f]{6}$/i.test(event.target.value))edit({color:event.target.value});else {message(t('Usa un color hexadecimal como #006241.','Use a hex colour such as #006241.'),true);fields();}};
 for(const k of ['repeat','rotation','roughness','metalness'])$('[data-'+k+']').oninput=event=>edit({[k]:Number(event.target.value)},k);
 for(const k of ['repeat','rotation','roughness','metalness'])$('[data-'+k+']').onchange=()=>{gesture=null;};
 for(const color of ['#006241','#ad855b','#f3eadb','#181c1c','#cf684b','#397eb1','#be9451']){const swatch=document.createElement('button');swatch.type='button';swatch.style.background=color;swatch.setAttribute('aria-label',t('Color ','Colour ')+color);swatch.onclick=()=>edit({color});$('[data-swatches]').append(swatch);}
 $('[data-remove]').onclick=()=>edit({image:null});
 const putImage=data=>{const id=crypto.randomUUID();state.images[id]=data;edit({image:id,color:'#ffffff'});};
 $('[data-image]').onchange=event=>run(async()=>{const file=event.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024)throw Error(t('Usa PNG, JPG o WebP de hasta 20 MB.','Use PNG, JPG or WebP up to 20 MB.'));
 const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>64000000)throw Error(t('Imagen demasiado grande.','Image dimensions too large.'));const scale=Math.min(1,1024/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);busy=false;putImage(canvas.toDataURL('image/webp',.9));busy=true;}finally{bitmap.close();event.target.value='';}});
 for(const b of panel.querySelectorAll('[data-pattern]'))b.onclick=()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=512;const c=canvas.getContext('2d'),pattern=b.dataset.pattern;c.fillStyle='#f1e6d2';c.fillRect(0,0,512,512);c.fillStyle=selected().color;
  if(pattern==='checks'){for(let x=0;x<8;x++)for(let y=0;y<8;y++)if((x+y)%2)c.fillRect(x*64,y*64,64,64);}
  if(pattern==='stripes')for(let x=0;x<512;x+=64)c.fillRect(x,0,32,512);
  if(pattern==='terrazzo')for(let i=0;i<200;i++){c.fillStyle=[selected().color,'#9f8266','#fffaf0'][i%3];c.beginPath();const x=(i*71)%512,y=(i*149)%512;c.moveTo(x,y);c.lineTo(x+5+i%13,y+3);c.lineTo(x+3,y+5+i%11);c.fill();}
  putImage(canvas.toDataURL('image/webp',.9));};
 for(const action of ['undo','redo'])$('[data-'+action+']').onclick=()=>{const source=state[action],target=state[action==='undo'?'redo':'undo'];if(!source.length)return;target.push(clone(state.patches));state.patches=source.pop();original=false;$('[data-original]').setAttribute('aria-pressed','false');fields();preview();};
 $('[data-original]').onclick=()=>{original=!original;$('[data-original]').setAttribute('aria-pressed',String(original));preview();};
 $('[data-reset]').onclick=()=>{state.undo.push(clone(state.patches));state.redo=[];delete state.patches[$('[data-surface]').value];original=false;$('[data-original]').setAttribute('aria-pressed','false');fields();preview();};
 function history(){const list=$('[data-history]');list.replaceChildren();if(!doc?.history?.length){const item=document.createElement('li');item.textContent=t('Todavía no hay versiones guardadas.','No saved versions yet.');list.append(item);return;}
  for(const event of [...doc.history].reverse()){const item=document.createElement('li');item.textContent='v'+event.revision+' · '+new Date(event.date).toLocaleString(language)+' · '+({apply:t('Aplicado','Applied'),restore:t('Recuperado','Restored'),import:t('Importado','Imported')}[event.action]||event.action);const restore=document.createElement('button');restore.type='button';restore.textContent=t('Recuperar','Restore');restore.onclick=()=>{state.undo.push(clone(state.patches));state.redo=[];state.patches=clone(event.patches);state.action='restore';original=false;$('[data-original]').setAttribute('aria-pressed','false');fields();preview();};item.append(restore);list.append(item);}}
 // Images are saved atomically with the chosen appearance.
 $('[data-apply]').onclick=()=>run(async()=>{doc=await saveAppearance(identity,state.patches,doc?.revision||0,state.action||'apply',Object.fromEntries(Object.entries(state.images).filter(([id])=>Object.values(state.patches).some(p=>p.image===id))));state.undo=[];state.redo=[];original=false;$('[data-original]').setAttribute('aria-pressed','false');history();await preview();});
 $('[data-cancel]').onclick=()=>run(async()=>{doc=await readAppearance(identity);state.patches=clone(doc?.patches||{});state.undo=[];state.redo=[];original=false;$('[data-original]').setAttribute('aria-pressed','false');$('[data-cancel]').textContent=t('Descartar borrador','Discard draft');history();await fields();await preview();});
 $('[data-export]').onclick=()=>run(async()=>{const images={},all=[state.patches,...(doc?.history||[]).map(e=>e.patches)];for(const p of all)for(const value of Object.values(p))if(value.image&&!images[value.image])images[value.image]=state.images[value.image]||await readImage(value.image);
 const blob=new Blob([JSON.stringify({schema:1,identity,patches:state.patches,history:doc?.history||[],images},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=identity.code+'-textures.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message(t('Copia exportada con imágenes e histórico.','Backup exported with images and history.'));});
 $('[data-import]').onchange=event=>run(async()=>{const file=event.target.files[0];if(!file)return;try{if(file.size>40*1024*1024)throw Error(t('Copia demasiado grande (máx. 40 MB).','Backup too large (max 40 MB).'));const bundle=parseBundle(JSON.parse(await file.text()),identity,surfaces.map(s=>s.key));state.undo.push(clone(state.patches));state.redo=[];for(const [oldId,data]of Object.entries(bundle.images)){const newId=crypto.randomUUID();state.images[newId]=data;for(const patch of Object.values(bundle.patches))if(patch.image===oldId)patch.image=newId;}state.patches=bundle.patches;state.action='import';original=false;$('[data-original]').setAttribute('aria-pressed','false');await fields();await preview();}finally{event.target.value='';}});
 panel.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();show(false);button.focus();}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'&&!['INPUT','SELECT'].includes(event.target.tagName)){event.preventDefault();$('[data-'+(event.shiftKey?'redo':'undo')+']').click();}});
 if(identity.instance==='sb-water-rack'){const notice=document.createElement('p');notice.textContent=t('El botellero no está colocado en el Xpacio de referencia. Editarlo no inventa su ubicación; este acabado se conserva para su instancia cuando se coloque.','The water rack is not placed in the reference Xpacio. Editing does not invent a location; its finish is retained for its instance when placed.');panel.append(notice);}
 const beforeUnload=event=>{if([...sessions.values()].some(session=>session.dirty)){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',beforeUnload);
 try{doc=await readAppearance(identity);if(!state.dirty)state.patches=clone(doc?.patches||{});await fields();history();await preview();button.disabled=false;}catch(error){button.disabled=false;await fields();history();await preview();message(t('El almacenamiento local no está disponible: ','Local storage is unavailable: ')+error.message,true);}
 return()=>{disposed=true;previewTicket++;api.onPick=null;button.onclick=null;button.disabled=true;window.removeEventListener('beforeunload',beforeUnload);workspace.close();placeholder.after(stage);workspace.remove();placeholder.remove();};
}
